### ISSUE TITLE
cannot include std headers

### ISSUE THREAD

**Issue by konradglas** [clangd/vscode-clangd#100]
Hi! 

Thanks a lot for this cool extension... However, I am not able to use it properly as it seems. I get an include squiggle when trying to include `vector` (and subsequently using std::vector). I have made a little minimal reproduction example [here](https://github.com/konradglas/Cmake-tools-import-errors/tree/clangd) /branch clangd. Maybe I am missing something very obvious here. But compile_commands.json are clearly in the path where clangd should be looking for and when pasting this command directly in the terminal all is fine ... When trying some other code, the extension seems to work fine as well... I am just not able to include any std headers ...

Note that this compile_commands.json was generated by cmake (but I have excluded the CMakeLists.txt from the project in order to make it as minimal as possible). So one would need to adapt some local paths probably.

If this is a user error I would be very happy if someone would show me how to do this properly :)

**Comment by HighCommander4** [comment]
Please upload a clangd log (from vscode's Output view, after selecting "Clangd Language Server" from the dropdown).

**Comment by konradglas** [comment]
Sure thing. btw... I am using xcode clang 12 on MacOS Catalina
```I[07:56:27.218] clangd version 11.0.0 (https://github.com/llvm/llvm-project 176249bd6732a8044d457092ed932768724a6f06)
I[07:56:27.219] PID: 737
I[07:56:27.219] Working directory: /Users/konrad/Cmake-tools-import-errors
I[07:56:27.219] argv[0]: /Users/konrad/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/bin/clangd
I[07:56:27.219] argv[1]: --compile-commands-dir="/Users/konrad/Cmake-tools-import-errors/build"
Path specified by --compile-commands-dir does not exist. The argument will be ignored.
I[07:56:27.219] Starting LSP over stdin/stdout
I[07:56:27.221] <-- initialize(0)
I[07:56:27.222] Client supports legacy semanticHighlights notification and standard semanticTokens request, choosing the latter (no notifications).
I[07:56:28.255] --> reply:initialize(0) 1034 ms
I[07:56:28.260] <-- initialized
I[07:56:28.260] <-- textDocument/didOpen
I[07:56:28.261] Loaded compilation database from /Users/konrad/Cmake-tools-import-errors
I[07:56:28.261] --> window/workDoneProgress/create(0)
I[07:56:28.261] Enqueueing 1 commands for indexing
I[07:56:28.262] <-- reply(0)
I[07:56:28.262] --> $/progress
I[07:56:28.262] --> $/progress
I[07:56:28.263] ASTWorker building file /Users/konrad/Cmake-tools-import-errors/Source/main.cpp version 1 with command 
[/Users/konrad/Cmake-tools-import-errors/build/Clang 12.0.0/Debug]
/usr/bin/clang++ --driver-mode=g++ -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.15 -std=c++17 -o CMakeFiles/includeErrors.dir/Source/main.cpp.o -c /Users/konrad/Cmake-tools-import-errors/Source/main.cpp -fsyntax-only -resource-dir=/Users/konrad/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/lib/clang/11.0.0
I[07:56:28.265] <-- textDocument/documentSymbol(1)
I[07:56:28.265] <-- textDocument/codeAction(2)
I[07:56:28.265] <-- textDocument/documentLink(3)
I[07:56:28.274] --> textDocument/clangd.fileStatus
I[07:56:28.279] <-- $/cancelRequest
I[07:56:28.279] <-- textDocument/documentLink(4)
I[07:56:28.279] <-- $/cancelRequest
I[07:56:28.279] <-- textDocument/documentSymbol(5)
I[07:56:28.334] --> textDocument/publishDiagnostics
I[07:56:28.334] --> reply:textDocument/documentSymbol(1) 69 ms, error: Task was cancelled.
I[07:56:28.334] --> reply:textDocument/codeAction(2) 69 ms
I[07:56:28.334] --> reply:textDocument/documentLink(3) 69 ms, error: Task was cancelled.
I[07:56:28.334] --> reply:textDocument/documentLink(4) 54 ms
I[07:56:28.334] --> reply:textDocument/documentSymbol(5) 54 ms
I[07:56:28.334] --> textDocument/clangd.fileStatus
I[07:56:28.341] --> $/progress
I[07:56:28.341] --> $/progress
I[07:56:28.341] --> $/progress
I[07:56:28.343] Indexed /Users/konrad/Cmake-tools-import-errors/Source/main.cpp (1 symbols, 0 refs, 1 files)
I[07:56:28.344] Failed to compile /Users/konrad/Cmake-tools-import-errors/Source/main.cpp, index may be incomplete
I[07:56:28.400] --> $/progress
I[07:56:28.565] <-- textDocument/semanticTokens/full(6)
I[07:56:28.566] --> reply:textDocument/semanticTokens/full(6) 0 ms
I[07:56:28.566] --> textDocument/clangd.fileStatus
I[07:56:28.593] <-- textDocument/codeAction(7)
I[07:56:28.593] --> reply:textDocument/codeAction(7) 0 ms
I[07:56:28.593] --> textDocument/clangd.fileStatus
I[07:56:29.038] <-- textDocument/codeAction(8)
I[07:56:29.038] --> reply:textDocument/codeAction(8) 0 ms
I[07:56:29.038] --> textDocument/clangd.fileStatus```

**Comment by HighCommander4** [comment]
Does adding `--query-driver=/usr/bin/clang++` to the arguments passed to clangd (via vscode's `clangd.arguments` setting) help?

**Comment by konradglas** [comment]
oh yes!!!!! that helped for the simple as well for my complex projects! Thank you very much :)

**Comment by HighCommander4** [comment]
Great! It seems to be a common problem on Mac.

There is mention of this workaround [here](https://clangd.llvm.org/troubleshooting.html#cant-find-standard-library-headers-map-stdioh-etc), but it's said to only apply to unusual or cross-compilers and your case seems to be neither, so perhaps that documentation should be revised.

There is also https://github.com/clangd/clangd/issues/539 on file for making this workaround unnecessary in many cases.

**Comment by konradglas** [comment]
Yeah... this would get a +1 from me definitely ... Just fyi. This is by far the best intellisense experience I am having this far and the projects I am working on are fairly large ... So again: Thank you :)

**Comment by iambingoNJU** [comment]
+1. In my case, I use clang++ compiler which is not located in $PATH instead of gcc...
