### ISSUE TITLE
Go to definition using clangd

### ISSUE THREAD

**Issue by JanJamaszyk-FlyNow** [clangd/vscode-clangd#107]
Using vscode's go to definition feature (F12) does currently not use clangd but a global search of the repo.
In case their are multiple hits vscode fails to resolve the correct one, shows an overlay and asks the user to select the correct version:
![Screenshot from 2020-11-23 15-00-13](https://user-images.githubusercontent.com/66419585/99970780-9b627080-2d9c-11eb-87eb-903920368606.png)

Using clangd vscode should be able to resolve the correct reference and hence directly jump into the correct file. This would greatly improve the usability of vscode for C++ development in general.

**Comment by HighCommander4** [comment]
The request should be going to clangd. You can verify this by opening the Output view, choosing "Clangd Language Server" from the dropdown, and then performing if a `textDocument/definition` message is sent when you perform the go-to-definition.

Clangd can sometimes return multiple results when it's unable to determine an exact result. This is particularly the case inside templates.

If you feel there's a scenario where clangd should be able to produce an exact result but does not, please provide a self-contained code example where it happens.

**Comment by JanJamaszyk-FlyNow** [comment]
Thanks for the explanation, with your described procedure we where able to verify that in fact it is really clang making the weird recommendations. I will try to setup a minimal example and report it towards clangd.
Many thanks for the quick and helpful response!
Closing.
