### ISSUE TITLE
Extension creates .cache folder that interferes with git

### ISSUE THREAD

**Issue by dakennedyd** [clangd/vscode-clangd#111]
The extension creates .cache folder that interferes with git
I know you can modify .gitignore but i think all extensions folders should be kept inside .vscode dir 
Can we change that folder to .vscode/.cache/ ?

**System information**
Clangd version (from the log, or `clangd --version`): none
clangd extension version: 11
Operating system: Ubuntu 16.04

**Comment by sam-mccall** [comment]
It's not the vscode extension that creates the cache, but rather clangd itself. (This is why it's not in .vscode and also not a vscode-clangd issue per se).

There are a few reasons for this, including one person using multiple editors, wanting .gitignore rules to apply the same way for different people using different editors, and having a way to deal with files not contained in a vscode workspace.

**Comment by njames93** [comment]
Is there potential to add an argument to clangd to specify where the index should be stored, rather than defaulting `$ROOT/.cache/clangd/index/`?
