### ISSUE TITLE
cant disable squiggles

### ISSUE THREAD

**Issue by Kurt-Shiwz** [clangd/vscode-clangd#114]
clangd version 10.0.0 (https://github.com/llvm/llvm-project d32170dbd5b0d54436537b6b75beaf44324e0c28)
os: macos 10.15.7
vscode 1.51.1
clangd extesion v0.1.8

there are some error squiggles on many files, i build on linux server, so i want disable squiggles, but i dont find the config.

like this:
![image](https://user-images.githubusercontent.com/7554917/101644432-210a3f80-3a70-11eb-9a26-5675e05d2e68.png)

**Comment by sam-mccall** [comment]
If you don't have a working build (e.g. missing compile_commands.json, or not all the required headers, or the code is just not portable to your platform) then clangd isn't going to work very well. For example, if an #include is not found, then we're not going to be able to parse code that refers to types defined in that header. Go-to-definition is unlikely to work reliably etc.

So I'm not sure what your goal is here:
 - do you want a way to disable clangd for these files entirely?
 - do you want to hide the diagnostics, but keep using other clangd features (which are unlikely to work well, and you won't know why)
 - do you want to make use of your remote build setup with clangd? (VSCode remote development works well for this!)
 - do you want clangd to work well locally? (in which case you need to *fix* the errors, even on the local machine. How to do this depends on what they are)

**Comment by HighCommander4** [comment]
>    * do you want to hide the diagnostics, but keep using other clangd features (which are unlikely to work well, and you won't know why)

This can sometimes be useful, e.g. local declarations can often be resolved and navigated to.

(This is also one of the cases where allowing the textual heuristic for go-to-def to trigger for [non-dependent identifiers](https://searchfox.org/llvm/rev/163c223161b8cd33e812613b27fbc52ea6e0f880/clang-tools-extra/clangd/XRefs.cpp#459) would be helpful.)

**Comment by Kurt-Shiwz** [comment]
> If you don't have a working build (e.g. missing compile_commands.json, or not all the required headers, or the code is just not portable to your platform) then clangd isn't going to work very well. For example, if an #include is not found, then we're not going to be able to parse code that refers to types defined in that header. Go-to-definition is unlikely to work reliably etc.
> 
> So I'm not sure what your goal is here:
> 
> * do you want a way to disable clangd for these files entirely?
> * do you want to hide the diagnostics, but keep using other clangd features (which are unlikely to work well, and you won't know why)
> * do you want to make use of your remote build setup with clangd? (VSCode remote development works well for this!)
> * do you want clangd to work well locally? (in which case you need to _fix_ the errors, even on the local machine. How to do this depends on what they are)

just hide the diagnostics, there is too many

**Comment by sam-mccall** [comment]
Clangd 12 will support this with config:

```
Diagnostics:
  Suppress: *
```

**Comment by tangdading6** [comment]
clangd version 12.0.0

When I have add the follow code to ~/.config/clangd/config.yaml, 
```
Diagnostics:
  Suppress: *
```
I get the error info from vscode-clangd.
![Screenshot_20210227_071825](https://user-images.githubusercontent.com/8147824/109365422-17081800-78cc-11eb-8e7b-cb2e33b93496.png)

**Comment by i-ky** [comment]
`*` needs to be in quotes: `'*'` or `"*"`, otherwise it is interpreted as an anchor reference in YAML.

**Comment by tangdading6** [comment]
> `*` needs to be in quotes: `'*'` or `"*"`, otherwise it is interpreted as an anchor reference in YAML.

Thanks!
