### ISSUE TITLE
"On Config Changed" doesn't support compile-commands-dir

### ISSUE THREAD

**Issue by mihe** [clangd/vscode-clangd#123]
**Current behavior**

With `--compile-commands-dir=some/directory` as part of the `clangd.arguments` setting, the file watcher that's meant to prompt or restart clangd fails to react to any changes in the provided directory.

**Expected behavior**

I expect the extension to prompt me for an action (assuming `clangd.onConfigChanged` is set to `prompt`), when a configuration file inside the provided `--compile-commands-dir` directory changes.

**Steps to reproduce**

1. Set the setting `clangd.arguments` to `["--compile-commands-dir=.clangd"]`
1. Set the setting `clangd.onConfigChanged` to `"prompt"`
1. Create a directory somewhere, meant to be the workspace
1. Add an empty `main.cpp` file to this workspace directory
1. Add a `.clangd` directory to this workspace directory
1. Add a `compile_commands.json` file to this `.clangd` directory, with the contents `[]`
1. Open VS Code in the workspace directory
1. Open `main.cpp` in this instance of VS Code
1. Open the extension output panel in VS Code
1. Note the message "Loaded compilation database from /your/workspace/path/.clangd"
1. Change the contents of `compile_commands.json`
1. Note how there's no prompt about restarting the language server

**Thoughts**

When looking at the code, it's clear that the file watcher does not accommodate for the `--compile-commands-dir` argument, and instead assumes that the configuration files are located either in the root of any of the workspace folders, or a `build` folder within any of them, as seen here:

https://github.com/clangd/vscode-clangd/blob/11f5b680647de3c195997515ecc85d0983fe4395/src/config-file-watcher.ts#L26-L29

**System information**

Clangd version: 11.0.0
Clangd extension version: 0.1.8
Operating system: Windows 10 Enterprise (10.0.19042)

**Comment by HighCommander4** [comment]
There is some relevant discussion in [this review comment](https://github.com/clangd/vscode-clangd/pull/33#discussion_r495219637).

I disagree with the characterization in that comment, that "`compile-commands-dir` is probably not a major use case"; I think it is an important use case.

However, the limitation described in that comment (that vscode only allows watching files inside the workspace folder) likely means that this feature can only be supported on the server side. The good news is, the server-side watcher is being worked on.

**Comment by HighCommander4** [comment]
> The good news is, the server-side watcher is being worked on.

Actually, it looks like [it may already be in clangd trunk](https://reviews.llvm.org/D92663), though I haven't tried it yet.

**Comment by sam-mccall** [comment]
Yeah, clangd trunk will now pick up changes to CDBs without restarting. I've added code to the vscode extension to turn off the file-watching/restart when such a version of clangd is used. I don't think we should try to make the watcher work for older versions of clangd. (This will be in clangd 12, the release branch is starting real soon now)
