### ISSUE TITLE
there is some error when implicit conversions with operator

### ISSUE THREAD

**Issue by Kurt-Shiwz** [clangd/vscode-clangd#124]
![image](https://user-images.githubusercontent.com/7554917/102758184-53d80000-43ad-11eb-932c-e9d998d9f821.png)

![image](https://user-images.githubusercontent.com/7554917/102757694-ab29a080-43ac-11eb-98ff-4854ce635aa3.png)

clangd version 10.0.0 (https://github.com/llvm/llvm-project d32170dbd5b0d54436537b6b75beaf44324e0c28)
os: macos 11.1 (20C69)
vscode 1.52.1
clangd extesion v0.1.8

**Comment by HighCommander4** [comment]
What compiler are you using to build the project?

Can you post a complete code example that triggers the error?

**Comment by Kurt-Shiwz** [comment]
> What compiler are you using to build the project?
> 
> Can you post a complete code example that triggers the error?

this project use cmake.
