### ISSUE TITLE
Same semantic token type for member function and variables

### ISSUE THREAD

**Issue by mirkow** [clangd/vscode-clangd#126]
clangd-11 provides for member functions and member variables the same semantic token type, i.e. "member". The VSCode C++ model categorizes member variables as "property" and functions as "member". Thus, with clangd member functions and member variables cannot have different colors.

**System information**
Clangd version (from the log, or `clangd --version`): clangd version 11.0.0 (https://github.com/llvm/llvm-project 176249bd6732a8044d457092ed932768724a6f06)
clangd extension version: v0.1.8
Operating system: Ubuntu 18.04

**Comment by HighCommander4** [comment]
I believe this has been fixed for clangd 12 in #105.
