### ISSUE TITLE
Highlighting on Extensionless Headers

### ISSUE THREAD

**Issue by cpsauer** [clangd/vscode-clangd#139]
C++ Headers without extensions aren't automatically highlighted or processed by clangd. It'd be awesome to have clangd's help when browsing those files. I assume this is because they aren't seen as c-family language files by the extension and/or vscode.

More details:

- I just ran into this with Eigen, a popular linear algebra library. An example header would be "Eigen/Dense"
- Others have run into this with standard libraries in the past, since many of those headers have no extensions. 
  - Issues with extensionless standard library headers (e.g. `#include <iostream>`) discussed in https://github.com/clangd/clangd/issues/57. There's great discussion there. But we can't count on every third-party library having a magic comment at the top.
  - As mentioned in there, clangd-vscode.activate doesn't fix the issue. Nor does adding the file to compile_commands.json
  - However, manually telling VSCode to mark the file as C++ by clicking in the lower right does seem to fix the issue. I then see syntax highlighting and a clang error, since it's having trouble with the relative include paths.
- It seems like there are some simple heuristics that would mostly detect correctly whether an extensionless file should be picked up by clangd: Is the file listed in compile_commands.json? Do lines start with #include or #import? A more complex heuristic would be to see if it's included by files in the compile_commands.json, perhaps as part of a more general solution to the header issues people have been discussing in https://github.com/clangd/clangd/issues/519.

Thanks so, so much!

**Comment by i-ky** [comment]
Luckily, the problem is not specific to clangd extension or even to VS Code, so there are existing solutions. In my case [Modelines](https://marketplace.visualstudio.com/items?itemName=chrislajoie.vscode-modelines) extension has completely solved the issue for standard library headers.

**Comment by njames93** [comment]
For what its worth, this extension should treat any file with `-*- C++ -*-` in a comment on the first line, as well as any filename matching these globs `**/include/c++/**` or `**/MSVC/*/include/**` as c++ files.

**Comment by cpsauer** [comment]
Indeed. The issue, though, is about third-party libraries without those magic comments or paths.

**Comment by cpsauer** [comment]
Filed a VSCode issue because I thought, maybe, that it was better handled there, but they disagreed. 

VSCode's API suggestions for having plugins mark files where they can best determine the language are in the [issue linked above](https://github.com/microsoft/vscode/issues/115826), along with, perhaps, a little unnecessary hostility toward C++.

**Comment by i-ky** [comment]
I think VS Code developers are hostile to any language-specific suggestions, not just ones specific to C++. And probably rightly so.

@cpsauer, have you tried to speak to Eigen developers? If they don't use any hints (like modelines) in their extension-less headers, how are their users supposed to get syntax highlighting there?

If library developers don't cooperate, it will be the best approach to implement heuristics as a standalone VS Code extension. This way developers of clangd extension have less code to maintain and also users of other C++ extensions for VS Code can benefit from language detection in extension-less headers. It should be similar in operation to Modelines, but C++ specific this time.

**Comment by cpsauer** [comment]
I hear ya, i-ky, and I think it'd definitely an unfortunate language convention. Happy to talk to the [Eigen folks](https://gitlab.com/libeigen/eigen/-/issues/2143), but we're not going to win this by modlining all the libraries, right? There have got to be lots more that copied this convention from the standard library.

It seems like an area where we've already implemented some heuristics. And while they don't catch some of the cases that come up in normal usage, we've got the information to make things better easily. We've got the include paths, along with the compilation language, and we know that when the user jumps into an extensionless file via clangd it's in that same language... (though the #include or #ifdef heuristics are probably better and more general?)

Some intel about other editors or plugins that came up in my dig through: Sounds like the Microsoft C++ plugin handles this by marking extensionless files that the user CTRL+clicks through to an extensionless file, it marks it as the right language. Platform specific-editors (Android Studio, Xcode) pick this up without modlines via some heuristic.

**Comment by i-ky** [comment]
> we're not going to win this by modlining all the libraries, right?

Neither will we by adding heuristics to all editors/extensions. It is M&times;N problem. I used to believe that it easier solved on libraries' side, one library at a time... before I saw [the response from Eigen team](https://gitlab.com/libeigen/eigen/-/issues/2143#note_503401464), that is. Such arrogance of Eigen folks is upsetting. Anyway, @cpsauer, thank you for trying!

> There have got to be lots more that copied this convention from the standard library.

Well, [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf1-use-a-cpp-suffix-for-code-files-and-h-for-interface-files-if-your-project-doesnt-already-follow-another-convention), [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Self_contained_Headers) and [LLVM Coding Standards](https://llvm.org/docs/CodingStandards.html#self-contained-headers) advocate for `.h` extension. The latter even [mandates modeline](https://llvm.org/docs/CodingStandards.html#file-headers) to make it easier for editor to distinguish C and C++ headers. C++ Core Guidelines mention IDE aspect of the question, but perhaps they can be louder about it.

> Sounds like the Microsoft C++ plugin handles this by marking extensionless files that the user CTRL+clicks through to an extensionless file, it marks it as the right language.

As an occasional user of Microsoft's extension I can confirm, that this is the default behaviour. And I must say that this is very annoying. If you have `settings.json` under version control, it becomes an erratic hotspot of changes. So I turned this feature off in favor of Modelines extension.

**Comment by cpsauer** [comment]
VSCode has fixed this one after all, with an ML model. It's on by default as of the August release, so I'm going to close this issue!

Their [release notes](https://code.visualstudio.com/updates/v1_60#_automatic-language-detection), [issue](https://github.com/microsoft/vscode/issues/129004).
