### ISSUE TITLE
NOLINT/NOLINTNEXTLINE do not work

### ISSUE THREAD

**Issue by mrdimfox** [clangd/vscode-clangd#14]
I have `-clang-tidy` enabled and it works perfectly, except `NOLINT/NOLINTNEXTLINE` comments do not make any effect.

VS Code: 1.45.0
clang version 10.0.0

**Comment by sam-mccall** [comment]
Can you give a minimal example?

e.g. for me, with .clang-tidy:
```
Checks: bugprone-lambda-function-name
```
and test.cc:
```
auto x = [] { return __func__; };  // NOLINT
```
there's no warning, but one appears if I remove NOLINT.

**Comment by mrdimfox** [comment]
Hmm. Looks like it magically started to work. That's strange. Sorry for bothering when. Issue is solved.

**Comment by sam-mccall** [comment]
No worries, please reopen if you can reproduce.
