### ISSUE TITLE
Syntax Highlighting incorrectly classifying class fields as functions

### ISSUE THREAD

**Issue by dwilliamson** [clangd/vscode-clangd#142]
Issue Type: <b>Bug</b>

This is what `llvm-vs-code-extensions.vscode-clangd` does:

![HighlightClangd](https://user-images.githubusercontent.com/1532903/106731104-01723c00-6607-11eb-9cf4-365eb1ff1a75.gif)

This is what `ms-vscode.cpptools` does:

![HighlightCppTools](https://user-images.githubusercontent.com/1532903/106731218-25ce1880-6607-11eb-808a-b85cf9b32549.gif)

**Extension version**: 0.1.9
**VS Code version**: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
**OS version**: Windows_NT x64 10.0.18362
**Clangd version**: 11.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (13.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by njames93** [comment]
I can't reproduce this on trunk so it's likely been fixed. Could you test with the latest snapshot release https://github.com/clangd/clangd/releases/tag/snapshot_20210124

**Comment by dwilliamson** [comment]
Will this require Clang 12? I'm not sure how to get that on Windows without building RC1 myself.

**Comment by njames93** [comment]
Just download the clangd-windows-snapshot_20210124.zip and extract it, then in vscode settings, set `clangd.path` to the absolute location of the binary, will probably be of the format `<folder-where-you-extracted>/clangd-windows-snapshot_20210124/bin/clangd.exe`

**Comment by dwilliamson** [comment]
Sorry, I got the first zip not the second.

Yes, that works, thankyou.
