### ISSUE TITLE
workspaceFolderBasename is not expanded in config.

### ISSUE THREAD

**Issue by teki** [clangd/vscode-clangd#147]
**Please describe the problem.**
Trying to add this to command line arguments: `"--compile-commands-dir=${workspaceFolder}/bazel-${workspaceFolderBasename}"`

**Logs**
Expanded like this:

`I[12:21:38.983] argv[8]: --compile-commands-dir=/my/workspace/bazel-${workspaceFolderBasename}`

**System information**
clangd extension version: v0.1.9
Operating system: macOS 10.15.7

**Note:**
I can see the MS CPP extension used to have the same issue: https://github.com/microsoft/vscode-cpptools/pull/2495

**Comment by HighCommander4** [comment]
There's a PR fixing this at https://github.com/clangd/vscode-clangd/pull/642
