### ISSUE TITLE
Enable debugging for C++ without depending on ms-vscode.cpptools?

### ISSUE THREAD

**Issue by saschanaz** [clangd/vscode-clangd#148]
To debug the code on Windows I need to enable both clangd and ms-vscode.cpptools (because otherwise `cppvsdbg` isn't available in `launch.json`), but getting two language services is just redundant as it parses and analyzes the same files twice. Could vscode-clangd enable debugging for C++ files independently?

**Comment by abpostelnicu** [comment]
I don’t think so. The scopes are totally different. Clangd is a language server that is based on LSP and for debugging you would need LLDB or WinDBG or GDB and an interface for it.

**Comment by abpostelnicu** [comment]
@saschanaz a good starting point would be to have the possibility of disabling intellisense in the microsoft extension.

**Comment by saschanaz** [comment]
Oh, turns out `C_Cpp.intelliSenseEngine="Disabled"` is what I really wanted. Sorry for the noise 😅
