### ISSUE TITLE
Semantic highlighting flickers on and off as you type

### ISSUE THREAD

**Issue by HighCommander4** [clangd/vscode-clangd#161]
I've recently switched from the old semantic highlighting implementation (`TheiaSemanticHighlighting`) to the new one (`semanticTokens`), and I'm finding that with the new one, semantic highlightings flicker off and back on as I type.

It doesn't happen on every character, but maybe every few words or so. It happens even when writing a comment, so it's not related to the code being temporarily ill-formed or anything like that.

This did not happen with the old implementation.

Has anyone else experienced this?

**Comment by hokein** [comment]
I think this is a vscode-clangd related issue, and it was fixed in #150.
