### ISSUE TITLE
Add an option to stop showing warning about clangd + mscpp incompatibility

### ISSUE THREAD

**Issue by kirillbobyrev** [clangd/vscode-clangd#162]
Context: https://github.com/clangd/vscode-clangd/pull/141#issuecomment-784561701

**Comment by sam-mccall** [comment]
Maybe this shouldn't be a visible option, just a way to "never ask again"

**Comment by kirillbobyrev** [comment]
Yes, in my mind it looks like a button next to "Disable mscpp" on the
warning.

**Comment by theswordsmahin** [comment]
I agree with the above here. Our project was setting 
```
    "C_Cpp.autocomplete": "Disabled",  // So you don't get autocomplete from both extensions.
    "C_Cpp.errorSquiggles": "Disabled", // So you don't get error squiggles from both extensions
```
As clang's errors/autocomplete were much better, but leaving the `intellisenseEngine` enabled for the enhanced colorization

So an option to disable the warning would be great.

**Comment by matms** [comment]
I'm not very familiar with vscode-clangd's contribution process, but I also faced the same issue, so I have made a small patch adding a config option to disable this warning (https://github.com/matms/vscode-clangd/commit/95e90f77bc447f06959174b834dc06657ab34680).

I'm not sure if I should make a pull request?

**Comment by HighCommander4** [comment]
> I'm not sure if I should make a pull request?

I would say yes, go ahead

**Comment by kirillbobyrev** [comment]
> I'm not very familiar with vscode-clangd's contribution process, but I also faced the same issue, so I have made a small patch adding a config option to disable this warning ([matms@95e90f7](https://github.com/matms/vscode-clangd/commit/95e90f77bc447f06959174b834dc06657ab34680)).
> 
> I'm not sure if I should make a pull request?

Absolutely!

Sorry, this is actually my bad for forgetting about this and not delivering on my promise to fix this originally. I'll gladly review your patch and provide help if needed.

**Comment by kirillbobyrev** [comment]
Seems to be fixed, makes sense to close.

**Comment by kirillbobyrev** [comment]
The new GitHub UI makes me miss the button every time 😆 Thanks, @HighCommander4!
