### ISSUE TITLE
Allow user to expicitly set the compile_commands.json file

### ISSUE THREAD

**Issue by imikejackson** [clangd/vscode-clangd#163]
Note: we mostly implement features in the clangd language server, and rely on Microsoft's LSP client framework to expose these in VSCode. Features requiring a lot of VSCode-specific work are unlikely to be implemented.

I have a workspace with 20 different source folders. I have 1 build folder that contains a compile_commands.json file. Why must I symlink that file into ALL of the source directories?

**Comment by HighCommander4** [comment]
You can already do this by adding the following to a workspace's settings:

```
{
  "clangd.arguments": [
    "--compile-commands-dir",
    "<path>"
  ]
}
```

with `<path>` being the path to the directory containing the `compile_commands.json` file.

**Comment by imikejackson** [comment]
Ahh.. Makes sense, but not obvious in the instructions. From a user's perspective the line between VSCode exposed settings and clangd itself is a bit blurred. Maybe a short blurb in the ReadMe would help direct users to this setting. Thanks for the fast response.
