### ISSUE TITLE
Includes Not Recognized (using compile_flags.txt)

### ISSUE THREAD

**Issue by Hypro999** [clangd/vscode-clangd#166]
I'm working on a simple single file project which uses an external library ([MS MPI](https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi)) which has:
- header files at: `C:\Program Files (x86)\Microsoft SDKs\MPI\Include`
- static library files at: `C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64`

The source file (at it's essence) is basically:
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "mpi.h"  // 'mpi.h' file not found clang(pp_file_not_found)

int main(int argc, char **argv) {
    return 0;
}
```

Since this project I'm working on is extremely simple, I've decided not to use cmake and a `compile_commands.json` file but to rather use a `compile_flags.txt` file after reading the [docs](https://clangd.llvm.org/installation.html#compile_flagstxt) and seeing:

> Creating this file by hand is a reasonable place to start if your project is quite simple.

My `compile_flags.txt` file is as follows:
```
-Wall
-I "C:\Program Files (x86)\Microsoft SDKs\MPI\Include"
-I "C:\Program Files (x86)\Microsoft SDKs\MPI\Include\x64"
-L "C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64"
-l msmpi.lib
```

After looking at the logs, it seems like the `-L` and `-l` flags are unnecessary (ignored), but I've included them here anyways for the sake of completeness.

The problem I'm facing here is that include (`#include "mpi.h"`) is not being recognized even though I feel like I've set the necessary flags appropriately (I've spent well over a two hours trying to see if I've done something wrong but I just can't figure it out, hence only as a final act of desperation, I've opened this issue).

**Additional Information**
The script I use to compile my code (this works exactly as expected):
```batch
@echo off

:: Create output folders.
if not exist "obj\" mkdir "obj\"
if not exist "bin\" mkdir "bin\"

:: Invoke the MSVC compiler and tell it where to find the MSMPI headers (/I).
:: In the linker options, we specify where to find the corresponding dynamic library files.
cl ^
	/W4 ^
	/EHsc ^
	/Fo"obj/"\ ^
	/Fe"bin/"\ ^
	/I"C:\Program Files (x86)\Microsoft SDKs\MPI\Include" ^
	/I"C:\Program Files (x86)\Microsoft SDKs\MPI\Include\x64" ^
	%* ^
	/link ^
		/MACHINE:x64 ^
		/DYNAMICBASE "msmpi.lib" ^
		/LIBPATH:"C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64"
```

I've also tried to use clang instead of cl and that worked just as well too:
```batch
clang main.c ^
    -Wall ^
    -I "C:\Program Files (x86)\Microsoft SDKs\MPI\Include" ^
    -I "C:\Program Files (x86)\Microsoft SDKs\MPI\Include\x64" ^
    -L "C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64" ^
    -l msmpi.lib
```

**Logs**
[clangd_output.log](https://github.com/clangd/vscode-clangd/files/6139323/clangd_output.log)

**System information**
Clangd version (from the log, or `clangd --version`): 11.0.0
clangd extension version: 0.1.11
Operating system: Windows 10 20H2 (19042.867)

P.S. Apologies in advance in case this issue is just a result of me configuring clang incorrectly and the problem has nothing to do with the extension itself. I've reported this issue here since in the clang docs this extension has canonicalized over any other plugin for any other editor. Thank you in advance for any time and effort invested in helping me out.
> it has excellent language server support and most faithfully demonstrates what clangd can do.

**Comment by Hypro999** [comment]
Just for reference, when using Microsoft's C/C++ Extension with the following configuration, the imports are properly resolved and intellisense works exactly as intended:
```json
{
    "configurations": [
        {
            "name": "MPI",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\Program Files (x86)\\Microsoft SDKs\\MPI\\Include",
                "C:\\Program Files (x86)\\Microsoft SDKs\\MPI\\Include\\x64"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64",
            "compilerArgs": []
        }
    ],
    "version": 4
}
```

**Comment by sam-mccall** [comment]
>```
> -I "C:\Program Files (x86)\Microsoft SDKs\MPI\Include"
> -I "C:\Program Files (x86)\Microsoft SDKs\MPI\Include\x64"
> ```

This part is isn't quite right. -I and the path are separate arguments, and should not be shell-escaped. (Currently you're passing them as a single argument containing quotes and spaces)

Try:
```
-I
C:\Program Files (x86)\Microsoft SDKs\MPI\Include
```

See https://clang.llvm.org/docs/JSONCompilationDatabase.html#alternatives
