### ISSUE TITLE
[enhancement] It seems clangd semantic token cannot distinguish member function and member variable

### ISSUE THREAD

**Issue by HLEdeft** [clangd/vscode-clangd#169]
It's an issue about semantic highlighting. I start to use clangd instead of ms.vscode-cpptools to do code completion. However, I found that the semantic token type of member function and member variable generated by clangd are the exactly same . They are both recognized as "member" and the foreground is "entity.name.function.member". So I can not assign different syntax highlighting color for them by editing semantic tokens section in theme file. Considering that even in code completion reminder block, member variable and function have different colors, I think there should exist a way to distinguish their semantic types so they can have different syntax highlighting colors. I am not sure whether it is a bug. But I haven't found a solution online so far.  Hope you can improve this. Great thanks!

```cpp
#include <iostream>
class Bar {
public:
  void calling() {}
};
class Foo {
public:
  Bar bar;
  void calling() {}
};
int main() {
  Foo foo;
  Foo *pFoo = &foo;
  // I am talking about the following two lines
  foo.bar.calling();
  pFoo->bar.calling();
  foo.calling();
  return 0;
}
```
**Logs**
Since the log is a little long, so I upload it to my repo with the source file. Here it is. https://github.com/HLEdeft/highlighting

**System information**
Clangd version (from the log, or `clangd --version`): 11.0
clangd extension version: 0.1.11
Operating system: mac os x 10.14.6
vscode version: 1.54.3
other plugin: ms-vscode.cpptools with intelliSenseEngine disabled.
theme: build in solarized-dark. However, since they have same semantic type, they will always have the same color no matter what themes I am using.

**Comment by sam-mccall** [comment]
I think this was fixed in clangd 12, early versions of the spec were unclear.

Can you try https://github.com/clangd/clangd/releases/tag/12.0.0-rc2 ?

**Comment by HLEdeft** [comment]
Great thanks. It works now. The semantic token type of member variable is property now. And I think this issue can be closed.
