### ISSUE TITLE
Drop minimum required version of vscode?

### ISSUE THREAD

**Issue by DaanDeMeyer** [clangd/vscode-clangd#170]
https://github.com/clangd/vscode-clangd/pull/127 bumped the minimum required vscode version to 1.52. I'm running vscode-clangd in an environment that's struck on 1.50 for now. Was the engine update required or can the extension run on 1.50? If so, can we drop the minimum version again?

**Comment by HighCommander4** [comment]
It seems to be necessary for the fix to #58.

**Comment by DaanDeMeyer** [comment]
Ah, indeed, I just read the commit message. That's a shame, guess I'll have to live without semantic highlighting for a while because the flickering issue is only fixed in 1.11.

**Comment by HighCommander4** [comment]
> That's a shame, guess I'll have to live without semantic highlighting for a while because the flickering issue is only fixed in 1.11.

Yeah, unfortunately the fix for that (in #150) is in a vscode-languageclient version that **also** depends on vscode 1.52. (So, backing out the fix for #58 locally is not an option either.)
