### ISSUE TITLE
Ability to alter the "clangd.path": setting in settings.json

### ISSUE THREAD

**Issue by ItsCubeTime** [clangd/vscode-clangd#175]
Hi, currently it seems the setting is overriden and doesnt actually let you as a user to set it. Is there a reason for this? 

Ive tried using the clangd extension from my LLVM install several times in the past but currently since theres seemingly no way of changing what clangd executeable vs code uses the only way of using your own exe of choice seems to be literally replacing the file in that very directory.

![image](https://user-images.githubusercontent.com/20190653/113137699-2b219b00-9225-11eb-9c10-6e9fae008d4d.png)

In my case its just as simple as that I want to be able to use preview versions of clangd, but I wouldnt be surprised if there are more people out there who would like to be able to use a clangd.exe of there own.

Thanks for stopping by <3

**Comment by sam-mccall** [comment]
Hmm, that setting works for me. What happens when you try to set it and then reload the window?

"Sync: ignored" just means the setting won't be synced between machines when settings sync is turned on. This is correct as clangd may be installed in different locations on different machines. (The text is a bit confusing, but we don't control it, it's added by VSCode)

**Comment by ItsCubeTime** [comment]
> Hmm, that setting works for me. What happens when you try to set it and then reload the window?
> 
> "Sync: ignored" just means the setting won't be synced between machines when settings sync is turned on. This is correct as clangd may be installed in different locations on different machines. (The text is a bit confusing, but we don't control it, it's added by VSCode)

Hi again, yes my bad apparently. It actually seems to be working now, I will be sending a message here again if I encounter some issue - I would like to remember this not working in the past, maybe I forgot to add double backslashes last time.
