### ISSUE TITLE
add command open clangd configure

### ISSUE THREAD

**Issue by findNextStep** [clangd/vscode-clangd#176]
as clangd support configure file, can we have a way open/create configure file more quickly?

https://clangd.llvm.org/config.html

**Comment by njames93** [comment]
There's some issues with this. For global config this should be easy to implement. The project root would be OK too, but for any sub directory config files, we won't be able to create commands for those.

**Comment by findNextStep** [comment]
I think the global config is enough for most of time, we need some config for mac and if we can simple access global config it will be easy to use clangd.

most of time the global config and project root config is good enough
