### ISSUE TITLE
Switch to official semantic highlighting API

### ISSUE THREAD

**Issue by DaanDeMeyer** [clangd/vscode-clangd#18]
Documentation on the new API:

https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

**Comment by sam-mccall** [comment]
Yes! On the server side clangd supports this protocol already (unless there were any sneaky last-minute changes). Clangd will also prefer the standard protocol (and not send notifications for the theia extension protocol) if the client advertises support for both.
However this is true only for clangd at head, clangd 11 will be the first release supporting this (no time travel yet, sadly).

So this means:
1. Once there's a stable vscode-languageclient version supporting this feature, we can bump vscode-clangd's dependency to pick it up. (I don't think we should depend on the prerelease `-next` versions unless we must).
2. But it's not terribly urgent as very few people have a new enough clangd to support it. This will break compatibility with older versions of vscode, so we should give it at least a month.
3. we need to keep support for the old protocol in vscode-clangd for a while, for people with old clangd. The imminent autoinstall/autoupdate functionality in vscode-clangd (#5) means maybe we can probably drop it a month or so  after LLVM 11 releases.
4. we need to keep support for the old protocol in clangd for a while, for people with old clients (mostly not vscode, rather clients that don't autoupdate). My guess is we'll deprecate it in 11 and drop it either in 12 or 13.

I think this bug should track making the client work with latest clangd using the new API, and then we should close it as there won't be anything to do but wait for a while.

**Comment by junknet** [comment]
A month has passed

**Comment by Trass3r** [comment]
>     1. Once there's a stable vscode-languageclient version supporting this feature, we can bump vscode-clangd's dependency to pick it up.

https://github.com/microsoft/vscode-languageserver-node#3153-protocol-61x-client-and-61x-server
Then this must be the old one?

**Comment by sam-mccall** [comment]
AFAICT there's still no stable release of the client. 6.1.3 is 3 months old and has the protocol under "proposed" (meaning it won't work with standard vscode, only insiders)

**Comment by Trass3r** [comment]
Fixed.
