### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by carlos738** [clangd/vscode-clangd#183]
- Issue Type: `Bug`
- Extension Name: `vscode-clangd`
- Extension Version: `0.1.5`
- OS Version: `Windows_NT ia32 10.0.18363`
- VS Code version: `1.55.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by kadircet** [comment]
i believe you forgot to paste, please do so and re-open.
