### ISSUE TITLE
Error while including header

### ISSUE THREAD

**Issue by rahdirigs** [clangd/vscode-clangd#189]
I am using VSCode with Clangd extension for the sole reason that MS IntelliSense is too slow.
My tasks require me to use GNU GCC distribution and accordingly I have it setup through MacPorts. When I include a specific header `random`, the editor shows a red squiggle and when I hover over it it reads
`In included file: definition of builtin function '_mm_getcsr'clang(builtin_definition)
xmmintrin.h(821, 1): Error occurred here`. 

I am unable to figure out if I am missing include paths or what the issue is exactly.

<img width="871" alt="Screenshot 2021-05-11 at 6 40 02 PM" src="https://user-images.githubusercontent.com/70215074/117820580-4eaa1d80-b288-11eb-92bb-8d9dcdda7e32.png">

**Logs**
`V[18:55:19.946] <<< {"id":87,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[{"code":"builtin_definition","message":"In included file: definition of builtin function '_mm_getcsr'","range":{"end":{"character":10,"line":14},"start":{"character":9,"line":14}},"relatedInformation":[{"location":{"range":{"end":{"character":10,"line":820},"start":{"character":0,"line":820}},"uri":"file:///opt/local/lib/gcc9/gcc/x86_64-apple-darwin20/9.3.0/include/xmmintrin.h"},"message":"Error occurred here"}],"severity":1,"source":"clang"}],"only":["quickfix"]},"range":{"end":{"character":10,"line":14},"start":{"character":9,"line":14}},"textDocument":{"uri":"file:///Users/myUser/myProj/myFolder/filename.cc"}}}`

**System information**
Clangd version: v12.0.0
clangd extension version: v0.1.11
Operating system: MacOS Big Sur 11.2.3

**Settings and compile_commands.json**
`"clangd.arguments": [
    "--query-driver=/opt/local/bin/g++-mp-9",
    "-log=verbose"
  ]`

compile_commands.json
`[
    {
        "directory": "/Users/myUser/myProj",
        "command": "/opt/local/bin/g++-mp-9 -DLOCAL filename.cc",
        "file": "filename.cc"
    }
]`

I would be glad if someone could help me out.

**Comment by kadircet** [comment]
It looks like you are trying to make use of GCC's builtin libraries, which doesn't go well with clang's internals. Since these headers are meant to be tied to version of clangd.

How did you install clangd? It might be because of a misplaced builtin headers folder that comes with clangd.

**Comment by rahdirigs** [comment]
I installed llvm via homebrew

**Comment by rahdirigs** [comment]
Seems like I had to specify the target flag in my compile command. By adding <code>--target=x86_64-pc-linux-gnu</code> in the <code>command</code> attribute of the compile_commands.json, I do not see any of the error squiggles and everything runs fine now.

The new compile_commands.json looks like
<code>[ { "directory": "/Users/myUser/myProj", "command": "/opt/local/bin/g++-mp-9 --target=x86_64-pc-linux-gnu -DLOCAL filename.cc", "file": "filename.cc" } ]</code>.

Closing the issue.
