### ISSUE TITLE
After enabling this feature I am not able to use clang-format to format files

### ISSUE THREAD

**Issue by zrno** [clangd/vscode-clangd#191]
Issue Type: <b>Bug</b>

Enabling this extension stops VS Code from formatting my files when using clang-format. 
It works perfectly fine when using Intellisense. It also works fine when enabling the extension for the first time in one VS Code session. But if the extension is enabled and I restart VS code then formatting stops working. There is a quick status message at the bottom saying `extension c/c++ cannot format .....myFileName...`

The C/C++ extension doesn't output any logs in the output tab. I assume that has to do with the fact that Intellisense is disabled after clangd is enabled.

Clangd doesn't output any additional logs in the output tab when formating a file fails.

Extension version: 0.1.11
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.12.5-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 4408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.06GB (19.39GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 87fed376-385e-4b70-a6e7-f62fe0f386e3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by rjra100** [comment]
This one's not clangd's fault. Think you've got a setting in your config something like
```
    "[cpp]": {
        "editor.defaultFormatter": "ms-vscode.cpptools"
    },
```
which tells it to use cpptools (the MS C/C++ extension) for code formatting. As you surmise, for some reason cpptools doesn't do code formatting if its intellisense is disabled (I even raised a [bug](https://github.com/microsoft/vscode-cpptools/issues/7584) for it the other day!).
If you remove that setting, clangd will do the formatting using its own copy of clang-format.

**Comment by njames93** [comment]
Clangd doesn't use a binary of clang-format as it has access to the format libraries directly. Therefore it's not possible to choose which version of format you are using. Instead you get the version of clang-format that was built at the same time your clangd was built.

**Comment by zrno** [comment]
Makes sense. What is the best way to use clangd as a language server and another clang-format for formatting? Is that possible?

**Comment by HighCommander4** [comment]
> What is the best way to use clangd as a language server and another clang-format for formatting? Is that possible?

That's going to be client-dependent, but e.g. with VSCode, you can install the [xaver.clang-format](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format) extension and configure that to be your default formatter.
