### ISSUE TITLE
C++17 doesn't work

### ISSUE THREAD

**Issue by codic12** [clangd/vscode-clangd#192]
I'm not quite sure if this is an issue with vscode-clangd or clangd, but it looks to work in my neovim configuration. In vscode-clangd, if I add the argument to enable C++17, it doesn't work; am I using the wrong variable?
```
    "clangd.arguments": [
      "-std=c++17"
    ],
```

Says that the language server crashed over 5 times. I'd be happy to get logs, but for some reason on my end the Output field is empty.

**Comment by HighCommander4** [comment]
`clangd.arguments` is for specifying command-line arguments for clangd itself, not for specifying command-line arguments for the commands used to compile the project files.

See the "Project setup" section of https://clangd.llvm.org/installation.html for how to specify those kinds of flags.

**Comment by codic12** [comment]
Wow, that was a quick reply, thank you!
My issue isn't with the compilation command, which I run manually with a makefile. It's that when I use a C++17 feature like std::filesystem, vscode-clangd will highlight it with a squiggly line, even though it compiles fine on my compiler.

**Comment by HighCommander4** [comment]
Yep, I understand. Please review the mentioned section -- you need to use one of the `compile_commands.json` or `compile_flags.txt` files to communicate this flag to clangd.

**Comment by codic12** [comment]
Got it, is there a way to specify it globally?

**Comment by HighCommander4** [comment]
> Got it, is there a way to specify it globally?

If by "globally" you mean "for all files in the project", then `compile_flags.txt` should do that. (For larger projects, `compile_commands.json` is usualyy generally by a tool, based e.g. on your makefile. Then, you're only specifying it once (in your makefile) but the flag will be reflected in every file's entry in `compile_commands.json`.)

If by "globally" you mean "for all projects on your computer", then perhaps using the [Config mechanism](https://clangd.llvm.org/config.html) (have a look at the `CompileFlags:` `Add:` keys).

**Comment by codic12** [comment]
I meant the latter, I'll take a look at that. Not a vscode-clangd issue so I'll close it, thanks!
