### ISSUE TITLE
Wrong "Use nullptr" fix when using operator ">" (larger than)

### ISSUE THREAD

**Issue by zrno** [clangd/vscode-clangd#197]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/13214299/121266301-5d7b0300-c90e-11eb-8287-388861890ef4.png)
![image](https://user-images.githubusercontent.com/13214299/121266339-72f02d00-c90e-11eb-9fa6-e8abbc05f758.png)

Extension version: 0.1.11
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.12.9-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.06GB (5.30GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 87fed376-385e-4b70-a6e7-f62fe0f386e3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by HighCommander4** [comment]
That's a pretty nonsensical diagnostic!

However, a couple of screenshots is not much to go on to investigate. Could you provide a complete file or set of files that reproduces it?

**Comment by njames93** [comment]
This should have been fixed in https://github.com/llvm/llvm-project/commit/98146c1f5d0c772aec56149724119d49990f4d0c. However that commit isn't on the 12 branch so you'll have to either use a trunk version of clangd or wait for the 13 release, Likely around September this year.

**Comment by zrno** [comment]
Thx. Ok to close this ticket then as it is not a bug in the extension but in clangd.
