### ISSUE TITLE
expand macros in preview

### ISSUE THREAD

**Issue by fneddy** [clangd/vscode-clangd#203]
add the expanded version of a macro to macro preview window e.g.

```C
#define MIN(_x, _y) (((_x) < (_y)) ? (_x) : (_y))

...



/*
   currently the macro preview window just shows the macro definition.
   instead of the definition it could expand to show the definition and
   the expanded macro in preview window. in this case:


      MIN(_x, _y) (((_x) < (_y)) ? (_x) : (_y))
   ->
      (((3) < (4)) ? (3) : (4)) 
*/
z = MIN(3, 4); 

```

**Comment by HighCommander4** [comment]
Not exactly what you're asking for, but there is an "expand macro" code action for macro calls which replaces the macro call with its expansion. You can use it to look at the expansion, and then "undo" to get back the call.

**Comment by fneddy** [comment]
ahhh nice to know. :+1:

**Comment by zoumi** [comment]
https://github.com/microsoft/vscode-cpptools/issues/4183#:~:text=When%20you%20hover%20over%20FOO%20%28ss%29%20and%20click,you%20clicked%20on%20in%20place%20where%20it%20was%3A

**Comment by zoumi** [comment]
Can we have expansion information in Hover window?
[![image](https://user-images.githubusercontent.com/5162901/164364384-fdaade10-0864-4db4-aa82-2045317d4b79.png)](https://user-images.githubusercontent.com/47744191/126126408-5e6e8ada-f43c-420c-a080-353021894868.gif)

**Comment by daiyousei-qz** [comment]
@HighCommander4 Hi, would you guys accept a patch like this: 
prototype in https://github.com/llvm/llvm-project/compare/main...daiyousei-qz:expand-macro-on-hover

![image](https://user-images.githubusercontent.com/12378019/171971018-f16e16e8-a94f-49a6-b3b6-b14c88d3ca19.png)

I probably should figure out how to make a proper section in hovercard and how to apply syntax highlight in the expansion

**Comment by daiyousei-qz** [comment]
This doesn't work very well with multi-line macro though

**Comment by HighCommander4** [comment]
Thanks, I think this is a useful addition to the hover and I would encourage you to upload the patch to Phabricator for further review.

My sense is that a "minimum viable" patch would need:

 * Some test cases that exercise the new feature (see `HoverTests.cpp`)
 * Reasonable behaviour for a variety of types of macros that are used in the wild. By that I mean, it shouldn't crash and it shouldn't produce an unreadable hover card; _not_ producing a macro expansion in some cases is fine (we can expand on those cases in the future).

**Comment by HighCommander4** [comment]
Linking to @daiyousei-qz's patch implementing this: https://reviews.llvm.org/D127082

**Comment by HighCommander4** [comment]
> Linking to @daiyousei-qz's patch implementing this: https://reviews.llvm.org/D127082

This was actually merged a while ago and will be released with clangd 16. I think the issue can be closed.

**Comment by catskul** [comment]
Not sure whether to open a new ticket:

AFAICT, the MACRO preview shows a single level of macro. Is there a way to show more than one level of macro expansion given the current implementation?

**Comment by HighCommander4** [comment]
> AFAICT, the MACRO preview shows a single level of macro. Is there a way to show more than one level of macro expansion given the current implementation?

The feature which @daiyousei-qz added in this issue is the "Expands to" section of the hover window.

Here is an example of that with two levels of macro expansion:

![expands-to](https://github.com/user-attachments/assets/e8cd771b-f8bf-4d2a-b103-75d593180686)

Note that the value shown under "expands to" is `42`, which is the result of both levels of expansion (`ANSWER` --> `REAL_ANSWER`, and `REAL_ANSWER` --> 42).

If you're looking for something different, can you elaborate?
