### ISSUE TITLE
Was anyone able to get vscode-clangd to work on Centos 7?

### ISSUE THREAD

**Issue by smeznaric** [clangd/vscode-clangd#206]
Due to an older version of glibc 2.17 it seems that I can't get vscode-clangd to run on Centos 7. I don't have administrative rights to the machine. Is there any workaround for this? Would very much like to try this extension for the quality IntelliSense.

**Comment by sam-mccall** [comment]
The VSCode extension should work as normal, but it needs a copy of clangd.
The github.com/clangd/clangd/releases binaries indeed don't support systems before glibc 2.17, if there isn't a package available from your distribution vendor you may need to build it from source.
Looks like someone's had luck with that approach: https://jdhao.github.io/2021/07/03/install_clangd_on_linux/

I need to close this as there's no bug here and we can't really provide installation support.
