### ISSUE TITLE
Doxygen preview

### ISSUE THREAD

**Issue by shilch** [clangd/vscode-clangd#213]
The Microsoft C++ extension in vscode provides a nice preview of Doxygen-documented symbols when hovering above them.  
With the vscode-clangd extension, the symbol's documentation is shown as unformatted text. That is, special Doxygen instructions like `@brief` are written out as such.
Since Doxygen is widely used, it would probably be helpful to get formatted documentation with this extension as well.

**Comment by HighCommander4** [comment]
Duplicate of https://github.com/clangd/clangd/issues/529?

**Comment by shilch** [comment]
@HighCommander4 Indeed. I'll close this issue here in favour of the one you linked. Thanks!
