### ISSUE TITLE
Add an option to disable inlay hints

### ISSUE THREAD

**Issue by SpaceIm** [clangd/vscode-clangd#215]
Is there a way in `settings.json` to disable inlay hints added in https://github.com/clangd/vscode-clangd/pull/168?

Turning off `editor.inlayHints.enabled` doesn't work for clangd, and I don't see any specific property.

**Comment by HighCommander4** [comment]
The feature is currently opt-in on the server side: it requires `--inlay-hints=true` in `clangd.arguments` to be enabled.

**Comment by SpaceIm** [comment]
OK thanks, I've updated my version of clangd (I was using an old beta version which surprisingly returned `clangd version 13.0.0 (https://github.com/llvm/llvm-project 5144f730a8a8a4c7c7984ff945187a9aa83c91ac)` with `clangd --version`).
