### ISSUE TITLE
clangd doesn't know a included file

### ISSUE THREAD

**Issue by playgithub** [clangd/vscode-clangd#216]
## Env
OS: Linux
Compiler: c++
Project: cmake
clangd: 0.1.11

## Problem
The cmake project is built succefully, and there is `compile_commands.json` in `${CMAKE_BINARY_DIR}`, but intellisense for a included file fails, screenshot below
![image](https://user-images.githubusercontent.com/3665590/129432477-6247652c-dde1-43c5-a769-4a3b7b841e4f.png)

**Comment by HighCommander4** [comment]
Please attach [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs) from a session where you open the affected file and observe this diagnostic.

**Comment by playgithub** [comment]
solved

https://clangd.llvm.org/installation
```
CMake-based projects

If your project builds with CMake, it can generate this file. You should enable it with:

cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1
compile_commands.json will be written to your build directory. You should symlink it (or simply copy it) to the root of your source tree, if they are different.

ln -s ~/myproject/compile_commands.json ~/myproject-build/
```
