### ISSUE TITLE
Instead of put a `compile_commands.json` at source root

### ISSUE THREAD

**Issue by playgithub** [clangd/vscode-clangd#218]
For cmake projects, `compile_commands.json` has to be copied/linked to the source root directory now.
Instead of this, can a property of vscode workspace be set, so that `vscode-clangd` knows where is `compile_commands.json`?

**Comment by HighCommander4** [comment]
Yes, this can be done today by adding the following to `<project>/.vscode/settings.json`:

```
{
  "clangd.arguments": [
    "--compile-commands-dir=<path_to_directory_containing_compile_commands.json>"
  ]
}
```

Another way is to use clangd's own config file (see the `CompilationDatabase` key in the [docs](https://clangd.llvm.org/config.html)).

**Comment by playgithub** [comment]
> Yes, this can be done today by adding the following to `<project>/.vscode/settings.json`:
> 
> ```
> {
>   "clangd.arguments": [
>     "--compile-commands-dir=<path_to_directory_containing_compile_commands.json>"
>   ]
> }
> ```

That's it, thanks.

> Another way is to use clangd's own config file (see the `CompilationDatabase` key in the [docs](https://clangd.llvm.org/config.html)).

It doesn't seem workspace specific, does it?

**Comment by HighCommander4** [comment]
> > Another way is to use clangd's own config file (see the `CompilationDatabase` key in the [docs](https://clangd.llvm.org/config.html)).
> 
> It doesn't seem workspace specific, does it?

It can be. From the docs:

> * **project configuration**: a file named `.clangd` in the source tree. (clangd searches in all parent directories of the active file).

**Comment by i-ky** [comment]
@playgithub, if you use [CMake Tools extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools), then there is a [`cmake.copyCompileCommands` setting](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md) that tells CMake Tools to copy compilation database from build directory to a desired location (e.g. `${workspaceFolder}`). This will work even if you have different build directories depending on build configuration and whatnot. `--compile-commands-dir` and `CompilationDatabase` will only allow one possible location.

**Comment by playgithub** [comment]
> @playgithub, if you use [CMake Tools extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools), then there is a [`cmake.copyCompileCommands` setting](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md) that tells CMake Tools to copy compilation database from build directory to a desired location (e.g. `${workspaceFolder}`). This will work even if you have different build directories depending on build configuration and whatnot. `--compile-commands-dir` and `CompilationDatabase` will only allow one possible location.

Anyway it's an assistant file, I prefer to make it transparent.
