### ISSUE TITLE
How not to underline include files?

### ISSUE THREAD

**Issue by playgithub** [clangd/vscode-clangd#219]
## Screenshot
![Screenshot_20210814_130758](https://user-images.githubusercontent.com/3665590/129434808-24200126-9ccb-47a6-87df-76b76e1a7a97.png)

## Description
When `vscode-clangd` disabled, no underlines for the included files.
When `vscode-clangd` enabled, how not to show the underlines?

**Comment by HighCommander4** [comment]
There is some discussion of this at https://github.com/clangd/clangd/issues/630.

There is no current option to disable the include underlines specifically, but there is mention of the `editor.links` option which will also disable underlines of URLs in comments, and a proposed patch (which hasn't been merged) to add an option specific to includes.

**Comment by playgithub** [comment]
> editor.links

It's fine, thanks very much.

**Comment by playgithub** [comment]
It works with `.vscode/settings.json` as below
```json
{
    "clangd.arguments": [
        "--compile-commands-dir=${workspaceFolder}/out"
    ],
    "editor.links": false,
    ...
}
```
What confuse me is that `editor.links` here is not like an option of `vscode-clangd` but a global option for the workspace.

**Comment by i-ky** [comment]
> What confuse me is that `editor.links` here is not like an option of `vscode-clangd` but a global option for the workspace.

Yes, it is an option for the whole workspace, but you can [limit it to specific language(s)](https://code.visualstudio.com/docs/getstarted/settings#_languagespecific-editor-settings):
```json
"[cpp]": {
    "editor.links": false
}
```
