### ISSUE TITLE
formatOnSaveMode appears broken

### ISSUE THREAD

**Issue by dwilliamson** [clangd/vscode-clangd#225]
Issue Type: <b>Bug</b>

I have the following settings:

```json
    "editor.formatOnSave": true,
    "editor.formatOnSaveMode": "modifications",
    "editor.defaultFormatter": "ms-vscode.cpptools",
```

`modifications` is set so that if there's no background source control, no formatting is performed. However, as of VSCode 1.60.0 (I didn't update vscode-clangd version) this option is formatting the entire file, which is what `modificationsIfAvailable` is supposed to do.

After updating to the latest vscode-clangd this behaviour is still apparent.

`modifications` still limits its formatting to edited sections of code when source control is enabled, so that bit is working fine.

Extension version: 0.1.13
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.91GB (15.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by HighCommander4** [comment]
If `editor.defaultFormatter` is set to `ms-vcode.cpptools`, then it's the Microsoft plugin doing the formatting and not clangd, right?

**Comment by dwilliamson** [comment]
Apologies, I also have this:

```json
    "[cpp]": {
        "editor.defaultFormatter": "llvm-vs-code-extensions.vscode-clangd"
    },
```

**Comment by HighCommander4** [comment]
I played around with this a bit, and what I'm seeing is that, with `"editor.formatOnSaveMode": "modifications"` specified:

 * in a project with version control, clangd receives a `textDocument/rangeFormatting` request (which specifies a range of the file to format) on file-save
 * in a project without version control, clangd receives a `textDocument/formatting` request (which means format the entire file)

So, I agree there's a bug, but the bug seems to be on the client (vscode) side.

**Comment by sam-mccall** [comment]
Just a thought: that sounds suspiciously like the editor is trying to implement format-on-save vs the VCS baseline, rather than vs the previous on-disk state.

Personally I find that to be the best workflow but a) others may disagree and b) VSCode may not be implementing it correctly by the sound of things.

**Comment by HighCommander4** [comment]
> Just a thought: that sounds suspiciously like the editor is trying to implement format-on-save vs the VCS baseline, rather than vs the previous on-disk state.

The vscode setting description is as follows:

```
 // Controls if format on save formats the whole file or only modifications. Only applies when `editor.formatOnSave` is enabled.
 //  - file: Format the whole file.
 //  - modifications: Format modifications (requires source control).
 //  - modificationsIfAvailable: Will attempt to format modifications only (requires source control). If source control can't be used, then the whole file will be formatted.
 "editor.formatOnSaveMode": "file",
```

It's pretty explicit that it's using source control; not sure what's suspicious about it :)

**Comment by HighCommander4** [comment]
[Here's the relevant code](https://github.com/microsoft/vscode/blob/a2a7dc9b53315f5a91713932dc91d11d1948ffc4/src/vs/workbench/contrib/codeEditor/browser/saveParticipants.ts#L257-L270) from the vscode source.

It looks like... it's treating `modifications` and `modificationsIfAvailable` exactly the same, with the behaviour matching the description for `modificationsIfAvailable`.

Basically, it looks like the [change](https://github.com/microsoft/vscode/pull/127849) that introduced `modificationsIfAvailable` regressed the behaviour of `modifications`.

**Comment by HighCommander4** [comment]
Filed upstream as https://github.com/microsoft/vscode/issues/132697.

**Comment by dwilliamson** [comment]
Thank you for the detective work!

**Comment by HighCommander4** [comment]
@dwilliamson looks like a fix for the upstream issue has landed in VS Code Insiders.

Please feel free to give it a try and [let them know](https://github.com/microsoft/vscode/issues/132697#issuecomment-930561777) if the issue is resolved.
