### ISSUE TITLE
File status disappears when changing focus to an output window

### ISSUE THREAD

**Issue by DavidGoldman** [clangd/vscode-clangd#23]
See this [VSCode issue](https://github.com/microsoft/vscode/issues/58869) for more details, the tl;dr is that output windows can show up in `vscode.window.activeTextEditor`.

As a workaround, you can store the previously open active text editor/document and then ignore changes when an `vscode.window.activeTextEditor.document.uri.scheme == 'output'` and then check `vscode.window. visibleTextEditors` to make sure it hasn't disappeared.

**Comment by hokein** [comment]
> the tl;dr is that output windows can show up in vscode.window.activeTextEditor.

yeah, I noticed that but didn't think it is worth fixing it as the output is mostly used for debugging clangd, and most clangd users would not use it (probably?).

> As a workaround, you can store the previously open active text editor/document and then ignore changes when an vscode.window.activeTextEditor.document.uri.scheme == 'output' and then check vscode.window. visibleTextEditors to make sure it hasn't disappeared.

this sounds plausible. it seems that the status item doesn't disappear when the focus is on `problems`, `debug console` and `terminal` panels (no matter whether the text document is visible or invisible), so a trivial fix would be to just ignore the `onDidChangeActiveTextEditor` event when the `vscode.window.activeTextEditor.document.uri.scheme == 'output'`, this should make the focus on `output` aligned with other panels.
