### ISSUE TITLE
C++ SDL.h file not found

### ISSUE THREAD

**Issue by jasrangi** [clangd/vscode-clangd#230]
Greetings,

I am using the Clangd extension on VS Code. 
VS Code reports the following error on my #include <SDL2/SDL.h>. 
```
'SDL2/SDL.h' file not found clang(pp_file_not_found)
```
Running make results in no errors. Here is my Makefile:
```make
CXXFLAGS = -Wall -Werror -std=c++11
SDL2FLAGS = -lSDL2
execs = chip8emu

all: chip8emu

chip8emu: chip8.cc chip8emu.cc
	$(CXX) $(CXXFLAGS) $(SDL2FLAGS) -o $@ $^

clean:
	rm -f $(execs)
```

I used bear, as per instructions on the clangd getting started [page](https://clangd.llvm.org/installation.html#project-setup).
```sh
make clean; bear -- make
```

This results in the following compile_commands.json.
```json
[
  {
    "arguments": [
      "/usr/bin/c++",
      "-c",
      "-Wall",
      "-Werror",
      "-std=c++11",
      "-o",
      "chip8emu",
      "chip8.cc"
    ],
    "directory": "/Users/jasjeet/chip8",
    "file": "/Users/jasjeet/chip8/chip8.cc",
    "output": "/Users/jasjeet/chip8/chip8emu"
  },
  {
    "arguments": [
      "/usr/bin/c++",
      "-c",
      "-Wall",
      "-Werror",
      "-std=c++11",
      "-o",
      "chip8emu",
      "chip8emu.cc"
    ],
    "directory": "/Users/jasjeet/chip8",
    "file": "/Users/jasjeet/chip8/chip8emu.cc",
    "output": "/Users/jasjeet/chip8/chip8emu"
  }
]
```
However, after restarting VS Code the error is still present.
I have also tried adding "-I SDL2" to "arguments".

**System information**
Clangd extension version v0.1.11
Operating system: MacOS 11.5.2
SDL2 and bear were installed using [Homebrew](https://brew.sh/).

Thanks in advance.

**Comment by HighCommander4** [comment]
Where is the target of the `#include <SDL2/SDL.h>` in the filesystem?

What compiler are you using?

**Comment by jasrangi** [comment]
The target is located at "/usr/local/include/SDL2/SDL.h". If it's relevant, there is also a .dylib file located at "/usr/local/Cellar/sdl2/2.0.16/lib/libSDL2.dylib". 
The compiler is clang++, which I believe is the default on Mac.

**Comment by HighCommander4** [comment]
I'm guessing the compiler has `/usr/local/include` in its default search path (but for some reason clangd does not?)

You can verify this by running `echo | clang++ -E -v -`: does the output include `/usr/local/include`?

(As a workaround, adding `-I /usr/local/include/` to your `CXXFLAGS` and re-generating the `compile_commands.json` should fix the issue.)

**Comment by jasrangi** [comment]
```echo | clang++ -E -v - | grep "/usr/local/include"``` verified that the output includes that path:
```
#include <...> search starts here:
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
```
Adding ```-I /usr/local/include/``` to ```CXXFLAGS``` in the Makefile, re-generating ```compile_commands.json``` by running ```make clean; bear -- make```, and reloading the file in VS Code has cleared the errors. Thank you!

**Comment by HighCommander4** [comment]
It's a bit of a mystery to me why clangd's builtin include search path does not also include `/usr/local/include`.

Out of curiosity, where is the `clangd` binary located? If it's in a different place than the `clang++` binary, is there perhaps a _different_ `clang` or `clang++` binary in the same place as `clangd`?

**Comment by jasrangi** [comment]
I checked the clangd extension settings in VS Code and it says that the path to the clangd executable is ```/Users/jasjeet/Library/Application\ Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/12.0.1/clangd_12.0.1/bin/clangd```. I looked in that directory and there is no ```clang``` or ```clang++``` binary. The only item in ```bin``` is the ```clangd``` binary.

**Comment by HighCommander4** [comment]
Ok, i see. So, maybe because it's installed in a different location, clangd doesn't "know about" all the compiler's built-in include paths.

Another way of solving this which doesn't require changes to the makefile is to run clangd with the command-line argument `--query-driver=/usr/bin/c++`. This tells clangd to query built-in include paths from `/usr/bin/c++` (note, this is the path to the compiler that appears in the the `compile_commands.json`; it's important that the two match). (This approach is mentioned [here](https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc).)
