### ISSUE TITLE
inlay hints for parameter names

### ISSUE THREAD

**Issue by yahya-mohammed07** [clangd/vscode-clangd#237]
I wish there was `inlay hints for parameter names` feature just like in ReSharper for c++ built-in with clangd

**Comment by yahya-mohammed07** [comment]
> We currently have support for that. You can turn this on by passing `--inlay-hints` flag to clangd.

can I change the color of the hints? + hints get duplicated when I call functions inside the test case inside the macro`REQUIRE` (on Catch2)

**Comment by HighCommander4** [comment]
The colors can be changed by adding the following to vscode's settings.json:

```
  "workbench.colorCustomizations": {
    "clangd.inlayHints.foreground": "#343434",
    "clangd.inlayHints.background": "#E4E4E4",
  }
```

The issue of duplicate hints has been fixed in https://reviews.llvm.org/D110051. The fix will appear in clangd 14.
