### ISSUE TITLE
support add custom "defines" in a project

### ISSUE THREAD

**Issue by gglin001** [clangd/vscode-clangd#250]
just like "defines"  or "C_Cpp.default.defines" in `vsocde-cpptools`

ref
https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference

**Comment by HighCommander4** [comment]
This can be done using clangd's [config file](https://clangd.llvm.org/config.html#compileflags), something like:

```
CompileFlags:
  Add: [-DMY_MACRO]
```
