### ISSUE TITLE
File is parsed correctly or not depending on the existence of another file in the compilation database

### ISSUE THREAD

**Issue by reddwarf69** [clangd/vscode-clangd#252]
In the attached CMake project the file `src/b/lib/b/impl/b/impl/b.hpp` is not parsed correctly. It says `b/b.hpp` in `#include <b/b.hpp>`  can't be found. That's with this compilation database:

```
[
{
  "directory": "/home/reddwarf/test_build/src/a/src",
  "command": "/usr/bin/c++    -o CMakeFiles/a.dir/a/impl/a.cpp.o -c /home/reddwarf/test/src/a/src/a/impl/a.cpp",
  "file": "/home/reddwarf/test/src/a/src/a/impl/a.cpp"
},
{
  "directory": "/home/reddwarf/test_build/src/b/src",
  "command": "/usr/bin/c++ -DFMT_LOCALE -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/home/reddwarf/test/src/b/lib/b/impl -I/home/reddwarf/test/src/b/lib/b/include -isystem /home/reddwarf/git/router_sdk_build/full/dependencies/src/spdlog/external-spdlog-prefix/opt/samknows/router_sdk/include -isystem /home/reddwarf/git/router_sdk_build/full/dependencies/src/fmt/external-fmt-prefix/opt/samknows/router_sdk/include  -o CMakeFiles/main.dir/main.cpp.o -c /home/reddwarf/test/src/b/src/main.cpp",
  "file": "/home/reddwarf/test/src/b/src/main.cpp"
}
]
```

If configured with `-DDISABLE_A=ON`, making the compilation database contain only
```
[
{
  "directory": "/home/reddwarf/test_build/src/b/src",
  "command": "/usr/bin/c++ -DFMT_LOCALE -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/home/reddwarf/test/src/b/lib/b/impl -I/home/reddwarf/test/src/b/lib/b/include -isystem /home/reddwarf/git/router_sdk_build/full/dependencies/src/spdlog/external-spdlog-prefix/opt/samknows/router_sdk/include -isystem /home/reddwarf/git/router_sdk_build/full/dependencies/src/fmt/external-fmt-prefix/opt/samknows/router_sdk/include  -o CMakeFiles/main.dir/main.cpp.o -c /home/reddwarf/test/src/b/src/main.cpp",
  "file": "/home/reddwarf/test/src/b/src/main.cpp"
}
]
```
the file is parsed correctly!

I found the problem in a bigger project in which I found the problem was triggered by any file in the compilation database with `impl/` as part of the `"file"` field. No other file triggered the issue.

[test.tar.gz](https://github.com/clangd/vscode-clangd/files/7558736/test.tar.gz)

**Logs**

[clangd.log](https://github.com/clangd/vscode-clangd/files/7558739/clangd.log)

**System information**
Clangd version (from the log, or `clangd --version`): 13
clangd extension version: 0.1.13
Operating system: Linux / Fedora 35

**Comment by HighCommander4** [comment]
It sounds like you are running into a situation where clangd's heuristics for choosing a source file whose compilation commands to use to parse a header file, is giving a suboptimal result.

Please see [this FAQ item](https://clangd.llvm.org/faq#what-can-i-do-if-clangd-chooses-the-wrong-source-file-to-infer-commands-for-a-header) for a workaround. Otherwise, improving the heuristics is tracked in #123.

**Comment by reddwarf69** [comment]
Yes, indeed. The log for the case that works says
`I[00:14:10.253] ASTWorker building file /home/reddwarf/test/src/b/lib/b/impl/b/impl/b.hpp version 1 with command inferred from /home/reddwarf/test/src/b/src/main.cpp`
