### ISSUE TITLE
Clangd can't find "math.h" only in one directory, while doing it without any problems in others

### ISSUE THREAD

**Issue by Artur-Romaniuk** [clangd/vscode-clangd#255]
Clangd can't find "math.h" only in one directory that is an interface lib. Our build system uses CMake and exports compile commands. Other system headers are included without any problems and math.h is properly recognized in all other dirs except this one (I am slowly going crazy because of this...).

The problem is that for some reason that library when compiled by clangd does't add these argument to the command (took this from clangd output):
-isystem /usr/lib/gcc/arm-none-eabi/11.2.0/../../../../arm-none-eabi/include/c++/11.2.0 -isystem /usr/lib/gcc/arm-none-eabi/11.2.0/../../../../arm-none-eabi/include/c++/11.2.0/arm-none-eabi -isystem /usr/lib/gcc/arm-none-eabi/11.2.0/../../../../arm-none-eabi/include/c++/11.2.0/backward -isystem /usr/lib/gcc/arm-none-eabi/11.2.0/include -isystem /usr/lib/gcc/arm-none-eabi/11.2.0/include-fixed -isystem /usr/lib/gcc/arm-none-eabi/11.2.0/../../../../arm-none-eabi/include

Other static libraries that are built using identical CMake files have those arguments properly passed.
CMake files themselves don't include any system files and arm-gcc compiles everything without any problems. 

If there is any other information that would help, I will gladly provide it.

settings.json:
    "clangd.arguments": [
        "--compile-commands-dir=build",
        "--all-scopes-completion",
        "--background-index",
        "--clang-tidy",
        "--completion-style=detailed",
        "--query-driver=/usr/bin/arm-none-eabi-g++"
    ]

Clangd version (from the log, or `clangd --version`): 12.0.1
clangd extension version: 0.1.13
Operating system: Manjaro Linux

**Comment by sam-mccall** [comment]
Info that would help is:
- what is the full path of the math.h file that exists in your system that you expect to be found
- what is the compile command for a working & non-working file (from clangd logs)
- what are the compile_commands.json entries from the working & non-working files?

**Comment by Artur-Romaniuk** [comment]
- This is math.h path that is properly added to other libs /usr/lib/gcc/arm-none-eabi/11.2.0/../../../../arm-none-eabi/include  
- There is no compile commands for this lib because it is header only Interface Lib
- Other compile commands are just regular compile commands, nothing special. Example:
"/usr/bin/arm-none-eabi-g++ -fdata-sections -ffunction-sections --specs=nano.specs -Wl,--gc-sections -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard  -I/***/Example_app -isystem /***/Libs/ETL/include -g -Wall -Wextra -Wpedantic -Wno-unused-parameter -fno-rtti -fno-exceptions -fno-threadsafe-statics -Wno-volatile -Wsuggest-override -Wold-style-cast -Og -g3 -ggdb -std=c++20 -o CMakeFiles/Example_app.dir/example_app.cpp.obj -c /***/Example_app/example_app.cpp"

**Comment by sam-mccall** [comment]
I'm asking about the path of the actual header file - I guess `/usr/arm-none-eabi/include/math.h`?

Please include the full compile command from the log and the paths of the relevant files (the file that works, the file that doesn't work, compile_commands.json etc). Ideally the full log.

If you have no compile_commands.json entry for the file, it will be using the entry from some other file. The log will say something like "building <file> with command <blah blah> inferred from <other file>".

My best guess at this point is that you're not getting a command inferred from a file that uses arm-none-eabi-g++ as it's compiler. Either because it's being matched against a file that compiles differently (e.g. a c file), or because you don't have a compile_commands.json that covers this file at all. Therefore your driver wouldn't be queried and your system includes wouldn't be set up right.

In any case, an available workaround is to add a .clangd file that injects the relevant -isystem flags. See https://clangd.llvm.org/config#compileflags for how to do this.

**Comment by Artur-Romaniuk** [comment]
Yes, this is the correct path to the header file.

You are right, because this is a header only library it doesn't have a compile command.
Other interface library that properly includes everything compiles like this:

I[20:50:28.968] ASTWorker building file /***/working_header_only.h version 65 with command inferred from /**/Example/examplet.cpp
Then there is a compile command json that has all includes and -isystem to the arm-none-eabi that I pasted in original post.

However this interface library that doesn't want to find math.h builds like this:
I[20:49:22.747] ASTWorker building file /***/etl/profiles/determine_compiler_language_support.h version 104 with command inferred from /***/startup.s
[/***/build]

As you can see, clangd chooses a .s ASM file, which probably is a reason why it doesn't probe arm-none-eabi-g++.

Is there any way to force it to use other compile command, that is not ASM?

I don't like this workaround with compile flag to library, because different devs might have different install locations and I would like to avoid complicating things unnecessarily for them. 

On the side note, why argument "--query-driver=" requires full path to the compiler? I would like to have it like this:
"--query-driver=arm-none-eabi-g++" instead of "--query-driver=/usr/bin/arm-none-eabi-g++". Why can't it work like this, even though arm-none-eabi is added to the path?

**Comment by sam-mccall** [comment]
I'm afraid I will close this, as there isn't enough info to understand the situation or possible improvements. If the project is private, that's ok but you'll need to be a bit more forthcoming if you want behavior changes.

> As you can see, clangd chooses a .s ASM file

Yes. The matching is based on the paths to the files. This is why I asked twice about file paths.

The best way to avoid having ASM commands used as fallback is not to include them in compile_commands.json. It should contain clang/gcc invocations only.

 There are heuristics that could possibly be tweaked to effectively filter them out, but we won't do this based on guesses of what might be in the compile_commands.json.

The reason query-driver takes a glob of a full path is that it's an allowlist for security. You can specify **/arm-none-eabi-g++ if you like, but it will make it unsafe to open code from untrusted sources.

**Comment by HighCommander4** [comment]
> Is there any way to force it to use other compile command, that is not ASM?

One way to do this is to use a tool to post-process the CDB to add entries for header files; see [this FAQ question](https://clangd.llvm.org/faq#what-can-i-do-if-clangd-chooses-the-wrong-source-file-to-infer-commands-for-a-header).
