### ISSUE TITLE
Long enum values not fully displayed

### ISSUE THREAD

**Issue by rg3igalia** [clangd/vscode-clangd#257]
First off, thanks for creating this amazing extension. Reporting this as a usability bug, but maybe it's a feature request. :shrug: 

I normally work on code using the Vulkan API, which has an interesting enum called VkStructureType used very frequently in many places. VkStructureType enum values are long and represent the type of an structure, so they are usually named as a variation of the VK_STRUCTURE_TYPE_ prefix followed by an uppercase and underscore-separated variation of the structure name itself. When I want clangd to help me type one of those values, I frequently find out there are several related ones sharing a common long prefix and clangd will not allow me to see the full name of each value anywhere, so I can't properly choose the right enum value. See the following screenshot:

![Screenshot from 2021-11-23 16-25-42](https://user-images.githubusercontent.com/47594367/143055610-88629494-789c-4e5a-b22f-f6472812f06f.png)

My suggestion would be to use the second box in the pop up to display not just the enum value type, but also the full enum value, using character-level wrapping if needed. Anything that lets me tell those enum values apart would be great.

**System information**
Clangd version (from the log, or `clangd --version`): clangd version 12.0.1 (Fedora 12.0.1-1.fc34)
clangd extension version: 0.1.13
Operating system: Fedora Linux

**Comment by HighCommander4** [comment]
You can widen the first box by dragging it right edge, and the new width will be remembered on subsequent invocations.

**Comment by rg3igalia** [comment]
Oh, cool! Never realized I could do that. :sweat_smile: Thanks a lot, that solves the problem. :+1:
