### ISSUE TITLE
Clangd language server is not installed

### ISSUE THREAD

**Issue by Yanpas** [clangd/vscode-clangd#267]
Extension version 0.1.13
I use vscode remote. Remote machine is rhel7 and doesn't have internet access. 
Despite clangd is in PATH and I explicitly specified it in clangd.path setting - it's still not found. Also there is an error in dev tools:
Auto-install failed: FetchError:.... ENOTFOUND api.github.com
at node-fetch/lib/index.js:1461:11

**Comment by HighCommander4** [comment]
Taking a quick look at the relevant code, that error is [produced](https://github.com/clangd/node-clangd/blob/4d086dfb177dedc93359097fc567e7bf6957e237/src/index.ts#L139) by a codepath which is only [called](https://github.com/clangd/node-clangd/blob/4d086dfb177dedc93359097fc567e7bf6957e237/src/index.ts#L71) if `which <clangdpath>` fails, where `<clangdpath>` is the value of the `clangd.path` setting.

You could try that `which` command on the command-line of your remote machine, and confirm that it produces a result?

**Comment by Yanpas** [comment]
`/usr/bin/which` on hosts works fine and shows clangd. I don't know whats the reason behind calling which if I directly specified full path to clangd. (I've also tried removing clangd.path setting, setting it to bin folder where clangd exists - all to no avail)

Took a look at the code and `node-which` uses heuristics instead of invoking which command.

**Comment by sam-mccall** [comment]
What is the value of clangd.path, and where is it set (remote config or general user config?)
And what is the path to clangd on the remote machine?

**Comment by Yanpas** [comment]
There is even a 3 years old issue:
https://github.com/isaacs/isexe/issues/18

**Comment by HighCommander4** [comment]
Perhaps, instead of using `which` unconditionally, we could check if the path is absolute, and if so just do an `exists()` check?

**Comment by sam-mccall** [comment]
That isexe bug is ugly :-(

The `which` usage, imperfect as it is, is pretty important for giving good error messages/suggestions in the very common case where clangd isn't installed at all. And I don't really want to go down the rabbithole of trying to build our own better version if there's no maintained equivalent.

> Perhaps, instead of using which unconditionally, we could check if the path is absolute, and if so just do an exists() check?

Definitely. It'd make the bug a little less frustrating. (The wrong permission logic is really unrelated to absolute/relative though.)

Another workaround available immediately is of course to wrap clangd in a shell script owned by the user :-\

**Comment by Yanpas** [comment]
Take a look at my PR please

**Comment by itacud95** [comment]
I am also experiencing this issue

**Comment by rajhlinux** [comment]
I also have this issue.

"The clangd language server is not installed." stated by VS code on FreeBSD 13.1

How to solve the issue?

Thanks.

**Comment by darkoverlordofdata** [comment]
This used to work on FreeBSD 12.x but 12 is now past EOL. Since upgrading to 13.x, the language server no longer installs. Interestingly enough, looking at https://github.com/clangd/clangd/releases, I don't see any FreeBSD releases. so I'm not sure how this ever worked.

**Comment by HighCommander4** [comment]
> This used to work on FreeBSD 12.x but 12 is now past EOL. Since upgrading to 13.x, the language server no longer installs. Interestingly enough, looking at https://github.com/clangd/clangd/releases, I don't see any FreeBSD releases. so I'm not sure how this ever worked.

I'm not sure how auto-install ever worked on FreeBSD either (note the original reporter of this issue was using RHEL), but you can find FreeBSD clangd binaries in the LLVM release packages, e.g. https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.4.

**Comment by wangjunbo4** [comment]
I also have this issue.
I'm working on CentOS Linux release 7.8.2003, vscode 1.86.2, and clangd v0.1.26

**Comment by HighCommander4** [comment]
> I also have this issue. I'm working on CentOS Linux release 7.8.2003, vscode 1.86.2, and clangd v0.1.26

Please file a separate ticket.

**Comment by Lenart12** [comment]
Also for others coming across this in the future: my issue was that I had this extension installed locally and on remote ssh, and on remote it would work. I figured out that clangd.path was set in my local settings.json and was a different one than what remote clangd expected. To fix: Open `> Preferences: Open Remote Settings (JSON) (SSH: hostname)` and set `clangd.path` there.
