### ISSUE TITLE
Syntax coloring doesn't work well with light themes.

### ISSUE THREAD

**Issue by jdumas** [clangd/vscode-clangd#27]
Hi there,

I'm on macOS with VSCode 1.45.0 and vscode-clang 0.1.4 (I have disabled the cpptools extension). It seems that vscode-clang changes the syntax highlighting, and it doesn't work well with light theme. Here are some screenshots:

- Light+ Theme with vscode-clangd **disabled**
![Screen Shot 2020-05-12 at 5 25 20 PM](https://user-images.githubusercontent.com/578702/81758248-0f2ed280-9476-11ea-89b8-06ada3e89b92.png)

- Light+ Theme with vscode-clangd **enabled**
![Screen Shot 2020-05-12 at 5 24 43 PM](https://user-images.githubusercontent.com/578702/81758313-41403480-9476-11ea-9cf0-b6eff5b4b895.png)

- Dark+ Theme with vscode-clangd **enabled**
![Screen Shot 2020-05-12 at 5 24 53 PM](https://user-images.githubusercontent.com/578702/81758334-54eb9b00-9476-11ea-922d-5e66b22eab1c.png)

As you can see, with vscode-clangd enabled, it's very hard to read code under the light theme...

**Comment by moether** [comment]
Same for me. Semantic highlighting is broken since 0.1.4. 
Workaround: going back to 0.1.3

**Comment by hokein** [comment]
should be fixed in v0.1.5, please try to update the extension.

**Comment by jdumas** [comment]
Awesome, thanks for the quick fix!
