### ISSUE TITLE
clangd server not installed

### ISSUE THREAD

**Issue by stark-zhang** [clangd/vscode-clangd#274]
I try to install clangd-13.0.0, used pre-build binaries on Github, on remote developing machine, and I connected the server by vs-code with plugin remote-ssh.

+ operating system of remote machine: CentOS 7.9, no external Internet and version of glibc less than 2.18
+ clangd: 13.0.0
+ native operating system: windows 10 enterprise 20H2
+ vscode: 1.63.0
+ vscode-clangd: the latest.

I wrote a shell script named `clangd` to wrap clangd server, its content is following:

```shell
#!/bin/bash
# clangd wrapper for user-defined glibc

clangd_dir="/var/work/$USER/clangd"
LD_LIBRARY_PATH="$clangd_dir/lib/glibc/"
$clangd_dir/lib/glibc/ld-2.18.so $clangd_dir/bin/clangd-13.0.0/clangd $@
```

And it works properly after I added it into `$PATH`:

```shell
[p8zhang@updev-hz-5-l1sw ~]$ clangd --version 
clangd version 13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
``` 

But vscode cannot find it and said: 
![image](https://user-images.githubusercontent.com/17326718/148640742-1359e05f-c6f4-42af-a9bd-5329d8769b24.png)

How to make vscode-clangd work properly?

**Comment by sam-mccall** [comment]
There are a few interesting wrinkles in this setup:
 - remote
 - different OSes
 - shell scripts

Can you try setting an absolute `clangd.path` (i.e. your script) in the remote vscode config?

**Comment by sam-mccall** [comment]
If I were to make a wild guess: you've added the `clangd` script to your PATH in a way that affects the SSH sessions you're testing with but doesn't affect the vscode remote server. E.g. setting it in bashrc but not sourcing that from profile.

Or there's some discrepancy between how $PATH is interpreted by npm-which vs your shell (we've seen that in some edge cases before). 

In either of those cases, passing an absolute path to the script is an easy workaround.

**Comment by stark-zhang** [comment]
I have a try, added the absolute path of the script to configuration `clangd.path` of remote vscode. And I got nothing, no non-installed warning, no reaction with clangd, not output of vscode-clangd...I am confused, how to do next step?
![image](https://user-images.githubusercontent.com/17326718/148737655-d5a6a221-133e-4346-af5d-3840d17c17f7.png)

**Comment by stark-zhang** [comment]
It worked after filled the absolute path of `clangd.sh` into `clangd.path`. thanks a lot~
