### ISSUE TITLE
Add option to activate extension as soon as workspace is opened

### ISSUE THREAD

**Issue by stefanhaller** [clangd/vscode-clangd#275]
Currently, the extension only activates as soon as a C++ file is opened. This is a problem if you want to use "Go to symbol in workspace" to open the first C++ file; you first have to open an arbitrary C++ file to make that work. I reload my windows fairly often for a number of reasons, so I'm running into this problem a lot.

I'd like to have an option to activate the extension right after opening a workspace. I'm not sure how easy that is to implement.

Another option would be to add `"workspaceContains:**/*.cpp" to `"activationEvents"`, but I'm not sure if that's desirable for everybody.

**Comment by sam-mccall** [comment]
Even if running, the language server wouldn't respond to workspace/symbols today until a file is open: it gets results from the index, and it knows which indexes to load based on which files are open.
(This is solvable by searching for indexes based on the workspace path, I think, but we have to decide what to do about background indexing etc)

And such a mode could never be the default: the purpose of activation is to avoid wasting resources on extensions that won't be used, and spawning language servers which load indexes is expensive (maybe the user isn't even going to edit c++ code).

If this isn't quite trivial to add/maintain, and it needs to be opt-in, I'm not sure it's going to benefit enough people to justify it. (I don't think we've had previous requests for this workflow).

**Comment by stefanhaller** [comment]
I see, thanks for the quick reply! Guess I'll have to live it, then.

**Comment by sam-mccall** [comment]
Yeah, sorry about that :-(
