### ISSUE TITLE
Windows clangd-13 doesn't find standard headers

### ISSUE THREAD

**Issue by wgumenyuk** [clangd/vscode-clangd#282]
Hi everbody, I experience issues with clangd-13 not being able to find C++ standard headers.
The extension underlines the `#include` and displays a `clang(pp_file_not_found)` error. I use CMake and g++ on Windows for building my projects and have placed a `compile_commands.json` in the project's root directory. Completely reinstalling all programs as well as the extension didn't resolve the issue unfortunately.

In the logs I found that the driver produced command includes directories (`-internal-isystem`) that don't exist on my computer (line 322), although I am not sure that this is causing the problem.

On my other Windows computer this extension works flawlessly. What could be causing this issue?
Thanks a lot!

```cpp
#include <iostream>  // 'iostream' file not found clang(pp_file_not_found)

int main() {
    return 0;
}
```

**Logs**
[log.txt](https://github.com/clangd/vscode-clangd/files/7912879/log.txt)

**System information**
Clangd version: `13.0.0 (x86_64-pc-windows-msvc)`
clangd extension version: `0.1.13`
g++ version: `8.1.0`
Operating system: Windows 10 (build 19042.1348)

**Comment by kadircet** [comment]
Have you tried following https://clangd.llvm.org/guides/system-headers ?

**Comment by wgumenyuk** [comment]
Thank you very much! That guide did help resolve the issue.

**Comment by htlpt** [comment]
i ran into the same issue, so how to change -internal-isystem path?
