### ISSUE TITLE
Toggle inlay hints command not working

### ISSUE THREAD

**Issue by zrno** [clangd/vscode-clangd#289]
Issue Type: <b>Bug</b>

Just updated the extension to 0.0.14 and tried executing the "clangd: toggle inlay hints" command from the command pallete and got this error: 
![image](https://user-images.githubusercontent.com/13214299/151060112-6dfad10c-9303-4508-93ae-bf229c1579fa.png)

No other output in the clangd output tab.

Extension version: 0.1.14
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.16.2-arch1-1
Restricted Mode: No

clangd version 13.0.0
Features: linux
Platform: x86_64-pc-linux-gnu

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|31.07GB (14.54GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 87fed376-385e-4b70-a6e7-f62fe0f386e3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by sam-mccall** [comment]
This means your installed doesn't support inlay hints. You'll need a recent snapshot or the upcoming 14 release.
