### ISSUE TITLE
Error: command 'clangd.inlayHints.toggle' already exists

### ISSUE THREAD

**Issue by HighCommander4** [clangd/vscode-clangd#298]
I sometimes get this error when restarting clangd.

```
Error: command 'clangd.inlayHints.toggle' already exists
	at u.registerCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:28683)
	at Object.registerCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:107:30423)
	at n9.initialize (/home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.15/out/bundle.js:239:7973)
	at Mb.initializeFeatures (/home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.15/out/bundle.js:36:13023)
	at /home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.15/out/bundle.js:36:5978
```

I think this might happen because this command is registered [at initialize() time](https://github.com/clangd/vscode-clangd/blob/21cc1a5ad494c5f1f9a728c9ee7e1eab5e22a2a9/src/inlay-hints.ts#L133) as opposed to [in the feature constructor](https://github.com/clangd/vscode-clangd/blob/21cc1a5ad494c5f1f9a728c9ee7e1eab5e22a2a9/src/switch-source-header.ts#L7), and `initialize()` gets called again when restarting? (Not sure why it doesn't happen on _every_ restart though...)

**Comment by HighCommander4** [comment]
Ah, it doesn't happen on **explicit** (`clangd.restart` command invocation) restarts because that invokes disposables [here](https://github.com/clangd/vscode-clangd/blob/21cc1a5ad494c5f1f9a728c9ee7e1eab5e22a2a9/src/extension.ts#L22), but it happens on **crash** restarts because... that doesn't?

**Comment by HighCommander4** [comment]
I wasn't sure how to get `clientsOptions.errorHandler` to run disposables (presumably it's possible to wrap the default error handler somehow to do so?), so I opted instead to add a check to `inlay-hints.ts` to ensure we don't try to register the command multiple times.

**Comment by jwake** [comment]
Thanks for this! I was literally just now trying to figure out why the restart wasn't restarting while trying to come up with a minimal reproducer for a peculiar crasher I keep getting when I finish typing the word `parallel` in `#pragma omp parallel` so I can file an issue about it 😅
