### ISSUE TITLE
Call hierarchy: go to actual line calling function

### ISSUE THREAD

**Issue by gianmarcoodorizzi** [clangd/vscode-clangd#299]
Hi,
if I right click on a function name and "Show Call Hierarchy" the hierarchy is shown on the left pane.
Let's assume function f() calls g() which in turn calls h().

Call hierarchy for h() is:

h()
     > g()
             > f()
If I click on g(), I am brought to g()'s prototype, while I would have expected to be brought to the exact line where h() gets called inside g() (which could be many lines below the function's prototype).

Is there something wrong with my setup or is this the intended behavior?

Thank you in advance.

**Comment by HighCommander4** [comment]
Unfortunately, this is an upstream issue in vscode: https://github.com/microsoft/vscode/issues/111454, and not something we can control on the clangd side

**Comment by gianmarcoodorizzi** [comment]
Thanks! Since you reported this a long time ago, though, it does not look so promising...
