### ISSUE TITLE
Debug with launch.json

### ISSUE THREAD

**Issue by juxeii** [clangd/vscode-clangd#304]
How would a launch.json look like, to get a working debug configuration?
All examples I have seen refer to the C++ extension from MS.

**Comment by sam-mccall** [comment]
Clangd is not a debugger, so the vscode-clangd extension does not provide debugging features.

You may be interested in [CodeLLDB](
https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) which is LLDB based, or [Native Debug](https://marketplace.visualstudio.com/items?itemName=webfreak.debug) which can talk to standalone LLDB or GDB over the MI protocol.
