### ISSUE TITLE
Compilation database location for multi-root workspace

### ISSUE THREAD

**Issue by gianmarcoodorizzi** [clangd/vscode-clangd#305]
Hello,
are multi-root workspaces supported?
I have added a  `project.code-workspace` under the project's `.vscode` folder:

`{
	"folders": [
		{
			"path": ".."
		},
		{
			"path": "../../common"
		}
	],
	"settings": {}
}`

And other code from a _common_ library.
I am able to compile the project and the _compile_commands.json_ is under: /home/user/git/cs/project/build.

When I try to open a source file inside that _common_  folder, this is what I get:

> I[09:50:31.276] clangd version 13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
> I[09:50:31.276] Features: linux+grpc
> I[09:50:31.276] PID: 21509
> I[09:50:31.277] Working directory: /home/user/git/cs/project
> I[09:50:31.277] argv[0]: /home/user/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/bin/clangd
> I[09:50:31.277] argv[1]: -log=verbose
> I[09:50:31.277] argv[2]: --query-driver=/opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/bin/arm-fslc-linux-gnueabi/arm-fslc-linux-gnueabi-g++
> V[09:50:31.277] User config file is /home/user/.config/clangd/config.yaml
> I[09:50:31.277] Starting LSP over stdin/stdout
> V[09:50:31.289] <<< {"id":0,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"markdown":{"parser":"marked","version":"1.1.0"},"regularExpressions":{"engine":"ECMAScript","version":"ES2020"},"staleRequestSupport":{"cancel":true,"retryOnContentModified":["textDocument/semanticTokens/full","textDocument/semanticTokens/range","textDocument/semanticTokens/full/delta"]}},"textDocument":{"callHierarchy":{"dynamicRegistration":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"dynamicRegistration":true,"honorsChangeAnnotations":false,"isPreferredSupport":true,"resolveSupport":{"properties":["edit"]}},"codeLens":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"completion":{"completionItem":{"commitCharactersSupport":true,"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"insertReplaceSupport":true,"insertTextModeSupport":{"valueSet":[1,2]},"labelDetailsSupport":true,"preselectSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"contextSupport":true,"dynamicRegistration":true,"editsNearCursor":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"documentHighlight":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"documentSymbol":{"dynamicRegistration":true,"hierarchicalDocumentSymbolSupport":true,"labelSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"foldingRange":{"dynamicRegistration":true,"lineFoldingOnly":true,"rangeLimit":5000},"formatting":{"dynamicRegistration":true},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"linkedEditingRange":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"publishDiagnostics":{"codeDescriptionSupport":true,"dataSupport":true,"relatedInformation":true,"tagSupport":{"valueSet":[1,2]},"versionSupport":false},"rangeFormatting":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"honorsChangeAnnotations":true,"prepareSupport":true,"prepareSupportDefaultBehavior":1},"selectionRange":{"dynamicRegistration":true},"semanticTokens":{"dynamicRegistration":true,"formats":["relative"],"multilineTokenSupport":false,"overlappingTokenSupport":false,"requests":{"full":{"delta":true},"range":true},"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator"]},"signatureHelp":{"contextSupport":true,"dynamicRegistration":true,"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true}},"window":{"showDocument":{"support":true},"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"workDoneProgress":true},"workspace":{"applyEdit":true,"codeLens":{"refreshSupport":true},"configuration":true,"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"fileOperations":{"didCreate":true,"didDelete":true,"didRename":true,"dynamicRegistration":true,"willCreate":true,"willDelete":true,"willRename":true},"semanticTokens":{"refreshSupport":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"workspaceEdit":{"changeAnnotationSupport":{"groupsOnLabel":true},"documentChanges":true,"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"Visual Studio Code","version":"1.65.2"},"initializationOptions":{"clangdFileStatus":true,"fallbackFlags":[]},"locale":"en","processId":21336,"rootPath":"/home/user/git/cs/project","rootUri":"file:///home/user/git/cs/project","trace":"off","workspaceFolders":[{"name":"project","uri":"file:///home/user/git/cs/project"},{"name":"common","uri":"file:///home/user/git/cs/common"}]}}
> 
> I[09:50:31.289] <-- initialize(0)
> I[09:50:31.355] --> reply:initialize(0) 65 ms
> V[09:50:31.355] >>> {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"astProvider":true,"callHierarchyProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"compilationDatabase":{"automaticReload":true},"completionProvider":{"allCommitCharacters":[" ","\t","(",")","[","]","{","}","<",">",":",";",",","+","-","/","*","%","^","&","#","?",".","=","\"","'","|"],"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"implementationProvider":true,"memoryUsageProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":["declaration","deprecated","deduced","readonly","static","abstract","dependentName","defaultLibrary","functionScope","classScope","fileScope","globalScope"],"tokenTypes":["variable","variable","parameter","function","method","function","property","variable","class","interface","enum","enumMember","type","type","unknown","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d) linux+grpc x86_64-unknown-linux-gnu"}}}
> 
> V[09:50:31.376] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}
> 
> I[09:50:31.376] <-- initialized
> V[09:50:31.376] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"cpp","text":"#include \"bytearray.h\"\r\n\r\nByteArray::ByteArray()\r\n\t: std::vector<char>()\r\n{\r\n\r\n}\r\n\r\nByteArray::ByteArray(const char * nullTerminatedData)\r\n\t:ByteArray(nullTerminatedData, strlen(nullTerminatedData))\r\n{\r\n}\r\n\r\nByteArray::ByteArray(const void * data, int lenght)\r\n{\r\n    if (lenght > 0)\r\n        assign((char *)data, (char *)data+lenght);\r\n}\r\nconst ByteArray fromJson(const nlohmann::json & json){\r\n    auto dumpData = json.dump();\r\n    ByteArray data(dumpData.c_str(), dumpData.length());\r\n    return data;\r\n}\r\n\r\nByteArray::ByteArray(const nlohmann::json & json)\r\n    : ByteArray(fromJson(json))\r\n{}\r\n\r\nByteArray::operator std::string() const\r\n{\r\n\treturn std::string(begin(), end());\r\n}\r\n","uri":"file:///home/user/git/cs/common/common/bytearray.cpp","version":1}}}
> 
> I[09:50:31.376] <-- textDocument/didOpen
> I[09:50:31.383] **Failed to find compilation database for /home/user/git/cs/common/common/bytearray.cpp**
> I[09:50:31.383] ASTWorker building file /home/user/git/cs/common/common/bytearray.cpp version 1 with command clangd fallback
> [/home/user/git/cs/common/common]
> /usr/bin/clang -resource-dir=/home/user/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/lib/clang/13.0.0 -- /home/user/git/cs/common/common/bytearray.cpp
> V[09:50:31.437] <<< {"id":1,"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///home/user/git/cs/common/common/bytearray.cpp"}}}
> 
> I[09:50:31.437] <-- textDocument/documentSymbol(1)
> V[09:50:31.440] <<< {"id":2,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/user/git/cs/common/common/bytearray.cpp"}}}
> 
> I[09:50:31.440] <-- textDocument/documentLink(2)
> V[09:50:31.446] Driver produced command: cc1 -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name bytearray.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/home/user/git/cs/common/common -resource-dir /home/user/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/lib/clang/13.0.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/backward -internal-isystem /home/user/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/lib/clang/13.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir=/home/user/git/cs/common/common -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /home/user/git/cs/common/common/bytearray.cpp
> I[09:50:31.446] --> textDocument/clangd.fileStatus
> V[09:50:31.446] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Update (1)","uri":"file:///home/user/git/cs/common/common/bytearray.cpp"}}
> 
> V[09:50:31.446] Building first preamble for /home/user/git/cs/common/common/bytearray.cpp version 1
> V[09:50:31.623] indexed preamble AST for /home/user/git/cs/common/common/bytearray.cpp version 1:
>   symbol slab: 2705 symbols, 779232 bytes
>   ref slab: 0 symbols, 0 refs, 128 bytes
>   relations slab: 276 relations, 8728 bytes
> V[09:50:31.647] Build dynamic index for header symbols with estimated memory usage of 2349444 bytes
> V[09:50:31.648] Built preamble of size 1136588 for file /home/user/git/cs/common/common/bytearray.cpp version 1
> I[09:50:31.649] --> workspace/semanticTokens/refresh(0)
> V[09:50:31.649] >>> {"id":0,"jsonrpc":"2.0","method":"workspace/semanticTokens/refresh","params":null}
> 
> I[09:50:31.649] --> textDocument/clangd.fileStatus
> V[09:50:31.649] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Build AST for (1)","uri":"file:///home/user/git/cs/common/common/bytearray.cpp"}}
> 
> V[09:50:31.653] <<< {"id":0,"jsonrpc":"2.0","result":null}
> 
> I[09:50:31.653] <-- reply(0)
> V[09:50:31.703] <<< {"id":3,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///home/user/git/cs/common/common/bytearray.cpp"}}}
> 
> I[09:50:31.703] <-- textDocument/semanticTokens/full(3)
> V[09:50:31.759] Trying to fix unresolved name "strlen" in scopes: []
> V[09:50:31.759] Dex query tree: (LIMIT 10000 (& T=len T=trl T=rle T=str S= ?=Restricted For Code Completion))
> V[09:50:31.760] Trying to fix unresolved name "assign" in scopes: []
> V[09:50:31.760] Dex query tree: (LIMIT 10000 (& T=ssi T=ass T=sig T=ign S= ?=Restricted For Code Completion))
> V[09:50:31.760] Trying to fix unresolved name "json" in scopes: [nlohmann::]
> V[09:50:31.760] Dex query tree: false
> V[09:50:31.761] Trying to fix unresolved name "json" in scopes: [nlohmann::]
> V[09:50:31.774] Trying to fix unresolved name "string" in scopes: [std::]
> V[09:50:31.774] Dex query tree: (LIMIT 10000 (& T=rin T=ing T=tri T=str S=std:: ?=Restricted For Code Completion))
> V[09:50:31.775] indexed file AST for /home/user/git/cs/common/common/bytearray.cpp version 1:
>   symbol slab: 5 symbols, 5376 bytes
>   ref slab: 6 symbols, 15 refs, 4416 bytes
>   relations slab: 0 relations, 24 bytes
> V[09:50:31.775] Build dynamic index for main-file symbols with estimated memory usage of 13992 bytes
> I[09:50:31.775] --> textDocument/publishDiagnostics
> V[09:50:31.775] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"pp_file_not_found","message":"In included file: '../include/json.hpp' file not found","range":{"end":{"character":22,"line":0},"start":{"character":9,"line":0}},"relatedInformation":[{"location":{"range":{"end":{"character":30,"line":3},"start":{"character":9,"line":3}},"uri":"file:///home/user/git/cs/common/common/bytearray.h"},"message":"Error occurred here"}],"severity":1,"source":"clang"},{"code":"not_direct_base_or_virtual","message":"Type 'std::vector<char>' is not a direct or virtual base of 'ByteArray'","range":{"end":{"character":8,"line":3},"start":{"character":3,"line":3}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'strlen'","range":{"end":{"character":38,"line":9},"start":{"character":32,"line":9}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'assign'","range":{"end":{"character":14,"line":16},"start":{"character":8,"line":16}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'nlohmann'","range":{"end":{"character":39,"line":18},"start":{"character":31,"line":18}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'nlohmann'","range":{"end":{"character":35,"line":24},"start":{"character":27,"line":24}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"typename_nested_not_found","message":"No type named 'string' in namespace 'std'","range":{"end":{"character":31,"line":28},"start":{"character":25,"line":28}},"relatedInformation":[],"severity":1,"source":"clang"}],"uri":"file:///home/user/git/cs/common/common/bytearray.cpp","version":1}}
> 
> V[09:50:31.776] ASTWorker running DocumentSymbols on version 1 of /home/user/git/cs/common/common/bytearray.cpp
> I[09:50:31.776] --> reply:textDocument/documentSymbol(1) 338 ms
> V[09:50:31.776] >>> {"id":1,"jsonrpc":"2.0","result":[{"detail":"()","kind":9,"name":"ByteArray::ByteArray","range":{"end":{"character":1,"line":6},"start":{"character":0,"line":2}},"selectionRange":{"end":{"character":20,"line":2},"start":{"character":11,"line":2}}},{"detail":"(const char *)","kind":9,"name":"ByteArray::ByteArray","range":{"end":{"character":1,"line":11},"start":{"character":0,"line":8}},"selectionRange":{"end":{"character":20,"line":8},"start":{"character":11,"line":8}}},{"detail":"(const void *, int)","kind":9,"name":"ByteArray::ByteArray","range":{"end":{"character":1,"line":17},"start":{"character":0,"line":13}},"selectionRange":{"end":{"character":20,"line":13},"start":{"character":11,"line":13}}},{"detail":"const ByteArray (const int &)","kind":12,"name":"fromJson","range":{"end":{"character":1,"line":22},"start":{"character":0,"line":18}},"selectionRange":{"end":{"character":24,"line":18},"start":{"character":16,"line":18}}},{"detail":"(const int &)","kind":9,"name":"ByteArray::ByteArray","range":{"end":{"character":2,"line":26},"start":{"character":0,"line":24}},"selectionRange":{"end":{"character":20,"line":24},"start":{"character":11,"line":24}}}]}
> 
> V[09:50:31.776] ASTWorker running DocumentLinks on version 1 of /home/user/git/cs/common/common/bytearray.cpp
> I[09:50:31.776] --> reply:textDocument/documentLink(2) 336 ms
> V[09:50:31.776] >>> {"id":2,"jsonrpc":"2.0","result":[{"range":{"end":{"character":22,"line":0},"start":{"character":9,"line":0}},"target":"file:///home/user/git/cs/common/common/bytearray.h"}]}
> 
> V[09:50:31.776] ASTWorker running SemanticHighlights on version 1 of /home/user/git/cs/common/common/bytearray.cpp
> I[09:50:31.776] --> reply:textDocument/semanticTokens/full(3) 73 ms
> V[09:50:31.776] >>> {"id":3,"jsonrpc":"2.0","result":{"data":[2,0,9,8,2048,0,11,9,8,513,6,0,9,8,2048,0,11,9,8,513,0,23,18,2,265,5,0,9,8,2048,0,11,9,8,513,0,23,4,2,265,0,10,6,2,257,2,8,6,2,256,1,8,6,14,64,0,15,4,2,264,0,14,4,2,264,0,5,6,2,256,2,6,9,8,2048,0,10,8,3,2049,0,32,4,2,265,1,9,8,1,257,1,4,9,8,2048,0,10,4,1,257,1,11,4,1,256,3,0,9,8,2048,0,11,9,8,513,0,33,4,2,265],"resultId":"1"}}
> 
> I[09:50:31.776] --> textDocument/clangd.fileStatus
> V[09:50:31.776] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///home/user/git/cs/common/common/bytearray.cpp"}}
> 

It seems like VSC is unable to find the compilation database. On the other hand, everything looks fine if I open a source file inside the "main" project. Any help would be greatly appreciated :)

EDIT: If I copy the compilation database to folder _common_ it gets recognized.

**Comment by HighCommander4** [comment]
I recommend using `--compile-commands-dir` as described [in this FAQ entry](https://clangd.llvm.org/faq#how-do-i-fix-errors-i-get-when-opening-headers-outside-of-my-project-directory)

**Comment by gianmarcoodorizzi** [comment]
Works like a charm. Thank you!
