### ISSUE TITLE
No inlay hints on MacOS arm64 using clang/llvm-clang

### ISSUE THREAD

**Issue by zheng95z** [clangd/vscode-clangd#320]
There is no inlay hints on my MacOS system. However, I have inlay hints on another windows platform with same settings.

Also, when I tried to use `toggle inlay hints`, there was an error said "Command 'clangd: Toggle inlay hints' resulted in an error (command 'clangd.inlayHints.toggle' not found)". Any ideas?

**System information**
```bash
Apple clangd version 13.0.0 (clang-1300.0.29.30)
argv[0]: /Library/Developer/CommandLineTools/usr/bin/clangd
argv[1]: --compile-commands-dir=.vscode
argv[2]: -j=13
argv[3]: --pch-storage=memory
argv[4]: --header-insertion=never
```

**Comment by sam-mccall** [comment]
> Apple clangd version 13.0.0

Apple clangd is a fork that we can't provide support for. You can get clangd 14 from the GitHub releases page.

**Comment by BIKA-C** [comment]
This version also has no inlay hint running on my m1 mac. I have the same setting on a linux machine, and it works fine.
```
clangd version 15.0.1 (https://github.com/llvm/llvm-project b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf)
Features: mac+grpc+xpc
Platform: x86_64-apple-darwin21.6.0
```
