### ISSUE TITLE
Clangd not finding includes defined in precompiled-header

### ISSUE THREAD

**Issue by ki-bo** [clangd/vscode-clangd#324]
Using clangd extension together with cmake-tools to build a simple hello world project with precompiled headers enabled on macOS. The extension complains about use of undeclared identifier 'std' in main.cpp - indicating the <iostream> include of the used pch.h is ignored. The project builds fine, though.
Any ideas what I am doing wrong?

These files have been used to set-up the project:

main.cpp:
```
int main() {
  std::cout << "Hello World\n";
  return 0;
}
```

pch.h:
```
#include <iostream>
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.16)
project(testapp LANGUAGES CXX)
add_executable(testapp main.cpp)
target_precompile_headers(testapp PUBLIC pch.h)
```

[clangd.log](https://github.com/clangd/vscode-clangd/files/8546826/clangd.log)

**System information**
Clangd version (from the log, or `clangd --version`): Apple clangd version 13.1.6 (clang-1316.0.21.2.3)
clangd extension version: 0.1.15
Operating system: macOS 12.3.1

**Comment by ki-bo** [comment]
Just also downloaded llvm14 release and tried that one instead of AppleClang. Again, the executable is built successfully, but clangd still complains as mentioned above.

This is the clangd log output with the 14.00 LLVM:
```
I[14:09:59.476] clangd version 14.0.0 (https://github.com/tru/llvm-release-build fc075d7c96fe7c992dde351695a5d25fe084794a)
I[14:09:59.477] Features: mac+xpc
I[14:09:59.477] PID: 91080
I[14:09:59.477] Working directory: /Users/robert/coding/vscode-clangd-pch-issue
I[14:09:59.477] argv[0]: /Users/robert/clang+llvm-14.0.0-x86_64-apple-darwin/bin/clangd
I[14:09:59.477] Starting LSP over stdin/stdout
I[14:09:59.477] <-- initialize(0)
I[14:09:59.499] --> reply:initialize(0) 21 ms
I[14:09:59.503] <-- initialized
I[14:09:59.503] <-- textDocument/didOpen
I[14:09:59.504] Loaded compilation database from /Users/robert/coding/vscode-clangd-pch-issue/compile_commands.json
I[14:09:59.504] ASTWorker building file /Users/robert/coding/vscode-clangd-pch-issue/main.cpp version 1 with command 
[/Users/robert/coding/vscode-clangd-pch-issue/build]
/Users/robert/clang+llvm-14.0.0-x86_64-apple-darwin/bin/clang++ --driver-mode=g++ -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Winvalid-pch -Xarch_arm64 -include/Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hxx -o CMakeFiles/testapp.dir/main.cpp.o -c -resource-dir=/Users/robert/clang+llvm-14.0.0-x86_64-apple-darwin/lib/clang/14.0.0 -- /Users/robert/coding/vscode-clangd-pch-issue/main.cpp
I[14:09:59.505] Loaded compilation database from /Users/robert/coding/vscode-clangd-pch-issue/build/compile_commands.json
I[14:09:59.505] --> window/workDoneProgress/create(0)
I[14:09:59.505] Enqueueing 1 commands for indexing
I[14:09:59.506] <-- reply(0)
I[14:09:59.506] --> $/progress
I[14:09:59.506] --> $/progress
I[14:09:59.507] --> $/progress
I[14:09:59.507] --> $/progress
I[14:09:59.512] --> textDocument/clangd.fileStatus
I[14:09:59.528] --> workspace/semanticTokens/refresh(1)
I[14:09:59.528] --> textDocument/clangd.fileStatus
I[14:09:59.528] --> textDocument/clangd.fileStatus
I[14:09:59.528] <-- reply(1)
I[14:09:59.532] <-- textDocument/semanticTokens/full(1)
I[14:09:59.536] --> textDocument/publishDiagnostics
I[14:09:59.536] --> reply:textDocument/semanticTokens/full(1) 3 ms
I[14:09:59.536] --> textDocument/clangd.fileStatus
```

**Comment by HighCommander4** [comment]
Looking at the compile command from the logs:

> /Users/robert/clang+llvm-14.0.0-x86_64-apple-darwin/bin/clang++ --driver-mode=g++ -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Winvalid-pch -Xarch_arm64 -include/Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hxx -o CMakeFiles/testapp.dir/main.cpp.o -c -resource-dir=/Users/robert/clang+llvm-14.0.0-x86_64-apple-darwin/lib/clang/14.0.0 -- /Users/robert/coding/vscode-clangd-pch-issue/main.cpp

I see it includes the flag:

> -include/Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hxx

Does the file `/Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hxx` contain the contents of your `pch.h`, or something else?

**Comment by ki-bo** [comment]
This is its contents:

/Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hxx:
```
/* generated by CMake */

#pragma clang system_header
#ifdef __cplusplus
#include "/Users/robert/coding/vscode-clangd-pch-issue/pch.h"
#endif // __cplusplus
```

And this is the contents of /Users/robert/coding/vscode-clangd-pch-issue/pch.h:
```
#include <iostream>
```

I think I read somewhere that there is an issue with the hxx file extension. Therefore I tried to rename cmake_pch_arm64.hxx to cmake_pch_arm64.hpp and manually edited the -include you mentioned to point to the .hpp instead of the .hxx file. And suddenly, this fixes it - the std namespace in main.cpp is visible again for the clangd extension.

I wonder whether this can be fixed without having to manually patch cmake to use a different file extension for the generated precompiled header related files?

**Comment by HighCommander4** [comment]
> I think I read somewhere that there is an issue with the hxx file extension. Therefore I tried to rename cmake_pch_arm64.hxx to cmake_pch_arm64.hpp and manually edited the -include you mentioned to point to the .hpp instead of the .hxx file. And suddenly, this fixes it - the std namespace in main.cpp is visible again for the clangd extension.

Very curious.

If you're able to find the thing you read about `.hxx`, I would be interested to see it.

> I wonder whether this can be fixed without having to manually patch cmake to use a different file extension for the generated precompiled header related files?

I agree that `.hxx` should work just as well as `.hpp` in this case.

I tried to reproduce the issue locally (I'm running Linux) with similarly named files and compile commands, but for me the `-include` works fine even with the `.hxx` extension, so I'm not quite sure what's going on here.

**Comment by HighCommander4** [comment]
Oh, wait! I just noticed that in your compile commands the `-include` is preceded by `-Xarch_arm64`.

This is significant. Options that begin with `-X` modify the handling of the **next** argument. So, I guess `-Xarch_arm64 -include<file>` means something like "apply `-include<file>` only when targeting arm64".

(Any chance that when you modified the `.hxx` to `.hpp`, you ended up with a command line where the `-include was **not** preceded by `-Xarch_arm64`? If so, that would explain why it started working.)

Quite possibly clangd does not handle `-X` options like this correctly, which should be investigated further. In the meantime, is it easy for you to arrange for the compile command to contain the `-include` without the preceding `-X...`?

**Comment by ki-bo** [comment]
Ok, maybe renaming of the .hxx to .hpp was not leading to the correct conclusion. Actually, there are four files in the CMake build folder after a successful build:

```
cmake_pch.hxx
cmake_pch_arm64.hxx
cmake_pch_arm64.hxx.cxx
cmake_pch_arm64.hxx.pch
```

For testing, I renamed all four of them, replacing `hxx` in their respective filename with `hpp`. Doing it on all four files and then manually replacing all occurrences in compile_commands.json will let the issue appear again. So, in fact the include of the hxx seems to work, but if the other files match as well, then clangd is again complaining about the unknown std namespace.

This is the compile_commands.json after replacing `hxx`with `hpp`:
```
[
  {
    "directory": "/Users/robert/coding/vscode-clangd-pch-issue/build",
    "command": "/Users/robert/clang+llvm-14.0.0-x86_64-apple-darwin/bin/clang++ -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Winvalid-pch -fpch-instantiate-templates -Xclang -emit-pch -Xclang -include -Xclang /Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hpp -x c++-header -o CMakeFiles/testapp.dir/cmake_pch_arm64.hpp.pch -c /Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hpp.cxx",
    "file": "/Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hpp.cxx"
  },
  {
    "directory": "/Users/robert/coding/vscode-clangd-pch-issue/build",
    "command": "/Users/robert/clang+llvm-14.0.0-x86_64-apple-darwin/bin/clang++ -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Winvalid-pch -Xarch_arm64 -include/Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hpp -o CMakeFiles/testapp.dir/main.cpp.o -c /Users/robert/coding/vscode-clangd-pch-issue/main.cpp",
    "file": "/Users/robert/coding/vscode-clangd-pch-issue/main.cpp"
  }
]
```

I also did the same on a Linux machine, and found out it is referencing the pct in a different way there (on Linux I do not see this issue btw). The Linux compile_commands.json shows it is using `-Xclang -include-pch` and if I understand the Clang documentation correctly, this is the expected way of referencing the precompiled header. Why is the -include-pch missing on macOS?

**Comment by HighCommander4** [comment]
> Why is the -include-pch missing on macOS?

I'm sorry, I don't know. I've reached the limit of my knowledge regarding PCH.

My suggestion remains the one made in the previous comment: can you arrange for the `compile_commands.json` to not contain the `-Xarch_arm64` flag?

If not, I think you can accomplish the same effect by instructing clangd to ignore it by putting the following into a `.clangd` config file in the project root:

```
CompileFlags:
  Remove: -Xarch_arm64
```

**Comment by ki-bo** [comment]
Thank you again for your answer!

I removed the `-Xarch_arm64` flag from `compile_commands.json`:

```
[
  {
    "directory": "/Users/robert/coding/vscode-clangd-pch-issue/build",
    "command": "/Users/robert/clang+llvm-14.0.0-x86_64-apple-darwin/bin/clang++ -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Winvalid-pch -fpch-instantiate-templates -Xclang -emit-pch -Xclang -include -Xclang /Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hxx -x c++-header -o CMakeFiles/testapp.dir/cmake_pch_arm64.hxx.pch -c /Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hxx.cxx",
    "file": "/Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hxx.cxx"
  },
  {
    "directory": "/Users/robert/coding/vscode-clangd-pch-issue/build",
    "command": "/Users/robert/clang+llvm-14.0.0-x86_64-apple-darwin/bin/clang++ -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Winvalid-pch -include/Users/robert/coding/vscode-clangd-pch-issue/build/CMakeFiles/testapp.dir/cmake_pch_arm64.hxx -o CMakeFiles/testapp.dir/main.cpp.o -c /Users/robert/coding/vscode-clangd-pch-issue/main.cpp",
    "file": "/Users/robert/coding/vscode-clangd-pch-issue/main.cpp"
  }
]
```

Unfortunately, the issue still remains: clangd complains about not knowing the namespace std.

**Comment by sam-mccall** [comment]
I think this is a bad interaction between clangd and clang's driver.

- clangd definitely can't actually consume the PCH file created by the build systtem (which could be from another compiler, another version of clang, built with different options etc).
- For this reason, we clear `CI.getPreprocessorOpts().ImplicitPCHInclude` in Compiler.cpp. If we assume `-Xclang -include-pch` is an optimization only and all headers are explicitly included, this would be safe, but that assumption is fragile.
- there's also logic in clang's driver (`Driver/Toolchains/Clang.cpp`) that will "upgrade" `-include` to `-include-pch` if a matching `*.gch` or `*.pch` file happens to exist (without any version/timestamp check, seems dangerous! also bypasses the VFS...)
- so between these two steps, the `-include` flag you're relying on for correctness (which also doesn't seem ideal) is just being dropped

So I think the fix is to somehow add a config knob to the Driver to disable this upgrade behavior.

**Comment by ki-bo** [comment]
I was wondering why the clang compilation differs between Linux and macOS regarding PCH related flags, as mentioned above. Is there any reason for this?

**Comment by sam-mccall** [comment]
I'm not sure, but I do see the problem on linux (same symptoms as on Mac). And it goes away if I delete the PCH file (CMakeFiles/testapp.dir/cmake_pch.hxx.gch), which is the giveaway that the include=>include-pch upgrade is the problem.

To see this bug, you have to have a compiler that generates PCH files with the name clang(d) expects relative to the header, but which are not actually compatible. So you might not see it if your host compiler is too different *or* too similar to your clangd. I wouldn't worry too much about it.

**Comment by ki-bo** [comment]
Yes, I understand that incompatible PCH formats may lead to issues. Therefore I made sure to configure the clangd extension to not use its own but the matching clangd binary of my Cland-14 install instead. That should not introduce format incompatibility issues, I assumed.

**Comment by sam-mccall** [comment]
https://github.com/clangd/clangd/issues/856 is a very similar issue
