### ISSUE TITLE
after update to v0.1.16, language server fails to install

### ISSUE THREAD

**Issue by mveldink** [clangd/vscode-clangd#325]
Version 0.1.15 still works. But after updating to 0.1.16, installation of the lang server via vscode command palette fails like this: 

<img width="453" alt="image" src="https://user-images.githubusercontent.com/97469566/165170492-818d7414-82c7-45c3-966c-ef04110b9c49.png">

There is no corresponding log output that I could find.

Clangd version (from the log, or `clangd --version`): clangd version 9.0.0 (tags/RELEASE_900/final)
clangd extension version: v0.1.16
Operating system: Debian Jessie (I know ; )

**Comment by sam-mccall** [comment]
Thanks, looks related to https://github.com/node-fetch/node-fetch/issues/784, node-fetch is doing some dubious introspection that's broken by minification. esbuild's keep-names option may help: https://esbuild.github.io/api/#keep-names

Will cut a new release tomorrow.

**Comment by sam-mccall** [comment]
Sorry about the delay, should be fixed in 0.1.17.
