### ISSUE TITLE
Cannot find module vscode-clangd\out\bundle, debug fail

### ISSUE THREAD

**Issue by leovincentseles** [clangd/vscode-clangd#328]
First of all, thanks a lot of all your hard work! I really love this vscode extension. I am new to the node and typescript, correct me if needed.

# Problem description
## Cannot find module vscode-clangd\out\bundle
- **Step 1**: Clone the [clangd](https://github.com/clangd/vscode-clangd) project
- **Step 2**: Follow the steps in [Developing.md](https://github.com/clangd/vscode-clangd/blob/master/DEVELOPING.md)
- **Step 3**: When the debugging window is opened, I open a cpp file, and vscode will report `Activating extension 'llvm-vs-code-extensions.vscode-clangd' failed: Cannot find module 'd:\Downloads\vscode-clangd\out\bundle'`

## Failed to use the breakpoint in the debugging mode
- If we have out/bundle.js in our project path, we still cannot set up the breakpoint correctly.
- The extension will keep going without hitting any breakpoint in the debugging mode.

# Reason
- When we press the F5 button, the vscode will first execute the preLaunchTask `npm` which is defined in [tasks.json](https://github.com/clangd/vscode-clangd/blob/master/.vscode/tasks.json). 
- In the `npm` task, it will call `npm run ts-compile --loglevel silent` which is defined in the scripts section of [package.json](https://github.com/clangd/vscode-clangd/blob/master/package.json).
- Finally, we will compile the entire project into `out/src/*.js` and `out/test/*.js`
- However, the entry point of this extension is `./out/bundle` which will not be generated until we call the `esbuild` manually. (This is the reason for **Cannot find module vscode-clangd\out\bundle**)
- Even when we have called the `esbuild` manually, the breakpoint still not work. Because the output bundle file cannot provide the diagnostic information during the execution. (This is the reason for **Failed to use the breakpoint in the debugging mode**)

# Three possible solutions
Here I have three ideas about this issue.

## Use different entry points for debugging and release
- I have searched a while, but I still cannot find how to define different entry point for debugging and release in [package.json](https://github.com/clangd/vscode-clangd/blob/master/package.json)

## Use same entry points for debugging and release
- For the debugging mode and release version, we both use `./out/src/extension` as our entry point
- Change the esbuild to generate the bundle file with name `out/src/extension.js` which will overwrite the file generated in the debugging stage.
- In this way, the debugging mode will work. Also the breakpoint can work.
- However, I am not sure if this is a good option here.

## Manually change the main section in [package.json](https://github.com/clangd/vscode-clangd/blob/master/package.json)
- When people want to debug this extension, they should change the `main` to `./out/src/extension`. And thus the debugging window can find correct entry point. Also the breakpoint will work.
- Suggest to include some related descriptions in the [Developing.md](https://github.com/clangd/vscode-clangd/blob/master/DEVELOPING.md)

**System information**
clangd version **14.0.0**
Features: **windows**
Platform: **x86_64-w64-windows-gnu**

**Comment by sam-mccall** [comment]
We switched to esbuild + bundling, the problems are:
 - the tasks.json entry is still just invoking tsc, and isn't doing the bundling
 - we also need the sourcemap (bundle.js.map) so debugging works

I think I worked out how to fix this.
