### ISSUE TITLE
Disabling annotations inserted into the code

### ISSUE THREAD

**Issue by Roman-Koshelev** [clangd/vscode-clangd#339]
I did not find an option to disable such annotations. How can this be done?
![123](https://user-images.githubusercontent.com/34384083/169756833-dc9200e3-62f3-4c32-924f-e95d9d41fa7c.png)

**Comment by sam-mccall** [comment]
These are called inlay hints.
They can be disabled in the VSCode settings, or with the command "clangd: toggle inlay hints".

(The many duplicate hints here looks like a bug - please feel free to file with details of the code!)

**Comment by i-ky** [comment]
Inlay hints can also be adjusted in [clangd configuration file](https://clangd.llvm.org/config#inlayhints).
