### ISSUE TITLE
feature request: Parameter Hints shown inline all the time (like IntelliJ) 

### ISSUE THREAD

**Issue by dwlsalmeida** [clangd/vscode-clangd#34]
Hello,

There has been extensive discussion over this issue here: https://github.com/Microsoft/vscode/issues/16221

I noticed rust-analyzer provides similar functionality for rust,  see https://user-images.githubusercontent.com/2771466/71774757-54269200-2fc8-11ea-8505-ac2f326761ca.png

I wonder whether it is possible to implement support for this in vscode-clangd for C/C++? I noticed that this already happens when you first type a function, but what I am looking for is something that is shown inline all the time.

**Comment by HighCommander4** [comment]
It should be possible. It needs server-side support, which is tracked in https://github.com/clangd/clangd/issues/313.

**Comment by Trass3r** [comment]
For the record, there is an LSP proposal: https://github.com/microsoft/language-server-protocol/issues/956.

**Comment by HighCommander4** [comment]
This has been implemented on both the server side (in clangd 14) and client side (vscode-clangd 0.1.14, controlled via `editor.inlayHints.enabled`); I think the issue can be closed.
