### ISSUE TITLE
inlay hints gone

### ISSUE THREAD

**Issue by Trass3r** [clangd/vscode-clangd#342]
It looks like https://github.com/llvm/llvm-project/commit/3137ca80b9ef99359a4adf77512925c2edc461b9 stopped inlay hints from working for me.
`editor.inlayHints.enabled` is on of course. But there are no [`textDocument/inlayHint`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint) messages.
If I comment out https://github.com/clangd/vscode-clangd/blob/dc6518fb0af230c73aa309ef9086e37a49c7e35f/src/inlay-hints.ts#L59 they come back, but based on the `clangd/inlayHints` protocol of course.

Can anyone confirm this behavior?

**System information**

Output of `clangd --version`: `clangd version 15.0.0
Features: linux
Platform: x86_64-unknown-linux-gnu`
Editor/LSP plugin: VSCode 1.67.2 / 0.1.17

**Comment by sam-mccall** [comment]
Unfortunately, needed to revert this and push 0.1.19 as it broke completion (e.g. #357).

Apparently the way we use commit characters + snippets is broken and we never noticed because commit characters were broken in languageclient :-(

**Comment by HighCommander4** [comment]
Looks like this is fixed in vscode-clangd 0.1.20.

The inlay hints may look a bit different by default now that it's vscode rendering them natively, but this can be customized (e.g. font size using `editor.inlayHints.fontSize`, colors using `editorInlayHint.foreground/background` in `workbench.colorCustomizations`).

**Comment by Trass3r** [comment]
True they did look better in the past iirc.
Now they look confusingly similar to selected/highlighted text in the dark theme.
