### ISSUE TITLE
Add setting for disabling clang-tidy warnings

### ISSUE THREAD

**Issue by petar-avramovic** [clangd/vscode-clangd#345]
Note: we mostly implement features in the clangd language server, and rely on Microsoft's LSP client framework to expose these in VSCode. Features requiring a lot of VSCode-specific work are unlikely to be implemented.

I was looking for settings that have minimal impact to default VSCode appearance (only show warnings about compile errors).
I tried to disable clang-tidy warnings in settings but I was not able to, closest thing I found online was this: 
https://weliveindetail.github.io/blog/post/2021/10/20/vscode-hide-warning-markers.html

**Comment by sam-mccall** [comment]
You can do this in the clangd config file:

```
Diagnostics:
  ClangTidy:
    Remove: '*'
```
https://clangd.llvm.org/config#clangtidy

**Comment by petar-avramovic** [comment]
Thanks, that worked,
btw is there a way to this without having to add .clangd config file to the project ?

**Comment by sam-mccall** [comment]
You can add it as ~/.config/clangd/config.yaml, or your OS-equivalent.
