### ISSUE TITLE
Integration with cmake vs code extension.

### ISSUE THREAD

**Issue by audetto** [clangd/vscode-clangd#349]
I have a c++ project in VSCode which uses cmake to build.

I have installed this extension too.

I have configured the cmake build directory in settings with

`cmake.buildDirectory": "${workspaceFolder}/build-${buildType}"`

This extension does not seem to use it and the only solution has been to create a symlink.
Should it not look into cmake settings and fetch the commands.json from there?

In the same way as I can use `${command:cmake.launchTargetDirectory}"` in `launch.json`?

**Comment by i-ky** [comment]
@audetto, I would suggest to use [`cmake.copyCompileCommands` setting](https://github.com/microsoft/vscode-cmake-tools/blob/f23388d191d376c2b062768778edee097c176aeb/docs/cmake-settings.md), it will tell CMake Tools extension to copy `compile_commands.json` from current build directory to a single place where clangd expects to see it. As far as I know, clangd watches `compile_commands.json` file and its modification/overwrite will be automatically detected.

**Comment by audetto** [comment]
Perfect thank you.
