### ISSUE TITLE
NOLINT should recognize line breaks

### ISSUE THREAD

**Issue by meldavis** [clangd/vscode-clangd#351]
It would be nice if NOLINT and NOLINTNEXTLINE would recognize line breaks put in by clang-format.

The following does not work:

```c++
// NOLINTNEXTLINE(*reinterpret-cast, *no-int-to-ptr)
auto *handle = 
        reinterpret_cast<HANDLE>(::_get_osfhandle(STD_OUTPUT_HANDLE));

```

Placing NOLINT at the end, causes the break in a different location. So it still does not work.

```c++
 auto *handle = reinterpret_cast<HANDLE>(::_get_osfhandle(
        STD_OUTPUT_HANDLE)); // NOLINT(*reinterpret-cast, *no-int-to-ptr)

```

**Workaround**

Turn off clang format for that line of code:

```c++
    // clang-format off
    // NOLINTNEXTLINE(*reinterpret-cast, *no-int-to-ptr)
    auto *handle = reinterpret_cast<HANDLE>(::_get_osfhandle(STD_OUTPUT_HANDLE));
    // clang-format on
```

**Comment by i-ky** [comment]
@meldavis, according to [Clang Tidy documentation](https://clang.llvm.org/extra/clang-tidy/) you should be able to use `NOLINTBEGIN` and `NOLINTEND` comments:
```cpp
// NOLINTBEGIN(*reinterpret-cast, *no-int-to-ptr)
auto *handle = 
        reinterpret_cast<HANDLE>(::_get_osfhandle(STD_OUTPUT_HANDLE));
// NOLINTEND(*reinterpret-cast, *no-int-to-ptr)
```

**Comment by meldavis** [comment]
Yes!  Thanks.  I'm sorry for the noise.

**Comment by i-ky** [comment]
For the reference, there are a couple of related issues in the main LLVM repo: https://github.com/llvm/llvm-project/issues/31559 and https://github.com/llvm/llvm-project/issues/41128
