### ISSUE TITLE
use of scan-build

### ISSUE THREAD

**Issue by peter197321** [clangd/vscode-clangd#36]
Hello all,

Can the vscode-clangd use scan-build for static analysis? 
if so please do you have some examples or can you point me how to use scan-build with vscode?

Thank you.

**Comment by sam-mccall** [comment]
No, clangd doen't support the clang static analyzer, which is the backend for scan-build.

It might be possible to get it to work, but:
 - it would take some effort and testing
 - our limited experience is that (at least for C++) it isn't stable enough on broken code to embed in a long-running process
 - it probably requires a more complete AST (we drop function bodies from included files for speed)
