### ISSUE TITLE
Support Nightly Snapshots of LLVM

### ISSUE THREAD

**Issue by kaladron** [clangd/vscode-clangd#366]
It would be very nice if it were possible to either specify the path to clangd manually or have this detect the snapshot versions, and invoke clangd-15

**Comment by sam-mccall** [comment]
You can set `clangd.path` in vscode settings to point to a custom binary, do i misunderstand what you need?

**Comment by kaladron** [comment]
I might be hold it wrong. =)

I went to the extensions page, tapped the gear, then tapped extension settings, I only see:
Clangd: Arguments
Clangd: Check Updates
Clangd: Detect Extension Conflicts
Clangd: Fallback Flags
Clangd: On Config Changed
Clangd: Restart After Crash
Clangd: Server Completion Ranking
Clangd: Trace

I'll search up clangd.path and see how to set it.  Thanks!

**Comment by sam-mccall** [comment]
Sorry, i think sometimes it is hidden in the UI. Foolproof way is to set it in the raw json view (though i think there's some way to see it in the settings UI)

I think this is a side effect us marking that setting "local to the machine" (which affects removing/settings sync behavior)

**Comment by sam-mccall** [comment]
Going to close this as this is possible and I use it regularly - please reply if it's still unclear.
