### ISSUE TITLE
Auto complete starting at incorrect entry

### ISSUE THREAD

**Issue by dwilliamson** [clangd/vscode-clangd#37]
Please see history of closed issue on VSCode: https://github.com/microsoft/vscode/issues/98835

Here's a visual repro of the problem, with debug view enabled:

![AutoComplete3](https://user-images.githubusercontent.com/1532903/83622435-e0dd7800-a587-11ea-83ed-85c8c915fe0f.gif)

I'm trying to get `KeyHeld` to select so that I can press `tab` to auto complete. I have `"editor.suggestSelection":"first"` setup in my settings.

When I type `KeyH` it still selects `KeyStateHeld`. I have to type `KeyHeld` completely for it to highlight and enable tab completion.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362
clangd version: 10.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (18.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
unicode-math-vscode|Gui|0.2.6
vscode-clangd|llv|0.1.5
cpptools|ms-|0.28.1
perforce|sle|3.2.0
vscode-jumpy|wma|0.3.1

</details>

**Comment by sam-mccall** [comment]
This is a ranking issue, and never possible to get 100% right. Having the desired result in the second slot isn't ideal, but you should still be able to press down->tab to complete the item. 

With a debug build of clangd you can run with `-debug-only=CodeComplete.cpp` to get an explanation of why `KeyStateHeld` is ranked higher despite a worse name match score. This requires building clangd from source though. Are you able to minimize this into a small file you can share?

Various signals can affect this, e.g. KeyStateHeld is more often called in the codebase, or its type matches the expected one (in this case `bool`), or textual matches... actually that one looks likely, you have `state` on the line and the word `state` in the name.

**Comment by dwilliamson** [comment]
This is happening everywhere and it's terribly frustrating. Another example:

* `file::Pa` matches `file::ParseSafePath`. Fair enough.
* `file::Pat` matches `file::JoinPath`. That's not right.

This never used to happen before with vscode-clangd. vscode-cpptools gets it right and, as far back as 20 years ago, good old Visual Assist would get it right. There seems to be more context going into this decision than I, as a user, would expect. Having to move my fingers to the cursor keys to match what I expect is suboptimal, especially when I'm doing it most of the time.

Leave this with me; I'll get a debug clangd build up and running and see what happens.

**Comment by dwilliamson** [comment]
This is from typing `.KeyH`. Is there enough information here to diagnose what's going on? I might try attaching and finding out.

```
I[15:17:00.204] Code complete: sema context DotMemberAccess, query scopes [] (AnyScope=true), expected type <none>
I[15:17:00.206] Code complete: 22 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 22 returned.
I[15:17:00.222] --> reply:textDocument/completion(224) 189 ms
I[15:17:00.250] <-- textDocument/codeAction(225)
I[15:17:00.256] ASTWorker building file c:\dev\Celtoys\Star\src\CppClient\Game\Parts\prtActor.cpp version 62 with command 
[c:\dev\Celtoys\Star]
c:\dev\Github\llvm\llvm-project\build3\Debug\bin\clang-tool -xc++ -m32 -std=c++14 -DCLCPP_SIZE_TYPE=size_t -DCLCPP_SIZE_TYPE_HEX_FORMAT="lX" -DVSCODE_INTELLISENSE -DRMT_USE_TINYCRT -DWITH_WASAPI -Isrc\CppClient -Iextern\bullet\src -Iextern\clReflect\release\inc -Iextern\DynamicPatcher\Source -Iextern\soloud\include -Iextern -Ibuild\gen\Debug -Isrc\CppClient\TinyCRT\stdlib c:\dev\Celtoys\Star\src\CppClient\Game\Parts\prtActor.cpp -fsyntax-only -resource-dir=c:\dev\Github\llvm\llvm-project\build3\Debug\lib\clang\11.0.0
I[15:17:00.268] --> textDocument/clangd.fileStatus
I[15:17:00.747] <-- textDocument/didChange
I[15:17:00.750] <-- $/cancelRequest
I[15:17:00.750] <-- textDocument/completion(226)
I[15:17:00.907] Code complete: sema context DotMemberAccess, query scopes [] (AnyScope=true), expected type <none>
I[15:17:00.910] Code complete: 11 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 11 returned.
I[15:17:00.917] --> reply:textDocument/completion(226) 166 ms
I[15:17:00.996] <-- textDocument/documentLink(227)
I[15:17:00.997] <-- textDocument/codeAction(228)
I[15:17:01.490] <-- textDocument/didChange
I[15:17:01.493] <-- $/cancelRequest
I[15:17:01.494] <-- textDocument/completion(229)
I[15:17:01.656] Code complete: sema context DotMemberAccess, query scopes [] (AnyScope=true), expected type <none>
I[15:17:01.658] Code complete: 11 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 11 returned.
I[15:17:01.666] --> reply:textDocument/completion(229) 171 ms
I[15:17:01.740] <-- textDocument/codeAction(230)
I[15:17:02.065] <-- textDocument/didChange
I[15:17:02.070] <-- $/cancelRequest
I[15:17:02.070] <-- textDocument/completion(231)
I[15:17:02.236] Code complete: sema context DotMemberAccess, query scopes [] (AnyScope=true), expected type <none>
I[15:17:02.239] Code complete: 11 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 11 returned.
I[15:17:02.246] --> reply:textDocument/completion(231) 176 ms
I[15:17:02.289] --> textDocument/publishDiagnostics
I[15:17:02.300] --> textDocument/semanticHighlighting
I[15:17:02.300] --> reply:textDocument/codeAction(225) 2050 ms, error: Task was cancelled.
I[15:17:02.301] --> reply:textDocument/documentLink(227) 1304 ms, error: Task was cancelled.
I[15:17:02.301] --> reply:textDocument/codeAction(228) 1304 ms, error: Task was cancelled.
I[15:17:02.301] --> reply:textDocument/codeAction(230) 561 ms, error: Task was cancelled.
I[15:17:02.302] --> textDocument/clangd.fileStatus
I[15:17:02.486] <-- textDocument/documentLink(232)
I[15:17:02.491] ASTWorker building file c:\dev\Celtoys\Star\src\CppClient\Game\Parts\prtActor.cpp version 65 with command 
[c:\dev\Celtoys\Star]
c:\dev\Github\llvm\llvm-project\build3\Debug\bin\clang-tool -xc++ -m32 -std=c++14 -DCLCPP_SIZE_TYPE=size_t -DCLCPP_SIZE_TYPE_HEX_FORMAT="lX" -DVSCODE_INTELLISENSE -DRMT_USE_TINYCRT -DWITH_WASAPI -Isrc\CppClient -Iextern\bullet\src -Iextern\clReflect\release\inc -Iextern\DynamicPatcher\Source -Iextern\soloud\include -Iextern -Ibuild\gen\Debug -Isrc\CppClient\TinyCRT\stdlib c:\dev\Celtoys\Star\src\CppClient\Game\Parts\prtActor.cpp -fsyntax-only -resource-dir=c:\dev\Github\llvm\llvm-project\build3\Debug\lib\clang\11.0.0
I[15:17:02.504] --> textDocument/clangd.fileStatus
I[15:17:02.552] <-- textDocument/codeAction(233)
I[15:17:02.911] <-- textDocument/didChange
I[15:17:02.914] <-- $/cancelRequest
I[15:17:02.914] <-- textDocument/completion(234)
I[15:17:03.070] Code complete: sema context DotMemberAccess, query scopes [] (AnyScope=true), expected type <none>
I[15:17:03.072] Code complete: 4 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 4 returned.
I[15:17:03.074] --> reply:textDocument/completion(234) 160 ms
I[15:17:03.131] <-- textDocument/codeAction(235)
I[15:17:03.879] <-- textDocument/documentLink(236)
I[15:17:04.503] --> textDocument/publishDiagnostics
I[15:17:04.516] --> textDocument/semanticHighlighting
I[15:17:04.516] --> reply:textDocument/documentLink(232) 2029 ms, error: Task was cancelled.
I[15:17:04.517] --> reply:textDocument/codeAction(233) 1964 ms, error: Task was cancelled.
I[15:17:04.522] ASTWorker building file c:\dev\Celtoys\Star\src\CppClient\Game\Parts\prtActor.cpp version 66 with command 
[c:\dev\Celtoys\Star]
c:\dev\Github\llvm\llvm-project\build3\Debug\bin\clang-tool -xc++ -m32 -std=c++14 -DCLCPP_SIZE_TYPE=size_t -DCLCPP_SIZE_TYPE_HEX_FORMAT="lX" -DVSCODE_INTELLISENSE -DRMT_USE_TINYCRT -DWITH_WASAPI -Isrc\CppClient -Iextern\bullet\src -Iextern\clReflect\release\inc -Iextern\DynamicPatcher\Source -Iextern\soloud\include -Iextern -Ibuild\gen\Debug -Isrc\CppClient\TinyCRT\stdlib c:\dev\Celtoys\Star\src\CppClient\Game\Parts\prtActor.cpp -fsyntax-only -resource-dir=c:\dev\Github\llvm\llvm-project\build3\Debug\lib\clang\11.0.0
I[15:17:04.537] --> textDocument/clangd.fileStatus
I[15:17:04.768] <-- textDocument/codeAction(237)
I[15:17:04.769] <-- $/cancelRequest
I[15:17:06.494] --> textDocument/publishDiagnostics
I[15:17:06.505] --> textDocument/semanticHighlighting
I[15:17:06.505] --> reply:textDocument/codeAction(235) 3374 ms, error: Task was cancelled.
I[15:17:06.513] --> reply:textDocument/documentLink(236) 2634 ms
I[15:17:06.525] --> reply:textDocument/codeAction(237) 1756 ms
I[15:17:06.525] --> textDocument/clangd.fileStatus
I[15:17:06.758] <-- textDocument/codeAction(238)
I[15:17:06.765] --> reply:textDocument/codeAction(238) 7 ms
I[15:17:06.766] --> textDocument/clangd.fileStatus
I[15:17:07.953] <-- textDocument/documentSymbol(239)
I[15:17:07.982] --> reply:textDocument/documentSymbol(239) 29 ms
I[15:17:07.986] --> textDocument/clangd.fileStatus
```

**Comment by sam-mccall** [comment]
It's clear what's going on at a high level: name match isn't the only factor that affects ranking. Your logs aren't useful to dig into the specific cases, because they don't contain the dump of signals for each candidate. That's fine, though.

It sounds like maybe you want prefix name matches to be weighted higher compared to non-prefix matches plus other signals, which is fair enough.

Regarding your specific examples:
 - KeyHeld vs KeyStateHeld is almost certainly the context-word-boosting I mentioned. When the full word is matched, it gets a further 2x boost which is enough for KeyHeld to win. A higher boost for prefix matches would help here.
 - is `file::Path` a type alias (rather than class) by any chance? ParsePath is probably liked here because it's more commonly used in the codebase. IIRC we don't properly count uses of type aliases.
