### ISSUE TITLE
What clang-format version is clangd using?

### ISSUE THREAD

**Issue by gianmarcoodorizzi** [clangd/vscode-clangd#370]
Although I was not able to find the clang-format binary in my VSC installation, I have been able to locate clangd paths:

`~/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/14.0.3/clangd_14.0.3/bin`

Since 

> clangd embeds clang-format, which can reformat your code: fixing indentation, breaking lines, and reflowing comments.

is clang-format actually invoked from clangd? If so, how?
Thank you in advance.

**Comment by sam-mccall** [comment]
> is clang-format actually invoked from clangd? If so, how?

clangd does not invoke an external clang-format binary. The clang-format formatting engine is included in the clangd binary, just as the clang parser etc is.

clang-format, clang, and clangd source code is all part of the git repository, so the clangd version is also the effective clang-format and clang version.
