### ISSUE TITLE
Outline doesn't show functions inside the scope of `extern "C" {}" in "_Remote-SSH_" mode

### ISSUE THREAD

**Issue by are-scenic** [clangd/vscode-clangd#374]
### Problem Statement

VSCode allows working in a remote mode using feature `Remote-SSH: Connect to Host...`.
This allows developing on a remote machine from VSCode running on your workstation/laptop.

When _clangd_ extension is used, there are issues with behavior of outline. 
Specifically if a header file has a scope `extern "C" {...}`, then all functions defined within that scope are not shown in outline.

I compared it with the behavior of IntelliSense of the official _Microsoft C/C++_ extension and its own behavior on a local machine.
Both the official _Microsoft C/C++_ extension and the official _clangd_ extension (when operating locally on the workstation/laptop) are showing the functions within the `exten` scope. 

Please note that all other symbols (e.g. structs, enums, global variables) are presented in the outline window properly.

> Unfortunately I can't provide screenshots, logs and examples, since all these contain sensitive information.

### Code Example

Here is an example for such a header file that doesn't show in the Outline window the functions that are declared within  `extern "C" {...}` scope:

```c
...
#ifdef __cplusplus
extern "C" {
#endif
...
status_t lib_get_version(void);

status_t lib_init(void);
...
#ifdef __cplusplus
}
#endif
```

None of the functions in the aforementioned example will be shown in the outline window when _clangd_ is used a language server with the remote Workspace.

### System information

Clangd:                               10.0.0-4ubuntu1_
clangd extension version:   v0.1.21
Operating system: 
- Ubuntu 20.04 on a remote computer with the codebase
- Windows 11 on the host with VSCode

> There is another issue with the Remote-SSH mode when using _clangd_, which is related to _Call History_.
> This issue is submitted in a separate Bug report (see #375)

**Comment by sam-mccall** [comment]
This bug (missing symbols inside `extern "C"`) was fixed in clangd 12, here clangd on the ubuntu machine is version 10.

The reason it's working locally and not remotely is that your local clangd is newer.

If your distro doesn't provide a newer release, you can download it from https://github.com/clangd/clangd/releases.
