### ISSUE TITLE
Feature _Show Call Hierarchy_ doesn't work in a "_Remote-SSH_" mode

### ISSUE THREAD

**Issue by are-scenic** [clangd/vscode-clangd#375]
> This issue is related to another ticket and might have the same root of cause (see issue #374)

### Problem Statement

VSCode allows remote development using "_Remote-SSH_" mode, which allows development on a remote machine using VSCode on a workstation/laptop.
When using `clangd` extension as a language server for C++ in the "_Remote-SSH_" mode, the option of showing _Show Call Hierarchy_ (which is available in a regular non-remote mode) simply disappears from the right-click menu. The interesting thing that _Show Type Hierarchy_ does appear in right-click menu. This is very similar to the issue with the outline window described by the issue #374.

### Logs

Unfortunately, no logs, screenshots or real code examples can be presented, due to the sensitive nature of this information.

### System information

- Clangd: 10.0.0-4ubuntu1_
- clangd extension version:   v0.1.21
- Operating system: 
  - Ubuntu 20.04 on a remote computer with the codebase
  - Windows 11 on the host with VSCode

**Comment by sam-mccall** [comment]
Similar to the other linked bug, call hierarchy was first supported in clangd 12, the version of clangd on your remote system is too old.
