### ISSUE TITLE
Go to symbol only shows current file

### ISSUE THREAD

**Issue by infn-ke** [clangd/vscode-clangd#377]
The function go to symbol only shows symbols in the current file. Is there no way to search through all symbols in the project?

Using clangd 11.0.1-2.

**Comment by HighCommander4** [comment]
VSCode has a "Go to symbol in editor" command and a "Go to symbol in workspace" command. The latter should offer symbols from the whole project, assuming the project is indexed.

**Comment by infn-ke** [comment]
Thanks! But realized this issue was caused by clangd not picking up the right compilation database. Seems it defaults to reading it from the source directory. Is that configurable?

**Comment by HighCommander4** [comment]
Yes, using the `--compile-commands-dir` command line argument to clangd (discussed e.g. [here](https://clangd.llvm.org/faq#how-do-i-fix-errors-i-get-when-opening-headers-outside-of-my-project-directory)).
