### ISSUE TITLE
Show call hierarchy does not show anything

### ISSUE THREAD

**Issue by infn-ke** [clangd/vscode-clangd#378]
When I do "Show call hierarchy" from the command palette, then nothing is shown. I don't see any output either in output window from clangd, some maybe vscode does not send the command to clangd?

clangd version 11.0.1-2
Debian Bullseye

**Comment by HighCommander4** [comment]
Support for call hierarchy was added in clangd version 12.

**Comment by infn-ke** [comment]
Confirming it works with clangd 12.
