### ISSUE TITLE
Objective-C/C++ support

### ISSUE THREAD

**Issue by blacktop** [clangd/vscode-clangd#379]
I believe clangd can support Objective-C++, but when I try to "goto definition" with the extension it does nothing.

Thanks!

**Comment by sam-mccall** [comment]
Can you provide more details please?
The following works for me, saved as `test.mm`:

```
@class Foo;
Foo *x; // go to def on Foo
```

**Comment by blacktop** [comment]
I just tried on `checkSettingsControlledByCaptivePortalMode` in `WebKit/WebKit/Tools/TestWebKitAPI/Tests/WebKitCocoa/ProcessSwapOnNavigation.mm` it's defined in the same file and a little pop-up says 'No definition found for checkSettingsControlledByCaptivePortalMode

**Comment by blacktop** [comment]
I am getting jump to def working on other mm files so this might be a issue with Test files?

**Comment by HighCommander4** [comment]
Most likely a configuration issue. Sharing [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs) may allow diagnosing the issue further.
