### ISSUE TITLE
Enabling clangd extension in vscode causes #else macro to be highlighted as comment.

### ISSUE THREAD

**Issue by Rid1-fz-06** [clangd/vscode-clangd#388]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Please attach the clangd log from the "Output" window if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

I[21:30:09.246] clangd version 15.0.1 (https://github.com/llvm/llvm-project b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf)
I[21:30:09.247] Features: linux+grpc
I[21:30:09.247] PID: 3101
I[21:30:09.247] Working directory: /home/rid1/Projects/tests
I[21:30:09.247] argv[0]: /home/rid1/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/15.0.1/clangd_15.0.1/bin/clangd
I[21:30:09.247] Starting LSP over stdin/stdout
I[21:30:09.248] <-- initialize(0)
I[21:30:09.249] --> reply:initialize(0) 1 ms
I[21:30:09.395] <-- initialized
I[21:30:09.413] <-- textDocument/didOpen
I[21:30:09.419] Failed to find compilation database for /home/rid1/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/15.0.1/clangd_15.0.1/lib/clang/15.0.1/include/stdint.h
I[21:30:09.423] ASTWorker building file /home/rid1/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/15.0.1/clangd_15.0.1/lib/clang/15.0.1/include/stdint.h version 1 with command clangd fallback
[/home/rid1/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/15.0.1/clangd_15.0.1/lib/clang/15.0.1/include]
/usr/bin/clang -xobjective-c++-header -resource-dir=/home/rid1/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/15.0.1/clangd_15.0.1/lib/clang/15.0.1 -- /home/rid1/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/15.0.1/clangd_15.0.1/lib/clang/15.0.1/include/stdint.h
I[21:30:09.435] --> textDocument/clangd.fileStatus
I[21:30:09.453] --> workspace/semanticTokens/refresh(0)
I[21:30:09.453] --> textDocument/clangd.fileStatus
I[21:30:09.459] <-- reply(0)
I[21:30:09.468] --> textDocument/clangd.fileStatus
I[21:30:09.506] <-- textDocument/codeAction(1)
I[21:30:09.514] <-- textDocument/documentLink(2)
I[21:30:09.514] <-- textDocument/inlayHint(3)
I[21:30:09.532] --> textDocument/publishDiagnostics
I[21:30:09.532] --> reply:textDocument/codeAction(1) 26 ms
I[21:30:09.532] --> reply:textDocument/documentLink(2) 18 ms
I[21:30:09.532] --> reply:textDocument/inlayHint(3) 18 ms
I[21:30:09.533] --> textDocument/clangd.fileStatus
I[21:30:09.706] <-- textDocument/semanticTokens/full(4)
I[21:30:09.712] --> reply:textDocument/semanticTokens/full(4) 5 ms
I[21:30:09.712] --> textDocument/clangd.fileStatus
I[21:30:10.068] <-- textDocument/documentLink(5)
I[21:30:10.068] --> reply:textDocument/documentLink(5) 0 ms
I[21:30:10.068] --> textDocument/clangd.fileStatus
I[21:30:10.068] <-- $/setTrace
I[21:30:10.068] unhandled notification $/setTrace
I[21:30:10.533] <-- textDocument/codeAction(6)
I[21:30:10.533] --> reply:textDocument/codeAction(6) 0 ms
I[21:30:10.533] --> textDocument/clangd.fileStatus
I[21:30:10.959] <-- $/setTrace
I[21:30:10.959] unhandled notification $/setTrace
I[21:30:10.992] <-- textDocument/hover(7)
I[21:30:11.016] --> reply:textDocument/hover(7) 24 ms
I[21:30:11.016] --> textDocument/clangd.fileStatus
I[21:30:11.160] <-- textDocument/codeAction(8)
I[21:30:11.160] --> reply:textDocument/codeAction(8) 0 ms
I[21:30:11.160] --> textDocument/clangd.fileStatus
I[21:30:11.222] <-- textDocument/documentSymbol(9)
I[21:30:11.222] --> reply:textDocument/documentSymbol(9) 0 ms
I[21:30:11.222] --> textDocument/clangd.fileStatus
I[21:30:12.770] <-- textDocument/inlayHint(10)
I[21:30:12.771] --> reply:textDocument/inlayHint(10) 0 ms
I[21:30:12.771] --> textDocument/clangd.fileStatus
I[21:30:13.499] <-- textDocument/inlayHint(11)
I[21:30:13.499] --> reply:textDocument/inlayHint(11) 0 ms
I[21:30:13.499] --> textDocument/clangd.fileStatus
I[21:30:13.542] <-- textDocument/documentLink(12)
I[21:30:13.542] --> reply:textDocument/documentLink(12) 0 ms
I[21:30:13.542] --> textDocument/clangd.fileStatus
I[21:30:13.545] <-- textDocument/inlayHint(13)
I[21:30:13.545] --> reply:textDocument/inlayHint(13) 0 ms
I[21:30:13.545] --> textDocument/clangd.fileStatus
I[21:30:13.976] <-- textDocument/documentLink(14)
I[21:30:13.976] --> reply:textDocument/documentLink(14) 0 ms
I[21:30:13.976] --> textDocument/clangd.fileStatus
I[21:30:13.993] <-- textDocument/inlayHint(15)
I[21:30:13.993] --> reply:textDocument/inlayHint(15) 0 ms
I[21:30:13.993] --> textDocument/clangd.fileStatus
I[21:30:14.369] <-- textDocument/inlayHint(16)
I[21:30:14.369] --> reply:textDocument/inlayHint(16) 0 ms
I[21:30:14.369] --> textDocument/clangd.fileStatus
I[21:30:14.414] <-- textDocument/inlayHint(17)
I[21:30:14.414] --> reply:textDocument/inlayHint(17) 0 ms
I[21:30:14.414] --> textDocument/clangd.fileStatus
I[21:30:14.605] <-- textDocument/inlayHint(18)
I[21:30:14.605] --> reply:textDocument/inlayHint(18) 0 ms
I[21:30:14.606] --> textDocument/clangd.fileStatus
I[21:30:14.636] <-- textDocument/inlayHint(19)
I[21:30:14.636] --> reply:textDocument/inlayHint(19) 0 ms
I[21:30:14.636] --> textDocument/clangd.fileStatus
I[21:30:14.668] <-- textDocument/inlayHint(20)
I[21:30:14.668] --> reply:textDocument/inlayHint(20) 0 ms
I[21:30:14.668] --> textDocument/clangd.fileStatus
I[21:30:15.366] <-- textDocument/inlayHint(21)
I[21:30:15.366] --> reply:textDocument/inlayHint(21) 0 ms
I[21:30:15.366] --> textDocument/clangd.fileStatus
I[21:30:15.444] <-- textDocument/inlayHint(22)
I[21:30:15.444] --> reply:textDocument/inlayHint(22) 0 ms
I[21:30:15.444] --> textDocument/clangd.fileStatus
I[21:30:15.499] <-- textDocument/inlayHint(23)
I[21:30:15.499] --> reply:textDocument/inlayHint(23) 0 ms
I[21:30:15.499] --> textDocument/clangd.fileStatus
I[21:30:15.571] <-- textDocument/inlayHint(24)
I[21:30:15.571] --> reply:textDocument/inlayHint(24) 0 ms
I[21:30:15.571] --> textDocument/clangd.fileStatus
I[21:30:15.621] <-- textDocument/inlayHint(25)
I[21:30:15.622] --> reply:textDocument/inlayHint(25) 0 ms
I[21:30:15.622] --> textDocument/clangd.fileStatus
I[21:30:15.965] <-- textDocument/inlayHint(26)
I[21:30:15.965] --> reply:textDocument/inlayHint(26) 0 ms
I[21:30:15.966] --> textDocument/clangd.fileStatus
I[21:30:16.005] <-- textDocument/inlayHint(27)
I[21:30:16.005] --> reply:textDocument/inlayHint(27) 0 ms
I[21:30:16.005] --> textDocument/clangd.fileStatus
I[21:30:16.085] <-- textDocument/inlayHint(28)
I[21:30:16.085] --> reply:textDocument/inlayHint(28) 0 ms
I[21:30:16.085] --> textDocument/clangd.fileStatus
I[21:30:16.123] <-- textDocument/inlayHint(29)
I[21:30:16.123] --> reply:textDocument/inlayHint(29) 0 ms
I[21:30:16.123] --> textDocument/clangd.fileStatus
I[21:30:16.459] <-- textDocument/inlayHint(30)
I[21:30:16.459] --> reply:textDocument/inlayHint(30) 0 ms
I[21:30:16.459] --> textDocument/clangd.fileStatus
I[21:30:16.586] <-- textDocument/inlayHint(31)
I[21:30:16.586] --> reply:textDocument/inlayHint(31) 0 ms
I[21:30:16.586] --> textDocument/clangd.fileStatus
I[21:30:17.008] <-- textDocument/inlayHint(32)
I[21:30:17.008] --> reply:textDocument/inlayHint(32) 0 ms
I[21:30:17.008] --> textDocument/clangd.fileStatus
I[21:30:17.037] <-- textDocument/inlayHint(33)
I[21:30:17.038] --> reply:textDocument/inlayHint(33) 0 ms
I[21:30:17.038] --> textDocument/clangd.fileStatus
I[21:30:17.462] <-- textDocument/inlayHint(34)
I[21:30:17.462] --> reply:textDocument/inlayHint(34) 0 ms
I[21:30:17.462] --> textDocument/clangd.fileStatus
I[21:30:17.846] <-- textDocument/inlayHint(35)
I[21:30:17.847] --> reply:textDocument/inlayHint(35) 0 ms
I[21:30:17.847] --> textDocument/clangd.fileStatus
I[21:30:18.130] <-- textDocument/inlayHint(36)
I[21:30:18.130] --> reply:textDocument/inlayHint(36) 0 ms
I[21:30:18.130] --> textDocument/clangd.fileStatus
I[21:30:18.215] <-- textDocument/inlayHint(37)
I[21:30:18.216] --> reply:textDocument/inlayHint(37) 0 ms
I[21:30:18.216] --> textDocument/clangd.fileStatus
I[21:30:18.542] <-- textDocument/inlayHint(38)
I[21:30:18.543] --> reply:textDocument/inlayHint(38) 0 ms
I[21:30:18.543] --> textDocument/clangd.fileStatus
I[21:30:18.802] <-- textDocument/inlayHint(39)
I[21:30:18.802] --> reply:textDocument/inlayHint(39) 0 ms
I[21:30:18.802] --> textDocument/clangd.fileStatus
I[21:30:18.893] <-- textDocument/inlayHint(40)
I[21:30:18.893] --> reply:textDocument/inlayHint(40) 0 ms
I[21:30:18.894] --> textDocument/clangd.fileStatus
I[21:30:19.125] <-- textDocument/inlayHint(41)
I[21:30:19.125] --> reply:textDocument/inlayHint(41) 0 ms
I[21:30:19.125] --> textDocument/clangd.fileStatus
I[21:30:19.199] <-- textDocument/inlayHint(42)
I[21:30:19.199] --> reply:textDocument/inlayHint(42) 0 ms
I[21:30:19.199] --> textDocument/clangd.fileStatus
I[21:30:19.498] <-- textDocument/inlayHint(43)
I[21:30:19.498] --> reply:textDocument/inlayHint(43) 0 ms
I[21:30:19.498] --> textDocument/clangd.fileStatus
I[21:30:19.817] <-- textDocument/inlayHint(44)
I[21:30:19.818] --> reply:textDocument/inlayHint(44) 0 ms
I[21:30:19.818] --> textDocument/clangd.fileStatus
I[21:30:20.115] <-- textDocument/inlayHint(45)
I[21:30:20.115] --> reply:textDocument/inlayHint(45) 0 ms
I[21:30:20.116] --> textDocument/clangd.fileStatus
I[21:30:20.402] <-- textDocument/inlayHint(46)
I[21:30:20.402] --> reply:textDocument/inlayHint(46) 0 ms
I[21:30:20.402] --> textDocument/clangd.fileStatus
I[21:30:20.625] <-- textDocument/inlayHint(47)
I[21:30:20.627] --> reply:textDocument/inlayHint(47) 1 ms
I[21:30:20.627] --> textDocument/clangd.fileStatus
I[21:30:20.696] <-- textDocument/inlayHint(48)
I[21:30:20.697] --> reply:textDocument/inlayHint(48) 0 ms
I[21:30:20.697] --> textDocument/clangd.fileStatus
I[21:30:21.018] <-- textDocument/inlayHint(49)
I[21:30:21.018] --> reply:textDocument/inlayHint(49) 0 ms
I[21:30:21.019] --> textDocument/clangd.fileStatus
I[21:30:21.294] <-- textDocument/inlayHint(50)
I[21:30:21.294] --> reply:textDocument/inlayHint(50) 0 ms
I[21:30:21.294] --> textDocument/clangd.fileStatus
I[21:30:21.581] <-- textDocument/inlayHint(51)
I[21:30:21.581] --> reply:textDocument/inlayHint(51) 0 ms
I[21:30:21.581] --> textDocument/clangd.fileStatus
I[21:30:21.858] <-- textDocument/inlayHint(52)
I[21:30:21.858] --> reply:textDocument/inlayHint(52) 0 ms
I[21:30:21.858] --> textDocument/clangd.fileStatus
I[21:30:22.109] <-- textDocument/inlayHint(53)
I[21:30:22.109] --> reply:textDocument/inlayHint(53) 0 ms
I[21:30:22.110] --> textDocument/clangd.fileStatus
I[21:30:22.444] <-- textDocument/inlayHint(54)
I[21:30:22.444] --> reply:textDocument/inlayHint(54) 0 ms
I[21:30:22.444] --> textDocument/clangd.fileStatus
I[21:30:22.714] <-- textDocument/inlayHint(55)
I[21:30:22.714] --> reply:textDocument/inlayHint(55) 0 ms
I[21:30:22.714] --> textDocument/clangd.fileStatus
I[21:30:23.165] <-- textDocument/inlayHint(56)
I[21:30:23.166] --> reply:textDocument/inlayHint(56) 0 ms
I[21:30:23.166] --> textDocument/clangd.fileStatus
I[21:30:23.426] <-- textDocument/inlayHint(57)
I[21:30:23.426] --> reply:textDocument/inlayHint(57) 0 ms
I[21:30:23.426] --> textDocument/clangd.fileStatus
I[21:39:27.926] <-- textDocument/hover(58)
I[21:39:27.954] --> reply:textDocument/hover(58) 28 ms
I[21:39:27.955] --> textDocument/clangd.fileStatus
I[21:39:38.781] <-- $/setTrace
I[21:39:38.781] unhandled notification $/setTrace
I[21:39:39.036] <-- $/setTrace
I[21:39:39.036] unhandled notification $/setTrace
I[21:39:39.693] <-- textDocument/semanticTokens/full(59)
I[21:39:39.700] --> reply:textDocument/semanticTokens/full(59) 7 ms
I[21:39:39.701] --> textDocument/clangd.fileStatus
I[21:39:41.087] <-- textDocument/hover(60)
I[21:39:41.125] --> reply:textDocument/hover(60) 37 ms
I[21:39:41.125] --> textDocument/clangd.fileStatus
I[21:39:45.407] <-- textDocument/inlayHint(61)
I[21:39:45.407] --> reply:textDocument/inlayHint(61) 0 ms
I[21:39:45.407] --> textDocument/clangd.fileStatus
I[21:39:48.181] <-- textDocument/codeAction(62)
I[21:39:48.182] --> reply:textDocument/codeAction(62) 0 ms
I[21:39:48.182] --> textDocument/clangd.fileStatus
I[21:40:48.247] <-- textDocument/inlayHint(63)
I[21:40:48.248] --> reply:textDocument/inlayHint(63) 0 ms
I[21:40:48.248] --> textDocument/clangd.fileStatus
I[21:40:55.389] <-- textDocument/documentHighlight(64)
I[21:40:55.390] --> reply:textDocument/documentHighlight(64) 0 ms
I[21:40:55.390] --> textDocument/clangd.fileStatus
I[21:40:55.397] <-- textDocument/documentHighlight(65)
I[21:40:55.397] --> reply:textDocument/documentHighlight(65) 0 ms
I[21:40:55.397] --> textDocument/clangd.fileStatus
I[21:40:55.647] <-- textDocument/codeAction(66)
I[21:40:55.647] --> reply:textDocument/codeAction(66) 0 ms
I[21:40:55.647] --> textDocument/clangd.fileStatus
I[21:40:57.920] <-- textDocument/inlayHint(67)
I[21:40:57.920] --> reply:textDocument/inlayHint(67) 0 ms
I[21:40:57.920] --> textDocument/clangd.fileStatus
I[21:41:02.460] <-- textDocument/inlayHint(68)
I[21:41:02.461] --> reply:textDocument/inlayHint(68) 0 ms
I[21:41:02.461] --> textDocument/clangd.fileStatus
I[21:43:34.962] <-- textDocument/codeAction(69)
I[21:43:34.962] --> reply:textDocument/codeAction(69) 0 ms
I[21:43:34.962] --> textDocument/clangd.fileStatus
I[21:43:34.985] <-- textDocument/documentLink(70)
I[21:43:34.985] --> reply:textDocument/documentLink(70) 0 ms
I[21:43:34.985] --> textDocument/clangd.fileStatus
I[21:43:34.985] <-- textDocument/inlayHint(71)
I[21:43:34.985] --> reply:textDocument/inlayHint(71) 0 ms
I[21:43:34.986] --> textDocument/clangd.fileStatus
I[21:43:34.999] <-- textDocument/documentHighlight(72)
I[21:43:34.999] --> reply:textDocument/documentHighlight(72) 0 ms
I[21:43:34.999] --> textDocument/clangd.fileStatus
I[21:43:35.096] <-- textDocument/codeAction(73)
I[21:43:35.097] --> reply:textDocument/codeAction(73) 0 ms
I[21:43:35.097] --> textDocument/clangd.fileStatus
I[21:43:38.119] <-- textDocument/hover(74)
I[21:43:38.148] --> reply:textDocument/hover(74) 29 ms
I[21:43:38.149] --> textDocument/clangd.fileStatus
I[21:43:39.933] <-- textDocument/hover(75)
I[21:43:39.959] --> reply:textDocument/hover(75) 26 ms
I[21:43:39.960] --> textDocument/clangd.fileStatus
I[21:43:41.622] <-- textDocument/inlayHint(76)
I[21:43:41.622] --> reply:textDocument/inlayHint(76) 0 ms
I[21:43:41.622] --> textDocument/clangd.fileStatus
I[21:43:44.518] <-- textDocument/inlayHint(77)
I[21:43:44.519] --> reply:textDocument/inlayHint(77) 0 ms
I[21:43:44.519] --> textDocument/clangd.fileStatus
I[21:43:44.597] <-- textDocument/inlayHint(78)
I[21:43:44.597] --> reply:textDocument/inlayHint(78) 0 ms
I[21:43:44.597] --> textDocument/clangd.fileStatus
I[21:43:44.693] <-- textDocument/inlayHint(79)
I[21:43:44.693] --> reply:textDocument/inlayHint(79) 0 ms
I[21:43:44.693] --> textDocument/clangd.fileStatus
I[21:43:44.742] <-- textDocument/inlayHint(80)
I[21:43:44.742] --> reply:textDocument/inlayHint(80) 0 ms
I[21:43:44.742] --> textDocument/clangd.fileStatus
I[21:43:44.832] <-- textDocument/inlayHint(81)
I[21:43:44.832] --> reply:textDocument/inlayHint(81) 0 ms
I[21:43:44.832] --> textDocument/clangd.fileStatus

**System information**
Clangd version (from the log, or `clangd --version`):15.0.1
clangd extension version:v0.1.21
Operating system:Ubuntu 22.04.1

The following screenshot might describe the problem...

![Screenshot from 2022-10-11 21-23-37](https://user-images.githubusercontent.com/92540820/195138515-c0293ea3-514d-4daf-b43c-5a6eb20d637c.png)

**Comment by HighCommander4** [comment]
This is deliberate: the inactive code region is given a semantic highlighting to indicate its inactive state. `comment` was chosen as the highlighting kind because there wasn't a closer match in the list of LSP highlighting kinds.

You can change the appearance of inactive blocks as described [here](https://github.com/clangd/vscode-clangd/issues/85#issuecomment-744650956) (without affecting the appearance of actual comments, which are highlighted on the client side, not via semantic highlighting).

https://github.com/clangd/vscode-clangd/pull/193 tracks a better solution.
