### ISSUE TITLE
clangd still cannot find header files after specifying the include options

### ISSUE THREAD

**Issue by iceypotato** [clangd/vscode-clangd#393]
I am using Windows 11, and I have downloaded the gcc compiler from mingw-w64, which should include all the basic system headers, and I am using clangd for vscode.
For some reason, clangd still has a hard time trying to find all the basic header files, even when I specify multiple `-isystemC:\path\to\includes`. For example, clangd still fails to find `bits/c++config.h`.
I have made a `.clangd` file to specify the includes.
```
CompileFlags:
  Add: [
    -std=c++20,
    "-isystemC:\\Users\\me\\Documents\\x86_64-12.2.0-release-posix-seh-rt_v10-rev0\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\12.2.0\\include",
    "-isystemC:\\Users\\me\\Documents\\x86_64-12.2.0-release-posix-seh-rt_v10-rev0\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\12.2.0\\include\\c++",
    "-isystemC:\\Users\\me\\Documents\\x86_64-12.2.0-release-posix-seh-rt_v10-rev0\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\12.2.0\\include\\c++\\x86_64-w64-mingw32",
    "-isystemC:\\Users\\me\\Documents\\x86_64-12.2.0-release-posix-seh-rt_v10-rev0\\mingw64\\include",
    "-isystemC:\\Users\\me\\Documents\\x86_64-12.2.0-release-posix-seh-rt_v10-rev0\\mingw64\\x86_64-w64-mingw32\\include"
  ]
```
Am I missing something?
Sorry if this is not the place to get help with clangd.

**Comment by HighCommander4** [comment]
Usually using `--query-driver`(as described towards the end of https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc) is an easier way to let clangd find the compiler's built-in includes than specifying them manually.

With this manually approach, I would guess the issue has something to do with the format of the path (e.g. spaces in the path, backslashes, use of quotes, etc. -- getting this stuff right can be tricky, especially on Windows). If you share [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs) I may be able to offer a more specific diagnosis.

**Comment by iceypotato** [comment]
I tried the query driver option and put the verbose log option. The query driver did not work. Here is the log from when I restarted the language server and clicked on a file.
[clangd verbose.log](https://github.com/clangd/vscode-clangd/files/9791144/clangd.verbose.log)

**Comment by HighCommander4** [comment]
A couple of reasons `--query-driver` is not working in this case:

 1. `--query-driver` currently requires that the project has a `compile_commands.json`, please see https://clangd.llvm.org/installation#project-setup for ways to create one. (This is more a current limitation than a by-design requirement; I'm working in https://github.com/clangd/clangd/issues/1089 to relax this such that `--query-driver` will work with a compiler specified in clangd's config file even in the absence of `compile_commands.json`.)
 2. The argument for `--query-driver` should be the compiler executable, i.e. `..\bin\g++.exe`, not just `..\bin`

**Comment by iceypotato** [comment]
Even with the compile_commands, it still doesn't work. I also fixed `--query-driver` to point to `g++.exe`.

This is my compile_commands.json
```
[
    { 
        "directory": "C:\\Users\\myuser\\Documents\\Visual Studio Code\\C",
        "command": "C:\\Users\\myuser\\Documents\\x86_64-12.2.0-release-posix-seh-rt_v10-rev0\\mingw64\\bin\\g++.exe",
        "file": "*"
    }
]
```

**Comment by HighCommander4** [comment]
Hmm, I don't think you can put `*` in `"file"`, it needs to be a specific file for clangd to find the compile command.

I also wouldn't recommend writing the `compile_commands.json` manually, it's better to generate it. (Usually I recommend using [bear](https://github.com/rizsotto/Bear) but as I think it may not work on Windows, you could try [compiledb](https://github.com/nickdiego/compiledb) instead.)

**Comment by iceypotato** [comment]
Yep, still no luck. I tried using compiledb, ran the `compiledb make` command and the outcome was still the same. It generated some stuff inside the `compile_commands.json` file, but it still could not find `bits/c++config.h`.

**Comment by HighCommander4** [comment]
Please show new clangd logs with the generated `compile_commands.json`.

**Comment by iceypotato** [comment]
[clangd.verbose.log](https://github.com/clangd/vscode-clangd/files/9792996/clangd.verbose.log)

I did some testing in a VM so the directories have changed.
`compile_commands.json`:
```
[
 {
  "directory": "C:\\Users\\myuser\\Documents\\Test",
  "arguments": [
   "g++",
   "-c",
   "-o",
   "testlib.o",
   "testlib.cpp"
  ],
  "file": "testlib.cpp"
 }
]
```

**Comment by HighCommander4** [comment]
The logs are showing that:

1. `--query-driver` is now working, based on the following:

> I[13:10:41.424] System includes extractor: successfully executed C:\Users\myuser\Documents\x86_64-12.2.0-release-posix-seh-rt_v10-rev0\mingw64\bin\g++.exe

2. There are no diagnostics issued when you open `testlib.cpp`.

There _are_ diagnostics issued when you open `<iostream>`, the reason for that is:

> I[13:10:41.362] Failed to find compilation database for c:\Users\myuser\Documents\x86_64-12.2.0-release-posix-seh-rt_v10-rev0\mingw64\lib\gcc\x86_64-w64-mingw32\12.2.0\include\c++\iostream

this can be fixed using https://clangd.llvm.org/faq#how-do-i-fix-errors-i-get-when-opening-headers-outside-of-my-project-directory.

**Comment by iceypotato** [comment]
Thanks, it was fixed. I also had to add the compilers to my user path also. My question is, is there no other way to do it without a `compiler_commands.json`? Like, is there a way to do this with the clang user config file (`.clangd`, `clangd.yaml`)?

**Comment by HighCommander4** [comment]
Once https://github.com/clangd/clangd/issues/1089 is fixed, it should be enough to add:

```
CompileFlags:
  Compiler: /path/to/g++
```

to the clangd config file (and `--query-driver=/path/to/g++` to the clangd command line), and `compile_commands.json` will not be required.
