### ISSUE TITLE
Inlay Hint does not work on M1 macOS

### ISSUE THREAD

**Issue by BIKA-C** [clangd/vscode-clangd#395]
The inlay hint feature has no use. I have tried to add `—inlay-hint` argument to clangd, and configured the `.clangd` file to enable inlay hint as well. The vscode setting is definitely on. I have the same setting on a linux machine, running clangd 14, and it works fine.

**Logs**
```
I[21:41:38.642] LSP finished, exiting with status 0
The flag `-inlay-hints` is obsolete and ignored.
I[21:41:38.650] clangd version 15.0.1 (https://github.com/llvm/llvm-project b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf)
I[21:41:38.650] Features: mac+grpc+xpc
I[21:41:38.650] PID: 37491
I[21:41:38.651] Working directory: <wd>
I[21:41:38.651] argv[0]: <clangd>
I[21:41:38.651] argv[1]: --enable-config
I[21:41:38.651] argv[2]: --inlay-hints
I[21:41:38.651] argv[3]: --log=info
I[21:41:38.651] argv[4]: --header-insertion-decorators
I[21:41:38.651] argv[5]: --header-insertion=iwyu
I[21:41:38.651] argv[6]: --clang-tidy
I[21:41:38.651] Starting LSP over stdin/stdout
I[21:41:38.651] <-- initialize(0)
I[21:41:38.668] --> reply:initialize(0) 17 ms
I[21:41:38.669] <-- initialized
I[21:41:38.670] <-- textDocument/didOpen
I[21:41:38.671] --> textDocument/publishDiagnostics
I[21:41:38.671] --> textDocument/publishDiagnostics
I[21:41:38.671] Failed to find compilation database for <path to my file>
I[21:41:38.671] ASTWorker building file <path to myfile> version 3 with command clangd fallback
[<wd>]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang "-resource-dir=<clangd lib>" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk — "<path to my file>"
I[21:41:38.672] --> textDocument/clangd.fileStatus
I[21:41:38.674] <-- textDocument/documentSymbol(1)
I[21:41:38.674] <-- textDocument/documentSymbol(2)
I[21:41:38.674] <-- textDocument/codeAction(3)
I[21:41:38.675] <-- textDocument/documentLink(4)
I[21:41:38.676] <-- textDocument/inlayHint(5)
I[21:41:38.721] --> workspace/semanticTokens/refresh(0)
I[21:41:38.721] --> textDocument/clangd.fileStatus
I[21:41:38.722] <-- reply(0)
I[21:41:38.725] --> textDocument/publishDiagnostics
I[21:41:38.725] --> reply:textDocument/documentSymbol(1) 50 ms
I[21:41:38.725] --> reply:textDocument/documentSymbol(2) 50 ms
I[21:41:38.725] --> reply:textDocument/codeAction(3) 50 ms
I[21:41:38.725] --> reply:textDocument/documentLink(4) 50 ms
I[21:41:38.725] --> reply:textDocument/inlayHint(5) 48 ms
I[21:41:38.725] --> textDocument/clangd.fileStatus
I[21:41:38.725] <-- textDocument/semanticTokens/full(6)
I[21:41:38.726] --> reply:textDocument/semanticTokens/full(6) 0 ms
I[21:41:38.726] --> textDocument/clangd.fileStatus
```

**System information**
Clangd version:
```
clangd version 15.0.1 (https://github.com/llvm/llvm-project b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf)
Features: mac+grpc+xpc
Platform: x86_64-apple-darwin21.6.0
```
clangd extension version: Latest `v0.1.22`
Operating system: macOS 12.6

**Comment by sam-mccall** [comment]
Hi, can you provide more details? The file contents (ideally a self-contained example with no `#includes) and the full log with `-log=verbose`?

Without these details it's not possible for anyone without a Mac to work on this bug.

**Comment by BIKA-C** [comment]
Sorry about that, here is verbose log and a self contained example:

### Log
```log
I[01:20:12.477] <-- shutdown(8)
I[01:20:12.477] --> reply:shutdown(8) 0 ms
I[01:20:12.482] <-- exit
I[01:20:12.482] LSP finished, exiting with status 0
The flag `-inlay-hints` is obsolete and ignored.
I[01:20:12.489] clangd version 15.0.1 (https://github.com/llvm/llvm-project b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf)
I[01:20:12.490] Features: mac+grpc+xpc
I[01:20:12.490] PID: 54101
I[01:20:12.490] Working directory: <wd>
I[01:20:12.490] argv[0]: clangd
I[01:20:12.490] argv[1]: --inlay-hints
I[01:20:12.490] argv[2]: --log=verbose
I[01:20:12.490] argv[3]: --header-insertion-decorators
I[01:20:12.490] argv[4]: --fallback-style=webkit
I[01:20:12.490] argv[5]: --header-insertion=iwyu
I[01:20:12.490] argv[6]: --clang-tidy
I[01:20:12.490] Starting LSP over stdin/stdout
I[01:20:12.490] <-- initialize(0)
I[01:20:12.507] --> reply:initialize(0) 17 ms
I[01:20:12.508] <-- initialized
I[01:20:12.509] <-- textDocument/didOpen
I[01:20:12.509] <-- textDocument/didOpen
I[01:20:12.510] --> textDocument/publishDiagnostics
I[01:20:12.510] Loaded compilation database from <wd>/build/compile_commands.json
I[01:20:12.510] --> window/workDoneProgress/create(0)
I[01:20:12.510] ASTWorker building file <sample.c> version 84 with command inferred from <another.c>
[<wd>/build]
/usr/bin/clang -g -arch arm64 -isysroot <clangd lib>" — "<sample.c>"
I[01:20:12.510] ASTWorker building file <another.c> version 29 with command 
[<wd>/build]
/usr/bin/clang -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -o CMakeFiles/<another.o> -c "-resource-dir=<clangd lib>" — "<another.c>"
I[01:20:12.510] Enqueueing 1 commands for indexing
I[01:20:12.511] <-- reply(0)
I[01:20:12.511] --> $/progress
I[01:20:12.511] --> $/progress
I[01:20:12.511] --> textDocument/clangd.fileStatus
I[01:20:12.511] --> textDocument/clangd.fileStatus
I[01:20:12.513] <-- textDocument/documentSymbol(1)
I[01:20:12.513] <-- textDocument/documentSymbol(2)
I[01:20:12.515] <-- textDocument/documentLink(3)
I[01:20:12.516] <-- textDocument/inlayHint(4)
I[01:20:12.523] --> workspace/semanticTokens/refresh(1)
I[01:20:12.523] --> textDocument/clangd.fileStatus
I[01:20:12.523] --> textDocument/clangd.fileStatus
I[01:20:12.523] <-- reply(1)
I[01:20:12.528] --> textDocument/publishDiagnostics
I[01:20:12.528] --> reply:textDocument/documentSymbol(1) 14 ms
I[01:20:12.528] --> reply:textDocument/documentSymbol(2) 14 ms
I[01:20:12.528] --> reply:textDocument/documentLink(3) 13 ms
I[01:20:12.528] --> reply:textDocument/inlayHint(4) 11 ms
I[01:20:12.528] --> textDocument/clangd.fileStatus
I[01:20:12.529] <-- textDocument/semanticTokens/full(5)
I[01:20:12.529] <-- textDocument/semanticTokens/full(6)
I[01:20:12.529] --> reply:textDocument/semanticTokens/full(6) 0 ms
I[01:20:12.529] --> $/progress
I[01:20:12.529] --> textDocument/clangd.fileStatus
I[01:20:12.529] --> $/progress
I[01:20:12.583] --> workspace/semanticTokens/refresh(2)
I[01:20:12.583] --> textDocument/clangd.fileStatus
I[01:20:12.590] <-- reply(2)
I[01:20:12.590] --> textDocument/publishDiagnostics
I[01:20:12.590] --> reply:textDocument/semanticTokens/full(5) 61 ms
I[01:20:12.590] --> textDocument/clangd.fileStatus
I[01:20:12.594] <-- textDocument/semanticTokens/full/delta(7)
I[01:20:12.595] --> reply:textDocument/semanticTokens/full/delta(7) 0 ms
I[01:20:12.595] --> textDocument/clangd.fileStatus
```

### sample.c
```c
void f(int a, int b) {}

int main()
{
	f(1, 2);
}
```

### Screenshot of the symptom (no inlay hint):
<img width="597" alt="image" src="https://user-images.githubusercontent.com/50717946/196127567-3a2de01b-878d-4eab-89f6-73356ab8f879.png">

**Comment by sam-mccall** [comment]
Thanks, this is really strange:

> `I[01:20:12.490] argv[2]: --log=verbose`

and yet the log is not verbose (all lines begin with `I`, no LSP messages are included). Not really sure what to suggest, I've never seen this symptom before.

Trying the same example in 15.0.1 on a non-M1 mac seems to work fine. Will try to find someone with an M1...

**Comment by fannheyward** [comment]
I'm using clangd 15 on M1, inlay hints works as expected.

```
❯ /Users/fannheyward/bin/clangd --version
clangd version 15.0.1 (https://github.com/llvm/llvm-project b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf)
Features: mac+grpc+xpc
Platform: x86_64-apple-darwin21.6.0

❯ file /Users/fannheyward/bin/clangd
/Users/fannheyward/bin/clangd: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64Mach-O 64-bit executable x86_64] [arm64]
/Users/fannheyward/bin/clangd (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Users/fannheyward/bin/clangd (for architecture arm64):	Mach-O 64-bit executable arm64
```

clangd's inlay hint on VSCode:

<img width="440" alt="截屏2022-10-18 10 45 27" src="https://user-images.githubusercontent.com/345274/196323699-aafc2667-965d-47be-a6bf-054c2e0eff7c.png">

clangd + vim + coc-clangd:

<img width="545" alt="截屏2022-10-18 10 45 07" src="https://user-images.githubusercontent.com/345274/196323630-ae8ee169-bb15-4aac-8b33-21b8f7cab0bc.png">

**Comment by BIKA-C** [comment]
Do you mind to share the config file for clangd in `settings.jsom`? Here is mine:
```json
"clangd.fallbackFlags": [],
"clangd.serverCompletionRanking": true,
"clangd.arguments": [
        "--inlay-hints",
        "--log=verbose",
        "--header-insertion-decorators",
        "--fallback-style=webkit",
        "--header-insertion=iwyu",
        "--clang-tidy",
],
```

The inlay hints works fine on my linux machine out of box with this exact same config, since I am using the ssh extension. I am really confused. What did I miss?  I tried to directly use the one downloaded from clangd extension
<img width="1910" alt="image" src="https://user-images.githubusercontent.com/50717946/196325750-65c05f82-c1d9-467d-92c6-dc6877a8a54d.png">

**Comment by fannheyward** [comment]
Only `"clangd.path" : "/Users/fannheyward/bin/clangd"` to custom clangd bin.

```
I[11:04:40.069] clangd version 15.0.1 (https://github.com/llvm/llvm-project b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf)
I[11:04:40.070] Features: mac+grpc+xpc
I[11:04:40.070] PID: 66102
I[11:04:40.070] Working directory: /Users/fannheyward/src/redis-stable
I[11:04:40.070] argv[0]: /Users/fannheyward/bin/clangd
I[11:04:40.070] Starting LSP over stdin/stdout
```

```
❯ ps aux | grep clangd
fannheyward      66127   0.0  0.0 408637584   1808 s002  S+   11:05AM   0:00.00 grep --color clangd
fannheyward      66102   0.0  0.4 409244352  75280   ??  S    11:04AM   0:00.47 /Users/fannheyward/bin/clangd
```

**Comment by BIKA-C** [comment]
This is not fair for me :(
Removing all the arguments does not help
Any suggestion for what might be the issue? Plz, I appreciate that!

**Comment by BIKA-C** [comment]
Alright, after some investigation, I fixed the problem by removing my user level config. I found 2 bugs:
 
1. when the argument `—inlay-hints` is passed to clangd, `-log=verbose` becomes `-log-info` with no warning other than `The flag `-inlay-hints` is obsolete and ignored.`
2. When both user level config (on macOS `$HOME/Library/Preferences/clangd/config.yaml` and project level `.clangd` are defined, clangd extension does not respect to the project level one. It gets ignored. I tested this by setting `InlayHints.Enabled: No` in `config.yaml` and `InlayHints.Enabled: Yes` in `.clangd` in project root folder. And under this configuration, inlay hint is disabled.

**Comment by fannheyward** [comment]
> I fixed the problem by removing my user level config

Close for now.

**Comment by HighCommander4** [comment]
>     1. when the argument `—inlay-hints` is passed to clangd, the argument`-log=<error|verbose>` has no effect and it becomes to the default`-log=info` with no warning other than `The flag '-inlay-hints' is obsolete and ignored.` Ref:
>        (logs start with V are disappeared, as I presented above):
>        > Thanks, this is really strange:
>        > > `I[01:20:12.490] argv[2]: --log=verbose`
>        > 
>        > 
>        > and yet the log is not verbose (all lines begin with `I`, no LSP messages are included). Not really sure what to suggest, I've never seen this symptom before.

I can reproduce this. I believe what's happening is that the `--inlay-hints` option expects an argument (e.g. `--inlay-hints=true`), and consumes the next token in the command line, which is `--log=verbose`, as its argument. Normally it would complain about that not being a valid argument, but since the option is obsolete, I guess the usual validation on the argument isn't performed, or the error it produces is swallowed in favour of the obsoletion warning.

>     2. When both the user level config (on macOS `$HOME/Library/Preferences/clangd/config.yaml` and project level `.clangd` are defined, clangd extension does not respect to the project level one. It gets ignored (or at least for the inlayHints opotion). I tested this by setting `InlayHints.Enabled: No` in `config.yaml` and `InlayHints.Enabled: Yes` in `.clangd` in project root folder. And under this configuration, inlay hint is disabled.

This user config taking precedence over the project config is deliberate, though there are use cases for having it either way; see https://github.com/clangd/clangd/discussions/1193 for some discussion.
