### ISSUE TITLE
Support variable substitutions like ${workplaceFolder} in clangd settings

### ISSUE THREAD

**Issue by sbrocket** [clangd/vscode-clangd#40]
It would be handy if settings like clangd.path supported variable substitutions like ${workplaceFolder}, rather than needing the full absolute path to be written out explicitly

**Comment by sam-mccall** [comment]
I think we already do: https://github.com/clangd/vscode-clangd/commit/6f66a43d80427becc3560418b0b203dfaf09d1ee

Is this not working, or just missing docs?

**Comment by Trass3r** [comment]
When used with CMake `"clangd.arguments": [ "--compile-commands-dir=${command:cmake.launchTargetDirectory}" ]` would be desirable.
https://github.com/microsoft/vscode-cmake-tools/issues/654

**Comment by sbrocket** [comment]
You're correct Sam, I must have incorrectly diagnosed my issue as being related to this.
