### ISSUE TITLE
Failed to start and restart clangd

### ISSUE THREAD

**Issue by fonqL** [clangd/vscode-clangd#406]
Please describe the problem.

![image](https://user-images.githubusercontent.com/75968297/198311354-1cfaa127-3a07-41a9-a2f5-f8be5abb5798.png)

Simply translate: Command ... resulted in an error ...

But 0.1.22 works well.

**Logs**
No output

**System information**
Clangd version (from the log, or `clangd --version`): 
```
clangd version 14.0.3
Features: windows
Platform: x86_64-pc-windows-msvc
```
clangd extension version:
0.1.23

VScode version:
1.69.1

Operating system:
Win10

**Comment by HighCommander4** [comment]
When this happens, can you open Help --> Toggle Developer Tools, and copy what you see in the Console tab? Hopefully there is a stack trace there that gives more information about this error.

**Comment by fonqL** [comment]
[vscode-app-1667030779566.log](https://github.com/clangd/vscode-clangd/files/9893240/vscode-app-1667030779566.log)

Here are logs, but I can't find something related to clang(d)... Hope it will help you.

**Comment by fonqL** [comment]
After debugging the extension I find my previous config `clangd.path: D:\LLVM\bin\clangd` is regarded as an error, and it is solved by appending `.exe`.
A little weird...
This problem is related to @clangd/install 0.1.16. (When I modified @clangd/install dependency version to 0.1.4 it works well)
The location of the exception is here.
![image](https://user-images.githubusercontent.com/75968297/199916379-502d46e9-feda-4f01-9ed5-40c2f7fcfde5.png)

**Comment by HighCommander4** [comment]
Thanks, I can reproduce the original error now.

Steps to reproduce:

  1. Set `clangd.path` to an invalid path
  2. Close and restart vscode
       ==> At this point, on vscode startup, I get a dialog saying: "The clangd binary '`<path>`' was not found. Would you like to download and install clangd 15.0.3"?
  3. Close that dialog (without installing).
  4. Perform "clangd: Restart language server"

Now I get the error:

> Command 'clangd: Restart language server' resulted in an error (Cannot read properties of undefined (reading 'stop'))

The source of the error is the `this.client.stop()` call [here](https://github.com/clangd/vscode-clangd/blob/c0375489682e331ad06c25b60df86e4f102a6407/src/clangd-context.ts#L180). That code is triggered by 'clangd: Restart language server', and it expects `this.client` to be a valid object, but if clangd was not running to begin with, then it will be undefined.

This part is a vscode-clangd bug.

As for `D:\LLVM\bin\clangd` being an invalid path on Windows, I think that's a legitimate error. Since the filename does include the `.exe`, the value of `clangd.path` should as well. I understand it may have worked without the `.exe` before since some library facilities try to automatically add the `.exe`, it's probably not a good idea to rely on that.

Out of curiosity, do you not get the first dialog (from step 2) when starting vscode, which says "The clangd binary 'D:\LLVM\bin\clangd' was not found. Would you like to download and install clangd 15.0.3"?

**Comment by fonqL** [comment]
Yes, I havn't seen the dialog.

**Comment by HighCommander4** [comment]
> I can't find any code calling [promptInstall](https://github.com/clangd/vscode-clangd/blob/c0375489682e331ad06c25b60df86e4f102a6407/src/install.ts#L114).

The code is in [node-clangd](https://github.com/clangd/node-clangd/blob/2ccb3395391004aee1349df47f44be190289382e/src/index.ts#L141)

**Comment by fonqL** [comment]
I have tried my best but still have no idea.
It seems that the code after this [await](https://github.com/clangd/node-clangd/blob/2ccb3395391004aee1349df47f44be190289382e/src/index.ts#L139) doesn't get executed at all. When I click `next step` button in that line, in typescript it just returns to [here](https://github.com/clangd/vscode-clangd/blob/c0375489682e331ad06c25b60df86e4f102a6407/src/install.ts#L25), in javascript it jumps to the end of `__awaiter()`.
Debug console has no logs.
I can only guess:
1. The `status` has a `background` member which is a `Promise`.  After `await common.prepare` it seems to be ignored, and its status is `pending`, though I don't know what it means. I try to `await` or `.then/.catch` but none of these works.
2. Network problems when accessing github cause some strange problems. But it seems never timeout or throw something.

**Comment by fonqL** [comment]
Ok I finally figured it out. it's a network and timeout problem. My vscode can't access github smoothly because of unknown reasons, and there is also no timeout parameter set in [latestRelease](https://github.com/clangd/node-clangd/blob/2ccb3395391004aee1349df47f44be190289382e/src/index.ts#L167) function which is called by `recover` function.
I think you can reproduce by disconnecting the internet.

**Comment by HighCommander4** [comment]
> Ok I finally figured it out. It's a network and timeout problem. My vscode can't access github smoothly because of unknown reasons, and there is also no timeout parameter set in [latestRelease](https://github.com/clangd/node-clangd/blob/2ccb3395391004aee1349df47f44be190289382e/src/index.ts#L167) function which is called by `recover` function. I think you can reproduce by disconnecting the internet.

Thanks for investigating! That sounds like a second bug that we should fix in node-clangd.

**Comment by HighCommander4** [comment]
(I'm going to reopen this issue and use it to track fixes for the two vscode-clangd/node-clangd bugs we have identified.)

**Comment by HighCommander4** [comment]
Fix for the first issue: https://github.com/clangd/vscode-clangd/pull/461

**Comment by HighCommander4** [comment]
Fix for the second issue: https://github.com/clangd/node-clangd/pull/23

(Though I could not reproduce the hang locally -- if I disconnect my internet then the `fetch()` fails immediately. That said, I'm fairly confident that adding a timeout here should address the hang.)

**Comment by fonqL** [comment]
It works, thanks a lot!

> (Though I could not reproduce the hang locally -- if I disconnect my internet then the fetch() fails immediately. That said, I'm fairly confident that adding a timeout here should address the hang.)

I just found out that it is related to my network proxy.
