### ISSUE TITLE
Some tokens are missing `readonly` modifier

### ISSUE THREAD

**Issue by alexfrasson** [clangd/vscode-clangd#412]
It seems that in certain situations tokens are not being assigned the `readonly` modifier. The behavior can be verified with the following example where the variables `foo`, `print` and `value` were not tagged as readonly even though they are constants. Tokens can be inspected with `Developer: Inspect Editor Tokens and Scopes`. My assumption is that all constants should be assigned the flag. Feel free to close the issue in case that is not the intended behavior.

```cpp
template <typename T>
class FooBar
{
    const T foo;    // modifiers: declaration classScope
    const int bar;  // modifiers: declaration readonly classScope
};

void Func()
{
    const auto print_readonly =  // modifiers: declaration readonly functionScope
        [](const auto& value /* modifiers: declaration functionScope */) { std::cout << value; };
    print_readonly(10);
}

template <typename T>
void Func()
{
    const auto print =  // modifiers: declaration functionScope
        [](const auto& value /* modifiers: declaration functionScope */) { std::cout << value; };
    print(10);
}
```
**System information**
Clangd version: clangd version 15.0.3
clangd extension version: v0.1.23
Operating system: Ubuntu 20.04.5 LTS

**Comment by HighCommander4** [comment]
This was recently fixed in https://github.com/clangd/clangd/issues/1222. The fix will be available in clangd 16.
