### ISSUE TITLE
Move inlay hints to mouse over pop up

### ISSUE THREAD

**Issue by jasonbeach** [clangd/vscode-clangd#413]
Note: we mostly implement features in the clangd language server, and rely on Microsoft's LSP client framework to expose these in VSCode. Features requiring a lot of VSCode-specific work are unlikely to be implemented.

I really like the inlay hints, however them being displayed all the time is a little obtrusive, and turning them on and off with the shortcut key (ctrl+shift+p -> toggle inlay hints) is a little annoying.  Trying to figure out if there's some middle ground and the best thing I could think of is to add it to the pop-up that appears when you hover your mouse over a function's argument:

![sketch1](https://user-images.githubusercontent.com/2664807/202737455-690e22cb-b05d-474d-9924-a5b0e5f4cf88.jpg)

Instead of just enabling / disabling, could their be display options like "inline" (current enabled behavior), "hover", "disable"?

**Comment by sam-mccall** [comment]
The UI for inlay hints is up to the editor.
VSCode offers on/off/onUnlessPressed/offUnlessPressed, you may want to look at the latter two options in VSCode settings.

If you want different UI, you will need to file a feature requesst against VSCode.
