### ISSUE TITLE
Cannot navigate to definition of member in header in files that are outside of compilation database and are alternatively indexed by clangd-indexer

### ISSUE THREAD

**Issue by ToBoMi** [clangd/vscode-clangd#415]
# In short
`Go to Definition` results in `No definition found for [...]` in a file that is outside the compilation database (`compile_commands.json`), but is indexed using `clangd-indexer`.

# Details
I have a project with sources that are build inside the project and pre built libraries that come in by a package manager and bring debug sources in separate folders with them.

```
- /build
   /**/somewhereHere/**/compile_commands.json
- /src
    ... hpp cpp files
- /externalSources
    *.a files
    - /debug
        hpp cpp files
.clangd
index.dex
```

I use a compilation database for background indexing and use an external index to index the library sources. (setup this by using `.clangd` config file)
**The indexed library sources are overall pretty good navigatable. So in general this approach seems to work for me.**

In these lib sources there are some class members that are defined/initialised directly in the header (.hpp file) like this:

```cpp
myType myClassVar {initvalue};
```
## What fails
These members are referenced in the implementation of a class method (.cpp file). When I try to navigate back to their definition in the header file it cannot be found.
This behavior applies to multiple members, that all share the property of beeing defined in the header and are referenced in the source.

## What works
There are also definitions of members in the header that belong to the main project, so they are in the `compile_commands.json`. For these sources the problematic navigation works. So it has to do with the external index.

## Investigation
In the index file (which is in YAML format) I can see that the member defined in the header has a declaration and a definition. Both point to the header file. That seems correct.
In the indexes references section there is an entry that shows a correct defintion location of the member.

## Additional information
I cannot share the project and I was unable to reproduce this in a minimum example project. In a minimal example the problematic navigation always worked.

**Logs**
When I use verbose logging and start the `Go to Definition` function this is the output of the

<details>
  <summary>clangd log (sensible information replaced with [...]</summary>
  
```
V[09:59:46.130] <<< {"id":15,"jsonrpc":"2.0","method":"textDocument/definition","params":{"position":{"character":10,"line":107},"textDocument":{"uri":"file:///c%3A/Users/[...]/swdev/[...]/debug/portable/WebSocket/MongooseTextWebSocket.cpp"}}}

I[09:59:46.130] <-- textDocument/definition(15)
V[09:59:46.132] ASTWorker running Definitions on version 3 of c:\Users\[...]\swdev\[...]\debug\portable\WebSocket\MongooseTextWebSocket.cpp
I[09:59:46.133] --> reply:textDocument/definition(15) 2 ms
V[09:59:46.133] >>> {"id":15,"jsonrpc":"2.0","result":[]}

I[09:59:46.133] --> textDocument/clangd.fileStatus
V[09:59:46.133] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///c:/Users/[...]/swdev/[...]/debug/portable/WebSocket/MongooseTextWebSocket.cpp"}}
```

</details>

**System information**
Clangd version (from the log, or `clangd --version`): clangd version 15.0.3 (https://github.com/llvm/llvm-project 4a2c05b05ed07f1f620e94f6524a8b4b2760a0b1)
clangd extension version: v0.1.23
Operating system: Windows 10
```clangd-indexer.exe --version
LLVM (http://llvm.org/):
  LLVM version 15.0.3
  Optimized build.
  Default target: x86_64-pc-windows-msvc
```

**Comment by ToBoMi** [comment]
>In the index file (which is in YAML format) I can see that the member defined in the header has a declaration and a definition. Both point to the header file. That seems correct.
In the indexes references section there is an entry that shows a correct defintion location of the member.

Because of this I start creating the issue here in `vscode-clangd`.

**Comment by HighCommander4** [comment]
Can the source file containing the reference resolve the inclusion of the header file?

That is, if you open an affected library source file which contains such a reference to a member, and scroll up to the top where the source file #includes the header file containing the class definition (presumably it contains such an #include), does go-to-definition on the #include work (take you to the header file)?

**Comment by ToBoMi** [comment]
Yeah I can navigate to the header by using the `Go to Definition` function on the corresponding header file name at the `#include` line. (Tested at two different locations in the code where the problem occurs)

Side note: I also can switch between header and source using clangd extension(`Alt-O`)

**The include line** in the source file of the header that holds the member definition **is marked with a red underline**. Inside the header there is one unresolved include. 

Can it be a clangd issue? The log shows that clangd returns nothing on vscode definition request:
>`V[09:59:46.133] >>> {"id":15,"jsonrpc":"2.0","result":[]}` in https://github.com/clangd/vscode-clangd/issues/415#issue-1463044218

**Comment by HighCommander4** [comment]
> **The include line** in the source file of the header that holds the member definition **is marked with a red underline**.

This is likely related to the problem, it indicates clangd doesn't know where to find the #include when processing the source file.

(I'm surprised that go-to-definition on the #include works even with the diagnostic present. I wonder if it's using some kind of heuristic fallback.)

I don't see how you can get around having a `compile_commands.json` containing entries for the library source files, with proper compiler flags including `-I` flags needed to compile the library source file. You may need to generate one yourself if you can't get one from the library's package.

**Comment by ToBoMi** [comment]
Te missing include is in the header file of the source file. clangd does not miss the header of the source file.
The error get somewhat propagated down the include hierarchy.

It might be a problem with the include. Though I think clangd has all the information needed to find the declaration.

Anyways, I ound out that copying just the two files to my minimal example project keeps the issue present.
I try to remove all sensible information from the files and see if the issue persists. That should be possible. So I hope I'll come up with a small test project soon.

**Comment by ToBoMi** [comment]
> I don't see how you can get around having a `compile_commands.json` containing entries for the library source files, with proper compiler flags including `-I` flags needed to compile the library source file. You may need to generate one yourself if you can't get one from the library's package.

I think I'll try this, too and follow the instructions from https://github.com/clangd/vscode-clangd/issues/38#issuecomment-639986094 for this.
Making the external index perfect might be much effort.

**Comment by ToBoMi** [comment]
I set up the libs with `compile_commands.json` files, put the libs together with their `compile_commands.json` in a workspace and that works pretty well.
Thanks for pointing me in that direction.
