### ISSUE TITLE
Enable autocomplete of function arguments after autocompleting a function

### ISSUE THREAD

**Issue by palapapa** [clangd/vscode-clangd#420]
Currently, after autocompleting a function and while entering the arguments, no autocomplete prompts show up. The "argument mode" where one can press tab to switch to the next argument must be exited before any autocomplete prompts show up for the arguments.

**Comment by HighCommander4** [comment]
This seems to work for me -- after accepting a completion proposal for a function, when the focus is on the first argument, I can type a partial argument name, press Ctrl+Enter to trigger completion for the argument name, accept a proposal, and then Tab does still take me to the next argument.

Maybe I'm not understanding the problem, or you can help clarify with a screen capture.

**Comment by palapapa** [comment]
@HighCommander4 Oh that works for me too. But it would be nice to have it appear automatically without having to press ctrl+enter.

**Comment by HighCommander4** [comment]
> But it would be nice to have it appear automatically without having to press ctrl+enter.

Ok, I see what you mean.

This activation behaviour is controlled by the vscode itself though. If I turn on the `"editor.quickSuggestions"` setting then I get code completion triggered immediately (without typing ctrl+enter) when typing the initial function name, but that indeed does not happen when typing an argument name ==> seems like a vscode bug, please consider filing at https://github.com/microsoft/vscode/issues.

**Comment by HEUBITLYJ** [comment]
i have meet the same problem， when the focus is on the first argument， no autocomplete prompts show up。 if i press Ctrl+Enter， it just create a new line and the focus is on the next line start. If I turn on the "editor.quickSuggestions" setting then I still cannot get code completion triggered immediately.

**Comment by HEUBITLYJ** [comment]
> i have meet the same problem， when the focus is on the first argument， no autocomplete prompts show up。 if i press Ctrl+Enter， it just create a new line and the focus is on the next line start. If I turn on the "editor.quickSuggestions" setting then I still cannot get code completion triggered immediately.

i solve this by disable `editor.suggest.snippetsPreventQuickSuggestions`

**Comment by HighCommander4** [comment]
I think we can close this, based on [this comment](https://github.com/microsoft/vscode/issues/169360#issuecomment-1354392689), the default vscode behaviour is the expected one, and disabling `editor.suggest.snippetsPreventQuickSuggestions` is indeed the suggested solution.
