### ISSUE TITLE
Function argument name added by the editor breaks vertical characters alignment

### ISSUE THREAD

**Issue by barsdeveloper** [clangd/vscode-clangd#421]
The argument name added by the extension does break monospace characters vertical alignment.
![Capture](https://user-images.githubusercontent.com/84736467/203296523-598c90d4-0a44-4c15-b65f-3a80f3b68709.JPG)
Check the first line: the editor adds the argument name (components:) but it does not leave a full width space after it. The second is fine, the added type does cover an integer number of monospace characters.

**Comment by sam-mccall** [comment]
This is a VSCode issue, we don't control over how these are rendered, we only provide the text.

**Comment by barsdeveloper** [comment]
That was my first guess but I've received the following reply
https://github.com/microsoft/vscode/issues/166947
