### ISSUE TITLE
Duplicate parameter names  shown in editor

### ISSUE THREAD

**Issue by BNieuwenhuizen** [clangd/vscode-clangd#422]
clangd has this feature where it shows the paremeter names of a function inline at the function call. I'm getting more and more duplicates of those names the longer the editor is up. Like this: https://drive.google.com/file/d/1pIEh1Kv_mBwktCrr_dcUUUXxE8raDORG/view?usp=sharing

(The code used to reproduce is available at https://gitlab.freedesktop.org/mesa/mesa/)

**Logs**
https://drive.google.com/file/d/18oRy7wDNBopC5t4CZP9V5uERLoCeBc7U/view?usp=sharing

**System information**
Clangd version (from the log, or `clangd --version`): 14.0.6
clangd extension version: v0.1.23
Operating system: Linux

**Comment by HighCommander4** [comment]
The duplicate parameters indicate that clangd is crashing repeatedly.

Based on the logs, the reason for the crash is https://github.com/clangd/clangd/issues/1216, which has been fixed in [clangd 15.0.6](https://github.com/clangd/clangd/releases/tag/15.0.6), upgrading to that version should resolve it.

**Comment by daniel-pg** [comment]
> the reason for the crash is [clangd/clangd#1216](https://github.com/clangd/clangd/issues/1216), which has been fixed in [clangd 15.0.6](https://github.com/clangd/clangd/releases/tag/15.0.6), upgrading to that version should resolve it

Unfortunately, some Linux distributions like Arch and Manjaro decided that they'd delay all updates to LLVM and Clang just because of a minor language called "zig". That means i'm stuck at Clang 14.0.6 .....

**Comment by kadircet** [comment]
you can always use clangd's unofficial [releases](https://github.com/clangd/clangd/releases)
