### ISSUE TITLE
'iostream' file not foundclang(pp_file_not_found)

### ISSUE THREAD

**Issue by ezoiljy** [clangd/vscode-clangd#425]
After I upgrade my system (ubuntu 22.04), it seems clangd cannot find standard libraries like `iostream`.

Minimum code:

```c++
#include <iostream>
int main() {
}
```

cmake file:

```cmake
cmake_minimum_required(VERSION 3.22)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

project(Test)

add_executable(main main.cc)
```

commands:

```shell
mkdir build
cmake ..
```

This will produce the `compile_commands.json`:

```
[
{
  "directory": "/home/hansljy/tmp/test/build",
  "command": "/usr/bin/c++    -o CMakeFiles/main.dir/main.cc.o -c /home/hansljy/tmp/test/main.cc",
  "file": "/home/hansljy/tmp/test/main.cc"
}
]
```

The compilation is correct, but vscode complains with red wavelines and the message above

**Comment by HighCommander4** [comment]
Likely https://github.com/clangd/clangd/issues/1394, please see workarounds in [this comment](https://github.com/clangd/clangd/issues/1394#issuecomment-1328676884#issuecomment-1328676884).

**Comment by ezoiljy** [comment]
Not working. I have gcc 11.3.0 installed on Ubuntu 22.04 so the first 2 options won't apply. This is my configuration (`~/.config/clangd/config.yaml`):

```yaml
CompileFlags:
  Add: --include-dir=/usr/include/c++/11
```

After I setup the above config, vscode stops complaining my `iostream` but it is not responding to my ctrl + click on the header file and it did not know what `std::` is, pretty annoying.

**Comment by ezoiljy** [comment]
Sorry, but the query driver way works. Thanks for the comment. But I was wondering how can I make this setting universal? I currently set the vscode config for clangd but I would like other code editor to be aware of the `--query-driver` option

**Comment by HighCommander4** [comment]
Currently, `--query-driver` can only be set as a command-line argument to clangd, which are specified in your editor's configuration.

The reasons for this are security-related; there's some relevant discussion at https://github.com/clangd/clangd/issues/539.
