### ISSUE TITLE
Support sizeof(class/struct) hover evaluation 

### ISSUE THREAD

**Issue by cacosub7** [clangd/vscode-clangd#427]
Does clangd have a feature that evaluating the sizeof(class/struct) result on hover？
![image](https://user-images.githubusercontent.com/46550268/209767290-ba6bd064-f819-4318-852b-c3cb0df36e9e.png)
(this is what vscode C/C++ extension shows)

**Comment by HighCommander4** [comment]
Please do not file issues in duplicate. Answered in https://github.com/clangd/clangd/discussions/1443.
