### ISSUE TITLE
Errors: Request textDocument/codeAction failed

### ISSUE THREAD

**Issue by linqingyao** [clangd/vscode-clangd#432]
I use clangd via the **compile_command.json** file generated by cmake.
```json
// compile_command.json
[
{
  "directory": "C:/Users/xxx/source/repos/CLANG/HelloWorld/build",
  "command": "C:\\Users\\xxx\\scoop\\apps\\mingw-winlibs-llvm-ucrt\\current\\bin\\clang++.exe  -Wall -fcolor-diagnostics -g -std=c++17 -o CMakeFiles\\HelloWorld.dir\\main.cpp.obj -c C:\\Users\\xxx\\source\\repos\\CLANG\\HelloWorld\\main.cpp",
  "file": "C:\\Users\\xxx\\source\\repos\\CLANG\\HelloWorld\\main.cpp"
}
]
```

File contents for testing:
```cpp
// main.cpp
#include <iostream>

int main(int argc, char **argv) {
  std::cout << "Hello,world!" << std::endl;

  return 1;
}
```

This is the relevant log information I checked:
```text
I[16:14:27.019] --> textDocument/clangd.fileStatus
V[16:14:27.019] >>> {
  "jsonrpc": "2.0",
  "method": "textDocument/clangd.fileStatus",
  "params": {
    "state": "idle",
    "uri": "file:///c:/Users/xxx/scoop/apps/mingw-winlibs-llvm-ucrt/12.2.0-15.0.6-10.0.0-r3/include/c%2B%2B/12.2.0/ostream"
  }
}

[Error - 16:14:27] Request textDocument/codeAction failed.
[object Object]
V[16:14:27.978] <<< {
  "id": 30,
  "jsonrpc": "2.0",
  "method": "textDocument/semanticTokens/full/delta",
  "params": {
    "previousResultId": "1",
    "textDocument": {
      "uri": "file:///c%3A/Users/xxx/scoop/apps/mingw-winlibs-llvm-ucrt/12.2.0-15.0.6-10.0.0-r3/include/c%2B%2B/12.2.0/ostream"
    }
  }
}

I[16:14:27.978] <-- textDocument/semanticTokens/full/delta(30)
V[16:14:27.980] ASTWorker running SemanticHighlights on version 1 of c:/Users/xxx/scoop/apps/mingw-winlibs-llvm-ucrt/12.2.0-15.0.6-10.0.0-r3/include/c++/12.2.0/ostream
I[16:14:27.985] --> reply:textDocument/semanticTokens/full/delta(30) 6 ms
V[16:14:27.985] >>> {
  "id": 30,
  "jsonrpc": "2.0",
  "result": {
    "edits": [],
    "resultId": "2"
  }
}

I[16:14:27.985] --> textDocument/clangd.fileStatus
V[16:14:27.985] >>> {
  "jsonrpc": "2.0",
  "method": "textDocument/clangd.fileStatus",
  "params": {
    "state": "idle",
    "uri": "file:///c:/Users/xxx/scoop/apps/mingw-winlibs-llvm-ucrt/12.2.0-15.0.6-10.0.0-r3/include/c%2B%2B/12.2.0/ostream"
  }
}
```

Related problem: https://github.com/clangd/vscode-clangd/issues/419#issuecomment-1331628085

**Comment by HighCommander4** [comment]
Hmm, it looks like that error might be printed by the client rather than clangd.

What client (editor) do you use?

**Comment by HighCommander4** [comment]
I see error messages like that printed in VSCode's Output view during my usage of clangd as well. However, they don't seem to interfere with any functionality, i.e. clangd is working well for me, so I think these messages might be normal?

Are you experiencing any issues with clangd functionality?

**Comment by linqingyao** [comment]
> Are you experiencing any issues with clangd functionality?

No.


> Hmm, it looks like that error might be printed by the client rather than clangd.

I think so, too, in other language servers (e.g. rust-ra).

**Comment by linqingyao** [comment]
I think I need to consult related questions in vscode.

**Comment by HighCommander4** [comment]
For me

```
[Error - 3:50:29 AM] Request textDocument/codeAction failed.
```

is usually preceded a few lines above by:

```
I[03:50:29.501] --> reply:textDocument/codeAction(1061) 8022 ms, error: Task was cancelled.
V[03:50:29.501] >>> {"error":{"code":-32800,"message":"Request cancelled"},"id":1061,"jsonrpc":"2.0"}
```

So I am thinking this is related to the fact that as you type, the client sends the same request multiple times (e.g. after each character), and if the server gets a newer request before completing the older request, it considers the older request to be stale and cancels it.

This makes me think this is likely expected behaviour.

**Comment by linqingyao** [comment]
> is usually preceded a few lines above by:
> 
> ```
> I[03:50:29.501] --> reply:textDocument/codeAction(1061) 8022 ms, error: Task was cancelled.
> V[03:50:29.501] >>> {"error":{"code":-32800,"message":"Request cancelled"},"id":1061,"jsonrpc":"2.0"}
> ```

Yes, I agree with you! I think I can close this issue now. Thank you very much for your help.
