### ISSUE TITLE
The code folding incorrectly when there is a 'goto' statement.

### ISSUE THREAD

**Issue by jay-zhou-yan** [clangd/vscode-clangd#439]
Type: <b>Bug</b>

Hello,

<img width="960" alt="codefolding" src="https://user-images.githubusercontent.com/40359079/212226347-18c1c5d8-87ef-4389-907b-a7e76b4cd5bf.png">

As the screenshot shows, the outermost "{" "}" of the function is expected when there is no goto statement in the function. However, when there is a goto statement in the function, the "{" at the top layer of the function is folded, and the "}" at the top layer is not in the area where the code is folded.

Extension version: 0.1.23
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (7.04GB free)|
|Process Argv|E:\\project\\debug_templete\\debug-windows --crash-reporter-id 548922f6-5112-4d86-b32f-3006cea6df33|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
3d0df643:30613357
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by HighCommander4** [comment]
Seems to be related to the labels being indented at the same level as the `{`. If the labels are indented further, they start to be included in the collapsed region.

**Comment by HighCommander4** [comment]
Oh, wait -- this is with vscode's client-side folding.

With the server side folding coming in clangd 16, it works correctly.
