### ISSUE TITLE
Call hierarchy: Show outgoing calls is empty and clangd shows error: -32601: method not found / Request callHierarchy/outgoingCalls failed

### ISSUE THREAD

**Issue by ToBoMi** [clangd/vscode-clangd#443]
Opening the call hierarchy of **outgoing calls** on a function (that calls other functions) the call hierarchy pane stays empty.

In the clangd log I can see the following entry:
```
I[08:23:07.501] <-- textDocument/prepareCallHierarchy(77)
I[08:23:07.502] --> reply:textDocument/prepareCallHierarchy(77) 1 ms
I[08:23:07.502] --> textDocument/clangd.fileStatus
I[08:23:07.764] <-- callHierarchy/outgoingCalls(78)
I[08:23:07.764] --> reply:callHierarchy/outgoingCalls(78) 0 ms, error: -32601: method not found
[Error - 08:23:07] Request callHierarchy/outgoingCalls failed.
[object Object]
```

Clangd is able to build a call hierarchy containing the method in question, by requesting the call hierarchy of incoming calls at a lower level. So the function should be known by clangd.

I cannot provide code - I'll prepare a minimal example if the issue is not reproducible.

**System information**
Clangd version (from the log, or `clangd --version`):
`clangd version 15.0.6 (https://github.com/llvm/llvm-project 088f33605d8a61ff519c580a71b1dd57d16a03f8)`
clangd extension version:
`v0.1.23`
Operating system:
`Windows 10`

**Comment by HighCommander4** [comment]
Outgoing calls is not currently supported by clangd. https://github.com/clangd/clangd/discussions/1206 is on file to discuss it (with additional discussion in https://github.com/clangd/clangd/issues/162)

**Comment by iamwwc** [comment]
`outgoing calls` is a key feature for source analysis

**Comment by HighCommander4** [comment]
> `outgoing calls` is a key feature for source analysis

You can follow the progress of the feature at https://github.com/clangd/clangd/discussions/1206 and https://reviews.llvm.org/D93829. I recently took over the patch implementing outgoing calls from its original author, and addressed the review comments on it.
