### ISSUE TITLE
Hints are often not being updated until build is manually triggered

### ISSUE THREAD

**Issue by Jendker** [clangd/vscode-clangd#444]
The issue is that the error hints are often not being updated until I manually trigger code build, what influences the coding experience. I have tested the configuration with clangd 15.0.6:
```
    "clangd.arguments": [
        "--compile-commands-dir=${fileWorkspaceFolder}/build",
        "--completion-style=detailed",
        "--background-index",
        "--header-insertion=never",
        "-pretty"
    ],
    "clangd.path": "/home/orbik/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/15.0.6/clangd_15.0.6/bin/clangd",
```
compile_commands.json
```
[
{
  "directory": "/home/orbik/repos/project/build/project",
  "command": "/usr/lib/ccache/c++  -DPACKAGE_VERSION=\\\"2.3.2+15+ga494fc3\\\" -DPACKAGE_VERSION_MAJOR=2 -DPACKAGE_VERSION_MINOR=3 -DPACKAGE_VERSION_PATCH=2 -DPCL_NO_PRECOMPILE -DPROJECT_VERSION=\\\"2.3.2\\\" -DPROJECT_VERSION_INT=20302 -DvtkRenderingContext2D_AUTOINIT=\"1(vtkRenderingContextOpenGL2)\"  -g   -msse2 -mpopcnt -msse4.2 -funroll-loops -Wall -c /home/orbik/repos/project/project/file.cc",
  "file": "/home/orbik/repos/project/project/file.cc"
},
...
]
```
and clangd 16.0.0 (unreleased), with and without `compile-commands-dir`:
```
    "clangd.arguments": [
        // "--compile-commands-dir=${fileWorkspaceFolder}/build",
        "--query-driver=/usr/lib/ccache/c++",
        "--completion-style=detailed",
        "--background-index",
        "--header-insertion=never",
        "-pretty"
    ],
    "clangd.path": "/home/orbik/Downloads/clangd-linux-snapshot_20230122/clangd_snapshot_20230122/bin/clangd",
```

clangd extension version: v0.1.23
Operating system: Ubuntu 20.04

**Comment by HighCommander4** [comment]
Maybe the errors are not actually being produced by clangd, but by another plugin that's getting them from the build output?

Do you have other plugins related to C++ or building installed?

Do you still see the errors if you disable the vscode-clangd plugin and restart vscode and do a build?

**Comment by Jendker** [comment]
You nailed it! That was Cmake Tools providing the errors... Huge oversight on my side but I am very thankful for your suggestion! You made my C++ coding experience in vscode 10x better :) No exaggeration.
