### ISSUE TITLE
Not check or update the include paths after configuration

### ISSUE THREAD

**Issue by traversebitree** [clangd/vscode-clangd#447]
## Breif
Not check or update the **include paths** after **configuration**.
Checking and Updating the include paths only after the **build** stage(it should be done after configuration).
And if I **reload** the window or workspace, also can check and update the include paths.

**CMake Code**:
```cmake
cmake_minimum_required(VERSION 3.25)
project(app)
set(CMAKE_EXPORT_COMPILE_COMMANDS TRUE)
enable_language(CXX)
set(CMAKE_CXX_STANDARD 23)
add_executable(main main.cpp)

target_include_directories(main PRIVATE header_folder)
```
**C++ Code**:
*header_folder\header.hpp*
```cpp
inline int add(int a, int b) { return a + b; };
```
*main.cpp*
```cpp
#include <header.hpp>

int main(int argc, char const *argv[]) {
  int c = add(5, 6);
  return c;
}
```

## Screenshots
![gif1](https://user-images.githubusercontent.com/30373236/215243023-94398fc8-7a9d-4490-b458-1bdc82f04bf5.gif)
![gif2](https://user-images.githubusercontent.com/30373236/215243048-093f06c8-5137-4cf8-88ce-b1e55fb96ad9.gif)
**_The include paths check should have done after configuration, but not, it done after build._**

## Log
**Logs**
```shell
[Error - 12:47:43] Request textDocument/documentSymbol failed.
[object Object]
[Error - 12:47:43] Request textDocument/semanticTokens/full failed.
[object Object]
[Error - 12:47:43] Request textDocument/inlayHint failed.
[object Object]
[Error - 12:47:43] Request textDocument/documentLink failed.
[object Object]
[Error - 12:47:43] Request textDocument/documentSymbol failed.
[object Object]
[Error - 12:54:57] Request textDocument/documentSymbol failed.
[object Object]
[Error - 12:54:57] Request textDocument/codeAction failed.
[object Object]
[Error - 12:57:18] Request textDocument/definition failed.
[object Object]
```
## System information
**System information**
Clangd version (from the log, or `clangd --version`): clangd_15.0.6
clangd extension version: v0.1.23
Operating system: Windows 11 22621.1194
CMake Tools Plugin version: from v1.11.26 to v1.13.43

**Comment by HighCommander4** [comment]
I believe what's happening is:

 * CMake does update the `compile_commands.json` during the configure step
 * Clangd does detect changes in `compile_commands.json` (this was implemented in https://github.com/clangd/clangd/issues/83)
 * However, files which are already open are not automatically reparsed when `compile_commands.json` changes (we have https://github.com/clangd/clangd/issues/909 open for this). Closing and reopening `main.cpp` (without restarting clangd or vscode altogether) should reflect the updated include paths.

**Comment by kadircet** [comment]
yes that's the case. we'll reparse all open files on a textdocument/didsave notification, but we don't have any logic to trigger parsing of open files when we pick a new compilation database. (you can also get a particular file re-parsed with any request, e.g. a simple hover)

we already have a broadcasting mechanism in place for communicating CDB discoveries, but unfortunately that logic also only triggers when user interacts with an already existing file.

so I don't see any clear way of doing this without listening for changes on compile_commands.json, independent of what's going on inside the editor.

**Comment by traversebitree** [comment]
Thank you very much! @HighCommander4 @kadircet
