### ISSUE TITLE
Cross compile don't find header file

### ISSUE THREAD

**Issue by Hyderman** [clangd/vscode-clangd#448]
Clangd don't find std headers file of arm-none-eabi-g++.
I saw on the clangd repo the --query-driver argument but is there a way like for the classic C++ extension to auto detect the headers files without command line ?

**Comment by HighCommander4** [comment]
You can specify command-line arguments for clangd such as `--query-driver` in vscode's settings, under `"clangd.arguments"`.

The reason for not doing `--query-driver` automatically is discussed in https://github.com/clangd/clangd/issues/539.

**Comment by Hyderman** [comment]
Thanks, it works perfectly.
