### ISSUE TITLE
Vscode clangd can not parse second level include file in external includes

### ISSUE THREAD

**Issue by xulongzhe** [clangd/vscode-clangd#453]
i have only one source file in 

${project}/src/test.cpp

it  just include a boost libary

```
#include <boost/thread/thread.hpp>
```

and one cmake file CMakeLists.txt

```
cmake_minimum_required(VERSION 3.4.1)
PROJECT(main)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -std=c++11 -gdwarf-2")
FILE(GLOB_RECURSE ALL_SOURCES "src/*.cpp")
add_executable(${PROJECT_NAME} ${ALL_SOURCES})
target_include_directoriess(${PROJECT_NAME} PUBLIC "E:/includes")
```

"E:/includes" contains all includes file of 3rd libary.

vscode can pase test.cpp, but if i enter boost/thread/thread.hpp from test.cpp， it can not found includes in thread.hpp (eg: 'boost/thread/thread_only.hpp' file not found)

if you copy “#include <boost/thread/thread_only.hpp>” includes to test.cpp, it can be found.

**System information**

E:\code\testinclude>clangd --version
clangd version 15.0.3 (https://github.com/llvm/llvm-project 4a2c05b05ed07f1f620e94f6524a8b4b2760a0b1)
Features: windows+grpc
Platform: x86_64-pc-windows-msvc

clangd extension version:  clangd-0.1.23
Operating system: Win10

**Comment by HighCommander4** [comment]
Please see https://clangd.llvm.org/faq#how-do-i-fix-errors-i-get-when-opening-headers-outside-of-my-project-directory

**Comment by xulongzhe** [comment]
ok thanks
