### ISSUE TITLE
Better include autocomplete?

### ISSUE THREAD

**Issue by H4M5TER** [clangd/vscode-clangd#46]
### Problem
I get autocompletion when I type dot.
In this way, if I want to change the letters, I should delete the dot first, with little inconvenience.
### Solution
For example, [Include Autocomplete](https://marketplace.visualstudio.com/items?itemName=ajshort.include-autocomplete) extension works in this way:
When I type "<", it starts detecting input and give autocompletion.

**Comment by H4M5TER** [comment]
I can't just go and use Include AutoComplete.
> The extension uses the same c_cpp_properties.json file as the Microsoft C++ Tools extension to configure the include directories to search.

It depends on cpptools and I don't think cpptools and clangd can be use together.
Also its autocompletion can't be triggered again after close.

**Comment by Trass3r** [comment]
Fixed in clangd 11: https://github.com/llvm/llvm-project/commit/032727f4f839a28ae449d2f38814857780c7453d

**Comment by hokein** [comment]
Closing it as it is fixed in clangd.
