### ISSUE TITLE
Clang-format executable path

### ISSUE THREAD

**Issue by BillDenton** [clangd/vscode-clangd#460]
Provide a setting to control the path to the clang-format executable path. This allows standardisation of clang-format between developers. We have clang-format wrapper that provides a standard version and passes the formatting options (which can vary by file ) to clang-format. In Microsoft VS Code C/C++ the setting "C_Cpp.clang_format_path" allows this to be changed. By setting this to our wrapper all the files are appropriately formatted with a managed version of clang-format. This tool is inside the development repo so is set to ${workspaceFolder}/<path>/<clang-format bat or shell file>.

**Comment by i-ky** [comment]
As far as I know, clangd uses clang-format as a library, so clang-format binary is not even involved, hence there is no "injection point" for your wrapper script.

Perhaps, you can standardize clangd binary across your team instead and ensure clang-format and clangd versions are in sync?

**Comment by HighCommander4** [comment]
> As far as I know, clangd uses clang-format as a library, so clang-format binary is not even involved

Indeed.

What you could do instead is to instruct VSCode to use a dedicated plugin which uses an external clang-format executable for formatting, rather than clangd.

For example, you could install https://marketplace.visualstudio.com/items?itemName=xaver.clang-format, and add something like this to vscode settings:

```
"[cpp]": {
  "editor.defaultFormatter": "xaver.clang-format"
  "clang-format.executable": "/path/to/your/desired/version/of/clang-format"
}
```

(note: that second setting, `"clang-format.executable"`, is provided by the formatter extension itself for configuring which clang-format executable to use; it may be different for other plugins)

**Comment by BillDenton** [comment]
@i-ky We don't use clang compiler, but some of the tools which are version managed. So it isn't possible to standardise the clang.
@HighCommander4 I've installed and tried it. Eventually, I got the extension to find the executable. I had to put the full Windows to the executable in the repo. This isn't portable between repo directories. The C/C++ extension understands "${workspaceFolder}" so each repo has the same setting. Anyway, it is a workaround so I'll close the defect.

**Comment by i-ky** [comment]
> @i-ky We don't use clang compiler, but some of the tools which are version managed. So it isn't possible to standardise the clang.

I didn't say anything about clang, I was talking about clang**d**. I believe you do use clang**d**, since you report issues for clang**d** extension.

> I had to put the full Windows to the executable in the repo. This isn't portable between repo directories. The C/C++ extension understands "${workspaceFolder}" so each repo has the same setting.

Consider reporting this issue to the maintainer(s) of `xaver.clang-format` that extension.
