### ISSUE TITLE
Show inactive macro block in dimmed color instead of comment color.

### ISSUE THREAD

**Issue by zhangyx1998** [clangd/vscode-clangd#469]
The current version of vscode-clangd will render inactive macro regions as comment. This feature makes it difficult to understand the code inside inactive macro regions. It also makes actual code indistinguishable from comments.

Is it possible to enable basic syntax highlighting (such as keywords, variables and comments) work inside inactive macro blocks?

Below is the comparison between official C/C++ extension against vscode-clangd in rendering the same code.

| C/C++ Language Support | VSCode-Clangd |
|:-------------------------:|:----------------:|
| <img width="422" alt="Screenshot_1" src="https://user-images.githubusercontent.com/37485759/226205479-8889ae34-7304-42d2-a816-6083c1713c8f.png"> | <img width="422" alt="Screenshot_2" src="https://user-images.githubusercontent.com/37485759/226205513-531cdfea-71df-416b-a757-c2fc809a135e.png"> |

I am not sure whether this feature involves a lot of TS scripting, or could be simply achieved by flip of a toggle. I am happy to contribute if someone could give me some directions on where to look at.

**Comment by HighCommander4** [comment]
This is already implemented in https://github.com/clangd/vscode-clangd/pull/193, I'm just waiting for the patches to be reviewed.

(What I implemented is a gray background rather than decreased opacity, but it would be straightforward to implement the latter as an option as well.)
