### ISSUE TITLE
Go-to-definition for deduced type inlay hints

### ISSUE THREAD

**Issue by daveliddell** [clangd/vscode-clangd#471]
Can inlay hints for types be made to Ctrl+click through to their definitions?  The problem with "auto" variables is that there is no explicit type to click on.  Alternatively or additionally, types in the hover pop-up could be made clickable.

**Comment by HighCommander4** [comment]
This is being worked on in https://github.com/clangd/clangd/issues/1535.

Note that you can also perform go-to-definition on the `auto` token.

**Comment by daveliddell** [comment]
Awesome!  Thank you!
