### ISSUE TITLE
VS Code won't connect to source-kit.lsp

### ISSUE THREAD

**Issue by lewisl** [clangd/vscode-clangd#474]
I have installed clangd vscode extension.  clangd is installed as part of commandlinetools.  I have added a path to the lsp: ``` "sourcekit-lsp.serverPath" : "/usr/bin/sourcekit-lsp",``` which appears dimmed in settings.json--so it is not being used by any extension or by vscode itself.

I can run clangd from the command line successfully:
```
clangd
clangd is a language server that provides IDE-like features to editors.

It should be used via an editor plugin rather than invoked directly. For more information, see:
	https://clangd.llvm.org/
	https://microsoft.github.io/language-server-protocol/

clangd accepts flags on the commandline, and in the CLANGD_FLAGS environment variable.

I[00:13:39.000] Apple clangd version 14.0.3 (clang-1403.0.22.14.1)
I[00:13:39.001] Features: mac+xpc
I[00:13:39.001] PID: 6840
I[00:13:39.001] Working directory: /Users/lewis
I[00:13:39.001] argv[0]: /Library/Developer/CommandLineTools/usr/bin/clangd
I[00:13:39.002] Starting LSP over stdin/stdout
```

But, any time I try to use clangd features on a cpp file, here is the output:
```
[Error - 12:15:01 AM] The Clang Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 12:15:01 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:15:01 AM] Clang Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:15:01 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

I can't find any help or explanation anywhere.  The Microsoft c/c++ tools are not installed (none of them).  No other c linters are installed.

clangd version output:
```
clangd -version
Apple clangd version 14.0.3 (clang-1403.0.22.14.1)
Features: mac+xpc
Platform: x86_64-apple-darwin22.4.0; target=arm64-apple-darwin22.4.0
```

**System information**
Clangd version (from the log, or `clangd --version`):
clangd extension version:  
```
Published
7/12/2017, 06:06:17
Last released
10/23/2022, 06:17:28
Last updated
4/6/2023, 21:55:06
Identifier
llvm-vs-code-extensions.vscode-clangd
```
Operating system: MacOS Ventura 13.3

**Comment by HighCommander4** [comment]
Can you show logs after selecting clangd from the dropdown in the Output view?

**Comment by lewisl** [comment]
Here you go:
```
clangd: Unknown command line argument '-std=c++14'.  Try: '/Library/Developer/CommandLineTools/usr/bin/clangd --help'
clangd: Did you mean '--log=c++14'?
[Info  - 10:26:41 AM] Connection to server got closed. Server will restart.
[Error - 10:26:41 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 10:26:41 AM] Clang Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
clangd: Unknown command line argument '-std=c++14'.  Try: '/Library/Developer/CommandLineTools/usr/bin/clangd --help'
clangd: Did you mean '--log=c++14'?
[Info  - 10:26:41 AM] Connection to server got closed. Server will restart.
[Error - 10:26:41 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 10:26:41 AM] Clang Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
clangd: Unknown command line argument '-std=c++14'.  Try: '/Library/Developer/CommandLineTools/usr/bin/clangd --help'
clangd: Did you mean '--log=c++14'?
[Info  - 10:26:41 AM] Connection to server got closed. Server will restart.
[Error - 10:26:41 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 10:26:41 AM] Clang Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 10:26:41 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
clangd: Unknown command line argument '-std=c++14'.  Try: '/Library/Developer/CommandLineTools/usr/bin/clangd --help'
clangd: Did you mean '--log=c++14'?
[Info  - 10:26:41 AM] Connection to server got closed. Server will restart.
[Error - 10:26:41 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 10:26:41 AM] Clang Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 10:26:41 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
clangd: Unknown command line argument '-std=c++14'.  Try: '/Library/Developer/CommandLineTools/usr/bin/clangd --help'
clangd: Did you mean '--log=c++14'?
[Error - 10:26:41 AM] The Clang Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:26:41 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 10:26:41 AM] Clang Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 10:26:41 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097

```

From: Nathan Ridge ***@***.***>
Reply-To: clangd/vscode-clangd ***@***.***>
Date: Friday, April 7, 2023 at 12:39 AM
To: clangd/vscode-clangd ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [clangd/vscode-clangd] VS Code won't connect to source-kit.lsp (Issue #474)


Can you show logs after selecting clangd from the dropdown in the Output view?

**Comment by lewisl** [comment]
And here is c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "cppStandard": "c++14",
            "compileCommands": "/Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex/.vscode/compiler_commands.json",
            "compilerPath": "/usr/bin/clang",
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "cStandard": "c17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

And compile_commands.json:
```
[
{
  "directory": "/Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex",
  "arguments": ["/Library/Developer/CommandLineTools/usr/bin/clang", "-c", "-Qunused-arguments", "-target", "arm64-apple-macos13.1", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk", "-O2", "-std=c++14", "-o", "build/.objs/hex/macosx/arm64/release/src/hex.cpp.o", "src/hex.cpp"],
  "file": "src/hex.cpp"
}]

```

From: Nathan Ridge ***@***.***>
Reply-To: clangd/vscode-clangd ***@***.***>
Date: Friday, April 7, 2023 at 12:39 AM
To: clangd/vscode-clangd ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [clangd/vscode-clangd] VS Code won't connect to source-kit.lsp (Issue #474)


Can you show logs after selecting clangd from the dropdown in the Output view?

**Comment by lewisl** [comment]
So, after turning squiggles on, disabling and enabling the plug-in, it seems to work.

Here is the latest log:
```
I[11:09:51.822] Apple clangd version 14.0.3 (clang-1403.0.22.14.1)
I[11:09:51.823] Features: mac+xpc
I[11:09:51.823] PID: 11235
I[11:09:51.823] Working directory: /Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex
I[11:09:51.823] argv[0]: /Library/Developer/CommandLineTools/usr/bin/clangd
I[11:09:51.823] Starting LSP over stdin/stdout
I[11:09:51.823] <-- initialize(0)
I[11:09:51.828] --> reply:initialize(0) 5 ms
I[11:09:51.829] <-- initialized
I[11:09:51.832] <-- textDocument/didOpen
I[11:09:51.833] Failed to find compilation database for /Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex/src/hex.cpp
I[11:09:51.833] ASTWorker building file /Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex/src/hex.cpp version 1 with command clangd fallback
[/Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex/src]
/Library/Developer/CommandLineTools/usr/bin/clang -resource-dir=/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3 -- "/Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex/src/hex.cpp"
I[11:09:51.833] <-- textDocument/codeAction(1)
I[11:09:51.834] --> textDocument/clangd.fileStatus
I[11:09:51.837] <-- textDocument/documentLink(2)
I[11:09:51.840] <-- clangd/inlayHints(3)
I[11:09:52.186] --> workspace/semanticTokens/refresh(0)
I[11:09:52.186] --> textDocument/clangd.fileStatus
I[11:09:52.186] --> textDocument/clangd.fileStatus
I[11:09:52.187] <-- reply(0)
I[11:09:52.252] --> textDocument/publishDiagnostics
I[11:09:52.255] --> reply:textDocument/codeAction(1) 422 ms
I[11:09:52.255] --> reply:textDocument/documentLink(2) 418 ms
I[11:09:52.255] --> reply:clangd/inlayHints(3) 415 ms
I[11:09:52.255] --> textDocument/clangd.fileStatus
I[11:09:52.520] <-- textDocument/codeAction(4)
I[11:09:52.520] --> reply:textDocument/codeAction(4) 0 ms
I[11:09:52.520] --> textDocument/clangd.fileStatus
```


But, it is not picking up -std=c++14 so it is flagging lots of spurious errors.

Just seems the whole toolchain is rather fragile.

From: Nathan Ridge ***@***.***>
Reply-To: clangd/vscode-clangd ***@***.***>
Date: Friday, April 7, 2023 at 12:39 AM
To: clangd/vscode-clangd ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [clangd/vscode-clangd] VS Code won't connect to source-kit.lsp (Issue #474)


Can you show logs after selecting clangd from the dropdown in the Output view?

**Comment by lewisl** [comment]
It seems to work now.

I had to add a .clangd file in the src directory.

It looks like this:
```
CompileFlags:                     # Tweak the parse settings
  Add: [-std=c++14]
```
This duplicates entries in c_cpp_preferences.json and compile_commands.json both of which are in the .vscode directory: is this the right place.  Both of these files contain a setting selecting c++14, but both appear to be noops.

The inconvenience would be that I have to do this in every source directory because compile_commands.json, which my build tool nicely creates automatically is simply ignored.

Maybe fewer ways to do the same thing would be more reliable?  (Everyone can’t get their preference of TOML, YAML, json or where to put things: You are in charge! You tell us all what for!)

From: Nathan Ridge ***@***.***>
Reply-To: clangd/vscode-clangd ***@***.***>
Date: Friday, April 7, 2023 at 12:39 AM
To: clangd/vscode-clangd ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [clangd/vscode-clangd] VS Code won't connect to source-kit.lsp (Issue #474)


Can you show logs after selecting clangd from the dropdown in the Output view?

**Comment by lewisl** [comment]
Last message, I promise.

So, the problem with compile_commands.json is that clangd wants it to be in the src directory (or parent of the .cpp source file). Visual Studio Code, and it’s c++ linter plugin wants it to be in the .vscode project directory. So, all the make tool vendors do what Microsoft tells them to do.  Seems like clangd needs to search all of the directories of the project, not just the source directory.

When compile_commands.json is in the same directory as the source file, .clangd config file is not needed for setting language version (though it might be needed for other settings), as this is in compile_commands.json.

I’ll see if I can get my make tool to write this file in the same dir as the source file.

From: Nathan Ridge ***@***.***>
Reply-To: clangd/vscode-clangd ***@***.***>
Date: Friday, April 7, 2023 at 12:39 AM
To: clangd/vscode-clangd ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [clangd/vscode-clangd] VS Code won't connect to source-kit.lsp (Issue #474)


Can you show logs after selecting clangd from the dropdown in the Output view?

**Comment by HighCommander4** [comment]
Clangd's behaviour for where it looks for `compile_commands.json` is documented at https://clangd.llvm.org/installation#compile_commandsjson.

There is also the option of adding `--compile-commands-dir=<directory>` to `"clangd.arguments"` in vscode settings to point clangd to a different `<directory>` containing the file, so in this case you could point it at the `.vscode` directory.

**Comment by lewisl** [comment]
Thanks.

I had read the description of the directories that are searched.  The documentation example uses $SRC. In my reading it appeared that directory is the project directory despite being called “SRC” in the docs.  .vscode would typically be under the name of the project folder.  It seems like “build” is special and sort of hard-coded.  The docs say that $SRC/ is in the search list • wouldn’t this include child directories and the contained files, recursively?  Or does this statement only mean files that are IN $SRC—and thus, no deeper child directories?  I had assumed it was meant to be recursive.

Your suggestion is a good one because the .clangd file would rarely if ever have to be changed and I could setup VS Code to create the file in a project automatically.  The source file specific information would be generated by the make tool and would be specific to each source file used in the build of the project.



From: Nathan Ridge ***@***.***>
Reply-To: clangd/vscode-clangd ***@***.***>
Date: Friday, April 7, 2023 at 6:07 PM
To: clangd/vscode-clangd ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [clangd/vscode-clangd] VS Code won't connect to source-kit.lsp (Issue #474)


Clangd's behaviour for where it looks for compile_commands.json is documented at https://clangd.llvm.org/installation#compile_commandsjson.

There is also the option of adding --compile-commands-dir=<directory> to "clangd.arguments" in vscode settings to point clangd to a different <directory> containing the file, so in this case you could point it at the .vscode directory.

**Comment by lewisl** [comment]
You can mark this closed.

It turns out my build tool of choice has an extension for VSCode that enables the compile_commands.json file to be directed to any directory under the project.  So, I can put it in ${workspaceRoot}/build, which is one of the normal search paths.

From: Nathan Ridge ***@***.***>
Reply-To: clangd/vscode-clangd ***@***.***>
Date: Friday, April 7, 2023 at 6:07 PM
To: clangd/vscode-clangd ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [clangd/vscode-clangd] VS Code won't connect to source-kit.lsp (Issue #474)


Clangd's behaviour for where it looks for compile_commands.json is documented at https://clangd.llvm.org/installation#compile_commandsjson.

There is also the option of adding --compile-commands-dir=<directory> to "clangd.arguments" in vscode settings to point clangd to a different <directory> containing the file, so in this case you could point it at the .vscode directory.

**Comment by HighCommander4** [comment]
The search proceeds in the direction of ancestors, not descendants.

Quoting from the docs:

> if editing $SRC/gui/window.cpp, we search in $SRC/gui/, $SRC/gui/build/, $SRC/, $SRC/build/, …

We search the directory immediately containing the open file, in this case `$SRC/gui`, first, and then search proceeds to the next ancestor, in this case `$SRC`, and so on.

There are a couple of reasons for doing things this way:

 1. Clangd doesn't need to know which directory is "the workspace root". This helps keep clangd client-agnostic, because not all clients have a concept of a "workspace" (e.g. in vim you can just open a file directly).
 2. Subdirectories can have their own `compile_commands.json` files (useful if e.g. it's a third-party dependency with its own build system), and those take precedence over the top-level one (because they're closer ancestors of the files in that subdirectory).

(In addition, at each level a sibling named `build` is also searched as a convenience to handle the common case of a separate build directory named `build` containing the `compile_commands.json` without any additional configuration.)

**Comment by lewisl** [comment]
Very smart.

Directory references across all of the tools and doc we use are not always the same:  see .gitignore for example.  So, thanks for correcting how I got tripped up.

I have everything working easily now.

From: Nathan Ridge ***@***.***>
Reply-To: clangd/vscode-clangd ***@***.***>
Date: Friday, April 7, 2023 at 6:41 PM
To: clangd/vscode-clangd ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [clangd/vscode-clangd] VS Code won't connect to source-kit.lsp (Issue #474)


The search proceeds in the direction of ancestors, not descendants.

Quoting from the docs:

if editing $SRC/gui/window.cpp, we search in $SRC/gui/, $SRC/gui/build/, $SRC/, $SRC/build/, …

We search the directory immediately containing the open file, in this case $SRC/gui, first, and then search proceeds to the next ancestor, in this case $SRC, and so on.

There are a couple of reasons for doing things this way:
1.       Clangd doesn't need to know which directory is "the workspace root". This helps keep clangd client-agnostic, because not all clients have a concept of a "workspace" (e.g. in vim you can just open a file directly).
2.       Subdirectories can have their own compile_commands.json files (useful if e.g. it's a third-party dependency with its own build system), and those take precedence over the top-level one (because they're closer ancestors of the files in that subdirectory).

(In addition, at each level a sibling named build is also searched as a convenience to handle the common case of a separate build directory named build containing the compile_commands.json without any additional configuration.)
