### ISSUE TITLE
Formatting doesn't work.  Disregards indent settings.

### ISSUE THREAD

**Issue by lewisl** [clangd/vscode-clangd#475]
This whole thing is a mess of incompatibilities and conflicting settings.

There is no formatting provided by clangd.  If there is it will NOT use indent spacing of 4. I have wasted close to 10 hours on this. I cannot get anything to work with either the MS C/CPP extension or this clangd extension.   

Clearly there is a massive settings muddle between this extension, the Microsoft extension, and VS Code's settings in general.  As this is more relevant to the problem.

here you go:

**Logs**
Based on the log and formatting taking 0 ms, we can assume no formatting occurred.
```
I[17:34:58.030] --> textDocument/clangd.fileStatus
I[17:34:58.030] --> textDocument/clangd.fileStatus
I[17:34:58.050] --> textDocument/clangd.fileStatus
I[17:34:58.050] --> textDocument/clangd.fileStatus
I[17:37:35.697] <-- textDocument/codeAction(7)
I[17:37:35.697] --> reply:textDocument/codeAction(7) 0 ms
I[17:37:35.697] --> textDocument/clangd.fileStatus
```

**Logs**
Please attach the clangd log from the "Output" window if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`):
```
clangd --version
Apple clangd version 14.0.3 (clang-1403.0.22.14.1)
Features: mac+xpc
Platform: x86_64-apple-darwin22.4.0; target=arm64-apple-darwin22.4.0
```
clangd extension version:  v0.1.23
Operating system:  MacOS

I have attached the entire VS Code settings.js
[settings.txt](https://github.com/clangd/vscode-clangd/files/11245208/settings.txt)
on file (which is probably where the problem lies).  I have also attached my .clang-format file, which is in my home directory.  I want all my cpp code formatted the exact same way, not on a per project basis.  I have had to attach these as .txt because the powers that be at github (oh, that's Microsoft!) believe json could corrupt the world.
[settings.txt](https://github.com/clangd/vscode-clangd/files/11245204/settings.txt)
[clang-format.txt](https://github.com/clangd/vscode-clangd/files/11245209/clang-format.txt)

**Comment by HighCommander4** [comment]
A couple of questions:

 * How are you invoking formatting in vscode?
 * What is the path of the source file you're trying to format?

**Comment by lewisl** [comment]
Context menu click in the file and choose Format Document. Also, select a function, context menu and choose Format selection.

The path to the file is {project}/src and the file is open on the editor.

- Lewis

On Apr 16, 2023, at 6:34 PM, Nathan Ridge ***@***.***> wrote:

﻿

A couple of questions:

  *   How are you invoking formatting in vscode?
  *   What is the path of the source file you're trying to format?

**Comment by HighCommander4** [comment]
Is `{project}` somewhere in your home directory? I ask because `.clang-format` is searched by looking in the ancestor directories of the source file. So, `/home/user/.clang-format` will be found for `/home/user/projects/foo/src/a.cpp`, but not for say `/opt/projects/foo/src/a.cpp`.

**Comment by lewisl** [comment]
Yes, the project directory ultimately ends up going to the home directory.

Still, I think you might be onto the problem.

When I run clang-format from the command line and format the cpp file, it uses spacing of 4 and when using -i option, the file is formatted as I expect.

So, this makes clear that 1) the .clang-format file is found; 2) the formatting comes out just as I expect it to; so 3) the problem is with VS Code’s morass of settings.

Got any suggestions?  I was following most guidance I could find to make sure that ‘file’ was being used and that your extension was doing formatting and Microsoft’s extension was NOT being used for formatting (or linting and intellisense:  this setup works to use clangd).  But, I may easily have missed something in the big mess.

From: Nathan Ridge ***@***.***>
Reply-To: clangd/vscode-clangd ***@***.***>
Date: Sunday, April 16, 2023 at 8:13 PM
To: clangd/vscode-clangd ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [clangd/vscode-clangd] Formatting doesn't work. Disregards indent settings. (Issue #475)


Is {project} somewhere in your home directory? I ask because .clang-format is searched by looking in the ancestor directories of the source file. So, /home/user/.clang-format will be found for /home/user/projects/foo/src/a.cpp, but not for say /opt/projects/foo/src/a.cpp.

**Comment by HighCommander4** [comment]
Could you attach a complete set of clangd logs, starting from clangd startup, in a session where you open a file and try to perform formatting on it? I'd like to see whether the LSP messages show vscode actually asking clangd to perform formatting.

**Comment by lewisl** [comment]
Thanks for sticking with this.  You'll see below a log upon opening VS Code with the file open from previous session of the editor.  And then you can see a new formatting pass after I chose "Format Document" from the context menu.

I spared you about a dozen error runs.  At one level I apologize for the ranting because I ranted about the wrong thing. I did have the settings right for letting clangd do the formatting. On the other hand, there are deserved rantings. I saw no formatting happen because my .clang-format file contained many errors:  either invalid keys or invalid values for keys.

That's an easy place to end up. Since the documentation is rather voluminous, I used this command to generate the file: ```clang-format -style=llvm -dump-config > .clang-format```. Problem is that this example is riddled with errors.  Keys that don't exist or keys for json or javascript mixed up with keys for cpp.  Most of the keys that were flagged by errors in my file are shown in the documentation as being clang 16 or only applicable to other languages.  I am using 16.0.1 so I should have been ok.  But, no--the documentation seems to contain a fair bit of conjecture or wishes.

So, one by one I commented out the offending lines until it ran with no errors (which causes dropping back to llvm--which works--it's just not the formatting I wanted).  This would have been good documentation, but I did delete a few before I realized I should comment them out.

So, it works.  It's hard to set up.  The doc has more than a few errors, but stuff that's been around for many versions is apt to be correct. The command line auto-generation of a .clang-format _should_ be perfect: that's the way around the documentation--just create a perfect example, except it seems to be way out of sync with either the command line tool or the vs code extension. I should probably diff the variation from llvm to gnu to google etc., but I'll let someone else do that. I am close enough for now.

Here the log which shows formatting occuring successfully.  And the file is very close to what I want.  A few tweaks and I'll get it just so.

```
I[17:18:49.322] Apple clangd version 14.0.3 (clang-1403.0.22.14.1)
I[17:18:49.322] Features: mac+xpc
I[17:18:49.322] PID: 25556
I[17:18:49.323] Working directory: /Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex
I[17:18:49.323] argv[0]: /Library/Developer/CommandLineTools/usr/bin/clangd
I[17:18:49.323] Starting LSP over stdin/stdout
I[17:18:49.323] <-- initialize(0)
I[17:18:49.328] --> reply:initialize(0) 5 ms
I[17:18:49.329] <-- initialized
I[17:18:49.333] <-- textDocument/didOpen
I[17:18:49.334] Loaded compilation database from /Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex/build/compile_commands.json
I[17:18:49.334] ASTWorker building file /Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex/src/hex.cpp version 1 with command 
[/Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex]
/Library/Developer/CommandLineTools/usr/bin/clang -c -Qunused-arguments -target arm64-apple-macos13.3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -O2 -std=c++17 -o build/.objs/hex/macosx/arm64/release/src/hex.cpp.o -resource-dir=/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3 -- "/Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex/src/hex.cpp"
I[17:18:49.334] --> window/workDoneProgress/create(0)
I[17:18:49.334] Enqueueing 1 commands for indexing
I[17:18:49.334] <-- reply(0)
I[17:18:49.334] --> $/progress
I[17:18:49.334] --> $/progress
I[17:18:49.335] --> textDocument/clangd.fileStatus
I[17:18:49.455] <-- $/setTrace
I[17:18:49.455] unhandled notification $/setTrace
I[17:18:49.466] <-- textDocument/codeAction(1)
I[17:18:49.480] <-- textDocument/documentLink(2)
I[17:18:49.512] --> $/progress
I[17:18:49.512] --> $/progress
I[17:18:49.512] --> $/progress
I[17:18:49.857] --> workspace/semanticTokens/refresh(1)
I[17:18:49.892] <-- $/setTrace
I[17:18:49.892] unhandled notification $/setTrace
I[17:18:49.951] --> textDocument/publishDiagnostics
I[17:18:49.953] --> reply:textDocument/codeAction(1) 487 ms
I[17:18:49.953] --> reply:textDocument/documentLink(2) 472 ms
I[17:18:49.953] --> textDocument/clangd.fileStatus
I[17:18:49.972] <-- $/cancelRequest
I[17:18:49.972] <-- textDocument/codeAction(3)
I[17:18:49.972] <-- $/cancelRequest
I[17:18:49.972] --> reply:textDocument/codeAction(3) 0 ms
I[17:18:49.972] <-- textDocument/codeAction(4)
I[17:18:49.972] --> textDocument/clangd.fileStatus
I[17:18:49.972] <-- $/setTrace
I[17:18:49.972] unhandled notification $/setTrace
I[17:18:49.972] <-- $/setTrace
I[17:18:49.972] unhandled notification $/setTrace
I[17:18:49.972] --> reply:textDocument/codeAction(4) 0 ms
I[17:18:49.972] --> textDocument/clangd.fileStatus
I[17:18:49.991] <-- reply(1)
I[17:18:49.991] <-- textDocument/semanticTokens/full(5)
I[17:18:49.991] <-- $/cancelRequest
I[17:18:49.991] <-- textDocument/documentLink(6)
I[17:18:49.991] <-- $/cancelRequest
I[17:18:49.991] <-- textDocument/codeAction(7)
I[17:18:49.992] --> reply:textDocument/semanticTokens/full(5) 1 ms
I[17:18:50.017] --> reply:textDocument/documentLink(6) 25 ms
I[17:18:50.017] --> reply:textDocument/codeAction(7) 25 ms
I[17:18:50.017] --> textDocument/clangd.fileStatus
I[17:18:50.018] <-- $/setTrace
I[17:18:50.018] unhandled notification $/setTrace
I[17:18:50.628] <-- $/cancelRequest
I[17:18:50.628] <-- textDocument/documentLink(8)
I[17:18:50.628] --> reply:textDocument/documentLink(8) 0 ms
I[17:18:50.628] --> textDocument/clangd.fileStatus
I[17:18:50.675] <-- $/cancelRequest
I[17:18:50.689] <-- textDocument/documentLink(9)
I[17:18:50.689] --> reply:textDocument/documentLink(9) 0 ms
I[17:18:50.689] --> textDocument/clangd.fileStatus
I[17:18:50.923] <-- textDocument/codeAction(10)
I[17:18:50.923] --> reply:textDocument/codeAction(10) 0 ms
I[17:18:50.923] --> textDocument/clangd.fileStatus
I[17:18:51.249] Indexed src/hex.cpp (226 symbols, 22844 refs, 801 files)
I[17:18:51.379] --> $/progress
I[17:18:51.471] <-- textDocument/codeAction(11)
I[17:18:51.471] --> reply:textDocument/codeAction(11) 0 ms
I[17:18:51.471] --> textDocument/clangd.fileStatus
I[17:18:51.472] <-- textDocument/documentSymbol(12)
I[17:18:51.473] --> reply:textDocument/documentSymbol(12) 0 ms
I[17:18:51.473] --> textDocument/clangd.fileStatus
I[17:18:51.659] <-- textDocument/semanticTokens/full/delta(13)
I[17:18:51.660] --> reply:textDocument/semanticTokens/full/delta(13) 1 ms
I[17:18:51.660] --> textDocument/clangd.fileStatus
I[17:19:27.276] <-- textDocument/formatting(14)
I[17:19:27.307] --> reply:textDocument/formatting(14) 30 ms
I[17:19:27.315] <-- textDocument/didChange
I[17:19:27.315] --> textDocument/clangd.fileStatus
I[17:19:27.413] ASTWorker building file /Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex/src/hex.cpp version 2 with command 
[/Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex]
/Library/Developer/CommandLineTools/usr/bin/clang -c -Qunused-arguments -target arm64-apple-macos13.3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -O2 -std=c++17 -o build/.objs/hex/macosx/arm64/release/src/hex.cpp.o -resource-dir=/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3 -- "/Users/lewis/Dropbox/Online Coursework/UCSC C for Everyone/Course 4/hex/src/hex.cpp"
I[17:19:27.415] --> textDocument/clangd.fileStatus
I[17:19:27.415] --> textDocument/clangd.fileStatus
I[17:19:27.426] --> textDocument/clangd.fileStatus
I[17:19:27.508] --> textDocument/publishDiagnostics
I[17:19:27.510] --> textDocument/clangd.fileStatus
I[17:19:27.667] <-- textDocument/documentSymbol(15)
I[17:19:27.668] --> reply:textDocument/documentSymbol(15) 0 ms
I[17:19:27.668] --> textDocument/clangd.fileStatus
I[17:19:27.683] <-- textDocument/semanticTokens/full/delta(16)
I[17:19:27.685] --> reply:textDocument/semanticTokens/full/delta(16) 1 ms
I[17:19:27.685] --> textDocument/clangd.fileStatus
I[17:19:28.323] <-- textDocument/documentLink(17)
I[17:19:28.323] --> reply:textDocument/documentLink(17) 0 ms
I[17:19:28.323] --> textDocument/clangd.fileStatus
```

**Comment by HighCommander4** [comment]
Glad you figured it out!

I agree that we should try to surface errors about unrecognized keys better; we have https://github.com/clangd/vscode-clangd/issues/408 on file for it.

**Comment by ereisch** [comment]
I've stumbled across this as well; I was previously using the C/C++ pack for VSCode, and the formatting options that come along with that.  I had configured that extension to use clang-format, and specified all the format settings correctly in the Clang-format_style config option.  All was well in the world.  However, I had issues with the built-in code analyzer, and wanted to use clangd for that.  Unfortunately though, when you install the clangd extension, it hijacks your code formatter, and insists on using clangd for _everything_.  This also means that there's no way of setting the preferred format style other than .clang-format files.

In my situation, I have many working folders, and don't want to carry around .clang-format files in all of them.  I tried switching back to using the C/C++ extension as a provider for formatting, but that ability seems somehow lost since I installed the clangd extension (right-click in source file, "Format Using..." shows clangd as the only option).

So I think there are a couple different bugs here:

- The clangd extension steals the formatting rights from any other providers that may have previously been installed/enabled, with no clearly evident way to restore those providers and/or use them instead of clangd
- When using clangd as a formatting provider, there's no way to specify a fallback style if no .clang-format file was found (as you are able to easily do in the C/C++ extension format provider)
- Clangd's global settings don't seem to provide an option to specify a global clang format setting in ~/.config/clangd/config.yaml

**Comment by HighCommander4** [comment]
>    * The clangd extension steals the formatting rights from any other providers that may have previously been installed/enabled, with no clearly evident way to restore those providers and/or use them instead of clangd

The "stealing" part is outside of vscode-clangd's control, it's a behaviour of vscode itself: if multiple extensions provide a formatter for a particular language, it seems the most recently installed one "wins".

You can however make an explicit choice using the `"editor.defaultFormatter"` setting in your vscode settings (which can also be scoped to a language).

>    * When using clangd as a formatting provider, there's no way to specify a fallback style if no .clang-format file was found (as you are able to easily do in the C/C++ extension format provider)

Clangd supports a `--fallback-style=<style>` command-line argument, which can be specified via `"clangd.arguments"` in vscode settings.

Another technique some users employ is to place a `.clang-format` file in an ancestor directory of all your projects (for example, on Linux systems, in `/home/<username>/.clang-format`). Clangd will search for a `.clang-format` in all ancestor directories of the file being opened, so a `.clang-format` in your home (or other sufficiently high ancestor) directory will serve as a fallback for projects that don't have their own `.clang-format`.

>    * Clangd's global settings don't seem to provide an option to specify a global clang format setting in ~/.config/clangd/config.yaml

This is mostly an artifact of `--fallback-style=<style>` pre-dating the introduction of `config.yaml`, and not wanting to duplicate the setting in two places.
