### ISSUE TITLE
Support clang-format 16

### ISSUE THREAD

**Issue by jczhang07** [clangd/vscode-clangd#477]
I don't know how to check the current clang-format version with clangd.
But I did find clangd reported errors with the `.clang-format` file in our project which someone used syntax from  clang-format version 16.

```
AlignTrailingComments:
  Kind: Always
  OverEmptyLines: 0
```

**Comment by HighCommander4** [comment]
clangd does not use an external clang-format, it links to the clang-format library of the same version, so with clangd 15 you'll get clang-format 15, with clangd 16 you'll get clang-format 16 and so on.

**Comment by jczhang07** [comment]
Thanks for the tip. I specified the binary path of clangd to one from `clang+llvm-16.0.0` and the problem is solved.
