### ISSUE TITLE
clangd extensions should respect vscode settings variables standards

### ISSUE THREAD

**Issue by Singha360** [clangd/vscode-clangd#485]
When I edit the path to the clangd library, I want it to set it up as so:

```json
"clangd.path": "$userHome/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/**version**/clangd_**version**/bin/clangd"
```

This however does not work as the extension does not seem to recognize the `$userHome` variable (see more [here](https://code.visualstudio.com/docs/editor/variables-reference))

For now, using the `$userHome` gives us the path of current working directory and appends the path corresponding to the `clangd.path` setting in **settings.json**. Which means this : 
```json
"CURRENT_WORKING_DIRECTORY/$userHome/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/**version**/clangd_**version**/bin/clangd"
```

For now I have to give it the absolute path on my system which is `/Users/USER_NAME/Library/...` instead of `$userHome/Library/` which makes the setting less portable on another system as the user might have a different name all together.

**System information**
clangd version 16.0.2 
Features: mac+grpc+xpc
Platform: x86_64-apple-darwin22.4.0
Operating system: macOS 13.3.1

**Comment by HighCommander4** [comment]
See also #147, a similar request about `${workspaceFolderBasename}`.

I'm not sure whether the VSCode API provides something we can hook into to perform substitutions of all supported variables, or if we'd need to implement each variable separately (the way we've done for `${workspaceFolder}`).

**Comment by Singha360** [comment]
[This seems relevant](https://code.visualstudio.com/api/references/vscode-api#env)

**Comment by HighCommander4** [comment]
I'm sorry, I'm not following the relation between the previous comment and the original issue. Could you elaborate please?

**Comment by Singha360** [comment]
I was thinking maybe this line exposes the variables in vscode:

<img width="671" alt="image" src="https://github.com/clangd/vscode-clangd/assets/35334787/9b33e063-ed8c-4c1a-b4da-1e848f785502">

**Comment by Singha360** [comment]
They also have this in their declaration file:

<img width="868" alt="image" src="https://github.com/clangd/vscode-clangd/assets/35334787/928c7a66-8377-4eac-ae74-01fa2a39e6b9">

I have no clue how extensions are written but would love to test this on my system to confirm this myself. I will try and come back if I have any success working on it but otherwise these are all the pertinent information I found when it comes to how we could possibly interface with vscode's predefined variables...

**Comment by HighCommander4** [comment]
Ok, so it sounds like support for new variables such as `${userHome}` needs to be added one by one.

Are you interested in writing a patch to add support for `${userHome}` ? The existing code to resolve variables such as `${workspaceFolder}` is in [this function](https://github.com/clangd/vscode-clangd/blob/c03cf78a300895ddb51ff6cabd24b24e3b143146/src/config.ts#L37).

**Comment by Singha360** [comment]
I am currently working on this however I came across a few false positive when debugging the extensions, let me explain:

So with the current latest version of the clangd extension, when using `${userHome}` in the `clangd.path` settings string, this how it resolves.

![Screenshot 2023-05-25 at 5 54 45 AM](https://github.com/clangd/vscode-clangd/assets/35334787/9e837f59-b4e9-4c00-85b0-b9987934ee2d)
 
This is exactly what I have mentioned initially when I opened this issue

> When I edit the path to the clangd library, I want it to set it up as so:
> 
> ```json
> "clangd.path": "$userHome/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/**version**/clangd_**version**/bin/clangd"
> ```
> 
> This however does not work as the extension does not seem to recognize the `$userHome` variable (see more [here](https://code.visualstudio.com/docs/editor/variables-reference))
> 
> For now, using the `$userHome` gives us the path of current working directory and appends the path corresponding to the `clangd.path` setting in **settings.json**. Which means this :
> 
> ```json
> "CURRENT_WORKING_DIRECTORY/$userHome/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/**version**/clangd_**version**/bin/clangd"
> ```
> 
> For now I have to give it the absolute path on my system which is `/Users/USER_NAME/Library/...` instead of `$userHome/Library/` which makes the setting less portable on another system as the user might have a different name all together.
> 
> **System information** clangd version 16.0.2 Features: mac+grpc+xpc Platform: x86_64-apple-darwin22.4.0 Operating system: macOS 13.3.1

**HOWEVER**
![Screenshot 2023-05-25 at 5 56 20 AM](https://github.com/clangd/vscode-clangd/assets/35334787/d5333c18-6692-41e7-b176-e5f8096ec6fd)
 This is what it resolves to once I hit `F5` and I start debugging...

These result that are printed on the notification are both running after not making any changes to the code. Meaning, I only forked and cloned the repo on my system and **ran without making any changes to any files**.

I am not so sure where to proceed with this as I am a bit befuddled with how, precisely, vscode handles these variable at this point. I mention precisely as it seems like the predefined variables that vscode uses are mostly meant for `task.json` and `launch.json` files specifically. 

I think some extensions allow the use of these variables but the capacity is a case by case situation and not universal. Though I might be wrong in this assumptions, but that is what I concluded based on my research. 

I would delegate this to someone else right now but if no progress is made I can try to do this once I have more personal time.
