### ISSUE TITLE
'go to reference' context menu lost after disabling intelliSenseEngine 

### ISSUE THREAD

**Issue by beantowel** [clangd/vscode-clangd#489]
`go to reference`context menu was lost after changing the `settings.json` with the config `"C_Cpp.intelliSenseEngine": "disabled"`.
If the config was reverted to `default`, the context menu goes back.

**Logs**
I think clangd lsp works well
```
I[16:48:36.403] <-- initialize(0)
I[16:48:36.411] --> reply(0)
I[16:48:36.413] --> initialized
E[16:48:36.413] Error -32601: method not found
I[16:48:36.419] <-- textDocument/didOpen
......
```

**System information**
Clangd version (from the log, or `clangd --version`):
`clangd version 7.0.1 (tags/RELEASE701/final)`
clangd extension version:
v0.1.24
Operating system:
CentOS Linux 7

**Comment by sam-mccall** [comment]
Clangd 7 is 5 years old, and find-refs was barely supported. Please switch to a recent release.
