### ISSUE TITLE
Show the reference count of a function or variable on the fly

### ISSUE THREAD

**Issue by wwm0609** [clangd/vscode-clangd#493]
![image](https://github.com/clangd/vscode-clangd/assets/35440923/c0b92e21-7dce-4d23-a57d-f870f3b77f98)

![image](https://github.com/clangd/vscode-clangd/assets/35440923/04a45f8e-0469-43f3-814f-83aba37af87a)

Something like the above
1. show how many  subclasses/variables of a class
2. show how many times the class/fuction/variable was referenced
3. show how many overrided version of a virutal function
4. click on the count hint and pop up a preview pannel

Best Regards

**Comment by HighCommander4** [comment]
vscode calls this feature "code lens", we have https://github.com/clangd/clangd/issues/442 for it. I'll close this one as a duplicate.
