### ISSUE TITLE
clangd died in random moments in vscode

### ISSUE THREAD

**Issue by cppshizoidS** [clangd/vscode-clangd#494]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
[Error - 8:42:18 PM] The Clang Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 8:42:18 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:42:18 PM] Clang Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:42:18 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

**System information**
Clangd version (from the log, or `clangd --version`): 17.0.0
clangd extension version:0.1.24
Operating system: Arch Linux

**Comment by HighCommander4** [comment]
Please select "clangd" from the dropdown in the Output view, and post those logs.

**Comment by HighCommander4** [comment]
Or if you already had that selected, please post the complete contents (the interesting part is what comes _before_ the "The Clang Language Server server crashed 5 times" line).

**Comment by cppshizoidS** [comment]
[Error - 5:05:07 PM] Client Clang Language Server: connection to server is erroring. Shutting down server.
[Error - 5:05:07 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at ff.shutdown (/home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:8662)
	at ff.stop (/home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:8241)
	at ff.stop (/home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:51221)
	at ff.handleConnectionError (/home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:13331)
	at errorHandler (/home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:11996)
	at /home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:21723
	at Bp.invoke (/home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:2:15350)
	at wa.fire (/home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:2:16144)
	at writeErrorHandler (/home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:3:7085)
	at Bp.invoke (/home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:2:15350)
	at wa.fire (/home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:2:16144)
	at Os.fireError (/home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:3:430)
	at Socket.<anonymous> (/home/cppshizoid/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:3:1263)
	at Socket.emit (node:events:513:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)
	at runNextTicks (node:internal/process/task_queues:65:3)
	at process.processImmediate (node:internal/timers:437:9)

**Comment by dotfield** [comment]
I am having the same issue of clangd "crashing 5 times in the last 3 minutes" whilst writing code.
I should add that I disable all auto-completion so often when I am in the middle of writing code I have opened a bracket or brace that has not yet been closed, so obviously that will cause mismatches lower down. A good "intellisense" compiler will be able to handle that without crashing, and also still list for me the members of the class (which I want to view but not have typed for me. I used Tab to accept).

The version I have is v0.1.24 running in VS Code on WSL (Centos) and unfortunately where I work they have a lot of pedantic lint settings (so many it makes the build take forever)

Even if it has to crash for whatever reason, not being able to manually restart it without restarting VS Code is extremely annoying.

I like being able to get methods listed, see where there are errors (at least when I've finished typing what I intended), being able to click on definitions etc.

By the way, if I change the definition of a function it would be nice to go to the declaration to change that as well. But of course you now don't find it because I changed it.

**Comment by HighCommander4** [comment]
> Even if it has to crash for whatever reason, not being able to manually restart it without restarting VS Code is extremely annoying.

We have a command, "clangd: Restart language server", which you can run from vscode's "Run command" (F1) prompt.

I'm not sure what to make of the original issue here, as the Output view doesn't seem to contain any output from clangd. (Suggesting that maybe it fails to even start and get to the point where it prints its first line of output...?)

Is that the case for your as well? The more common case is that the Output view contains clangd output including a stack trace of the crash, in which case I would suggest filing a new issue and attaching that output.

**Comment by dotfield** [comment]
#0 0x00000000004bc2bd llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/path/to/clang-tidy-15/bin/clangd+0x4bc2bd)
 #1 0x00000000004bb2f3 llvm::sys::RunSignalHandlers() (/path/to/clang-tidy-15/bin/clangd+0x4bb2f3)
 #2 0x00000000004bb842 SignalHandler(int) Signals.cpp:0:0
 #3 0x00000000004d3270 __restore_rt libpthread.o:0:0
 #4 0x0000000000579512 llvm::CastInfo<clang::BinaryOperator, clang::Stmt const*, void>::doCastIfPossible(clang::Stmt const* const&) (.isra.0) ExprConstant.cpp:0:0
 #5 0x0000000000589857 clang::StmtVisitorBase<llvm::make_const_ptr, (anonymous namespace)::RecordExprEvaluator, bool>::Visit(clang::Stmt const*) ExprConstant.cpp:0:0
 #6 0x0000000000589e93 clang::StmtVisitorBase<llvm::make_const_ptr, (anonymous namespace)::RecordExprEvaluator, bool>::Visit(clang::Stmt const*) ExprConstant.cpp:0:0
 #7 0x000000000058a233 EvaluateInPlace(clang::APValue&, (anonymous namespace)::EvalInfo&, (anonymous namespace)::LValue const&, clang::Expr const*, bool) ExprConstant.cpp:0:0
 #8 0x00000000005b1afe clang::Expr::EvaluateAsConstantExpr(clang::Expr::EvalResult&, clang::ASTContext const&, clang::Expr::ConstantExprKind) const (/path/to/clang-tidy-15/bin/clangd+0x5b1afe)
 #9 0x0000000000a789df clang::Sema::PopExpressionEvaluationContext() (/path/to/clang-tidy-15/bin/clangd+0xa789df)
#10 0x00000000009bc956 clang::Sema::ActOnFinishFunctionBody(clang::Decl*, clang::Stmt*, bool) (/path/to/clang-tidy-15/bin/clangd+0x9bc956)
#11 0x000000000133fa21 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/path/to/clang-tidy-15/bin/clangd+0x133fa21)
#12 0x00000000012ea799 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/path/to/clang-tidy-15/bin/clangd+0x12ea799)
#13 0x00000000012f8826 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/path/to/clang-tidy-15/bin/clangd+0x12f8826)
#14 0x00000000012e83c5 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/path/to/clang-tidy-15/bin/clangd+0x12e83c5)
#15 0x00000000012e865f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#16 0x00000000012eb56b clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/path/to/clang-tidy-15/bin/clangd+0x12eb56b)
#17 0x0000000001306fce clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (/path/to/clang-tidy-15/bin/clangd+0x1306fce)
#18 0x0000000001307065 clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (/path/to/clang-tidy-15/bin/clangd+0x1307065)
#19 0x0000000001307065 clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (/path/to/clang-tidy-15/bin/clangd+0x1307065)
#20 0x0000000001307065 clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (/path/to/clang-tidy-15/bin/clangd+0x1307065)
#21 0x0000000001307065 clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (/path/to/clang-tidy-15/bin/clangd+0x1307065)
#22 0x000000000130a34d clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) (/path/to/clang-tidy-15/bin/clangd+0x130a34d)
#23 0x00000000012fdda3 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/path/to/clang-tidy-15/bin/clangd+0x12fdda3)
#24 0x00000000012eb461 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/path/to/clang-tidy-15/bin/clangd+0x12eb461)
#25 0x00000000012ebfc7 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/path/to/clang-tidy-15/bin/clangd+0x12ebfc7)
#26 0x00000000012ec049 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/path/to/clang-tidy-15/bin/clangd+0x12ec049)
#27 0x00000000012e6c9e clang::ParseAST(clang::Sema&, bool, bool) (/path/to/clang-tidy-15/bin/clangd+0x12e6c9e)
#28 0x00000000012124ef clang::FrontendAction::Execute() (/path/to/clang-tidy-15/bin/clangd+0x12124ef)
#29 0x0000000000d3bd4f clang::clangd::ParsedAST::build(llvm::StringRef, clang::clangd::ParseInputs const&, std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation>>, llvm::ArrayRef<clang::clangd::Diag>, std::shared_ptr<clang::clangd::PreambleData const>) (/path/to/clang-tidy-15/bin/clangd+0xd3bd4f)
#30 0x0000000000d78945 clang::clangd::(anonymous namespace)::ASTWorker::runWithAST(llvm::StringRef, llvm::unique_function<void (llvm::Expected<clang::clangd::InputsAndAST>)>, clang::clangd::TUScheduler::ASTActionInvalidation)::'lambda'()::operator()() TUScheduler.cpp:0:0
#31 0x0000000000d721be clang::clangd::(anonymous namespace)::ASTWorker::runTask(llvm::StringRef, llvm::function_ref<void ()>) TUScheduler.cpp:0:0
#32 0x0000000000d75ad8 clang::clangd::(anonymous namespace)::ASTWorker::run() TUScheduler.cpp:0:0
#33 0x0000000000e8d9a6 void* llvm::thread::ThreadProxy<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::'lambda0'()>>(void*) Threading.cpp:0:0

**Comment by HighCommander4** [comment]
@dotfield That stack trace looks similar to the one in https://github.com/clangd/clangd/issues/1311. The underlying issue has been fixed in clangd 16 (where I gather from the `/path/to/clang-tidy-15/bin` in your stack trace that you're using clangd 15). Upgrading to clangd 16 should resolve the crash.

**Comment by dotfield** [comment]
Thank you, I will have to propose that we upgrade to clang-tidy-16

**Comment by HighCommander4** [comment]
@cppshizoidS if you were able to resolve this, I encourage you to share what it is you did, in case it's helpful for other users encounting this.
