### ISSUE TITLE
Add the ability to fix all occurrences of a clang-tidy check

### ISSUE THREAD

**Issue by hriekehof** [clangd/vscode-clangd#495]
If i run `clang-tidy` check like `misc-const-correctness` and i have multiple hits in a file it would be great to be able to fix all occurrences at once. At the moment you have to go to every line and accept the fix. 
I think the Microsoft C++ extension already offers this if you run a code analysis with clang-tidy.

**Comment by HighCommander4** [comment]
This should be doable with "Auto Fix", but it doesn't work currently due to https://github.com/clangd/clangd/issues/1536. I'm going to close this one as a duplicate of that.
