### ISSUE TITLE
Log files are not generating

### ISSUE THREAD

**Issue by BhavyaVM1** [clangd/vscode-clangd#499]
I am using clangd extension for indexing my workspace. During the indexing process ,i can see the logs in the output tabs. But the clang_log.txt file is not generating with the following settings.

"clangd.arguments": [
        "--clang-tidy",
        "--log=verbose"
    ],
Is there some way to save the output of clangd or create a log file.

**System information**
Clangd version : llvm-16.0-p0
clangd extension version:v0.1.24
Operating system: Linux

**Comment by HighCommander4** [comment]
> But the clang_log.txt file is not generating with the following settings.

This is the first I hear of "clang_log.txt".

Where have you come across this / what makes you expect that clangd would create such a file?
