### ISSUE TITLE
xmmintrin.h: use of undeclared identifier '__builtin_ia32_addss'

### ISSUE THREAD

**Issue by ljhm** [clangd/vscode-clangd#500]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Please attach the clangd log from the "Output" window if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`): clangd version 16.0.5 (Fedora 16.0.5-1.fc38)
clangd extension version: v0.1.24
Operating system: fedora 38 linux 
VSCode: Version: 1.80.0 (Universal)

---

xmmintrin.h: use of undeclared identifier '__builtin_ia32_addss'

When i set the path "-I/usr/lib/gcc/x86_64-redhat-linux/13/include/"
to "sanitizer/lsan_interface.h" in clangd.fallbackFlags in vscode
settings.json on fedora 38.

The program compiles but clangd reports error message:
```
/usr/lib/gcc/x86_64-redhat-linux/13/include/xmmintrin.h:
use of undeclared identifier '__builtin_ia32_addss'
```

Is it conflict between xmmintrin.h files?
```
$ find /usr -name lsan_interface.h
/usr/lib/gcc/x86_64-redhat-linux/13/include/sanitizer/lsan_interface.h
$

$ find /usr -name xmmintrin.h
/usr/lib/gcc/x86_64-redhat-linux/13/include/xmmintrin.h
/usr/lib64/llvm15/lib/clang/15.0.7/include/ppc_wrappers/xmmintrin.h
/usr/lib64/llvm15/lib/clang/15.0.7/include/xmmintrin.h
/usr/lib64/clang/16/include/ppc_wrappers/xmmintrin.h
/usr/lib64/clang/16/include/xmmintrin.h
$
```

```
$ g++ --version
g++ (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)
$

Installed Packages:
clang.x86_64                      16.0.5-1.fc38  @updates
clang-libs.x86_64                 16.0.5-1.fc38  @updates
clang-resource-filesystem.x86_64  16.0.5-1.fc38  @updates
clang-tools-extra.x86_64          16.0.5-1.fc38  @updates

```

**Comment by HighCommander4** [comment]
This is a known issue. Please see https://github.com/clangd/clangd/issues/1203,  https://github.com/clangd/clangd/issues/1345, https://github.com/clangd/clangd/issues/1432, and https://github.com/clangd/clangd/issues/1695 for previous discussions and potential workarounds.

**Comment by ljhm** [comment]
> This is a known issue. Please see [clangd/clangd#1203](https://github.com/clangd/clangd/issues/1203), [clangd/clangd#1345](https://github.com/clangd/clangd/issues/1345), [clangd/clangd#1432](https://github.com/clangd/clangd/issues/1432), and [clangd/clangd#1695](https://github.com/clangd/clangd/issues/1695) for previous discussions and potential workarounds.

This is new issue to me. It didn't happen before on my computer. I'd have to switch to ms-vscode.cpptools.

**Comment by HighCommander4** [comment]
Ok, can you provide more details?

 * What is a code example that triggers the diagnostic for you?
 * When you say the issue didn't happen before, what has changed -- newer clangd version? newer compiler version? something else?

**Comment by ljhm** [comment]
> Ok, can you provide more details?
> 
> * What is a code example that triggers the diagnostic for you?
> * When you say the issue didn't happen before, what has changed -- newer clangd version? newer compiler version? something else?

Hi, I did `dnf update` then got the error. Maybe clang-tools-extra (now: 16.0.5-1.fc38) got updated too.

1. main.cpp: line 4

```
#include <sanitizer/lsan interface.h> 
```

---

2. settings.json: line 17

```
"clangd. fallbackFlags": [
  "-I/usr/lib/acc/x8664-redhat-linux/13/include/",
]
```
![Screen Shot 2023-07-13 at 1 05 28 AM](https://github.com/clangd/vscode-clangd/assets/9011764/1d88b7e9-6049-4ff8-b0e6-f043d4135efb)

**Comment by ljhm** [comment]
Sorry, 

I specified the wrong path to lsan_interface.h. 
The one under /usr/include works now. 

/usr/include/sanitizer/lsan_interface.h
/usr/lib/gcc/x86_64-redhat-linux/13/include/sanitizer/lsan_interface.h
