### ISSUE TITLE
refs/derived shortcut

### ISSUE THREAD

**Issue by koll1009** [clangd/vscode-clangd#505]
Hi, I very like this extension. I have used it to substitute ccls. Only one bad, it's not as easy as ccls to jump to reference. could you supply similar shortcut like ccls?

![image](https://github.com/clangd/vscode-clangd/assets/3896772/0e2dde5c-ee63-46c0-b814-47507e27fe84)

**Comment by HighCommander4** [comment]
The Language Server Protocol calls this feature "code lens". The tracking bug for it is https://github.com/clangd/clangd/issues/442.
