### ISSUE TITLE
Extension partially disable sticky scroll

### ISSUE THREAD

**Issue by LumiereDeLOmbre** [clangd/vscode-clangd#522]
Hi,

This extension partially disable sticky scroll once activated.

A single line is shown when it should show more, depending on the context.

To make sure, I disabled all the extensions and reset them one by one to spot the culprit.

Do not hesitate if you need further info.

**Comment by HighCommander4** [comment]
> Do not hesitate if you need further info.

Yes, please provide a code example, and screenshots showing the sticky headers with / without clangd.

**Comment by LumiereDeLOmbre** [comment]
Apparently, my folders in the workspace were opened for too long (months).
I completely closed every folder in the workspace, closed the app and reopened them. The issue went away.

hmmmm. Solved..

Thanks (and sorry)
