### ISSUE TITLE
Can't wrap line in QML

### ISSUE THREAD

**Issue by stvsl** [clangd/vscode-clangd#529]
Type: <b>Bug</b>

I configured a qml development environment, but now line wrapping cannot work properly.

Extension version: 0.1.24
VS Code version: Code 1.82.1 (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:41:36.199Z)
OS version: Linux x64 6.5.2-zen1-1-zen
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 4068)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 2, 2|
|Memory (System)|30.77GB (23.10GB free)|
|Process Argv|--unity-launch /home/stvsl/Documents/DXCZ/combine/CABT --crash-reporter-id be7fb336-8bcd-4f64-ad72-7b42cb47474a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30835152
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by HighCommander4** [comment]
Can you elaborate on what you mean by "line wrapping cannot work properly"?

What is it that you're doing, what do you expect to happen, and what actually happens?

**Comment by stvsl** [comment]
At that time, after I had configured the environment, I couldn't line break in this particular place, but I could line break normally everywhere else. Later on, I found out that this might be conflicting with other plugins.
![image](https://github.com/clangd/vscode-clangd/assets/41932612/b4dd1ed1-02b3-4de9-a5f7-968b8d1a24c2)
