### ISSUE TITLE
clangd formatting some part of line to next line

### ISSUE THREAD

**Issue by lakshits11** [clangd/vscode-clangd#545]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

Suppose I have a line 37 of code like this:

![image](https://github.com/clangd/vscode-clangd/assets/54276661/20d51048-32d6-495f-a78c-c595ecdc5e52)

Now if I format the code, some part of line 37 is automatically sent to next line

<img width="645" alt="image" src="https://github.com/clangd/vscode-clangd/assets/54276661/e8821fea-6b6e-4441-b187-6e876bf3734a">

why does it happen? Below are my .clang-format settings:
```
BasedOnStyle: LLVM
UseTab: Never
IndentWidth: 4
TabWidth: 4
BreakBeforeBraces: Allman
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
ColumnLimit: 0
AccessModifierOffset: -4
NamespaceIndentation: All
FixNamespaceComments: false
AlignConsecutiveMacros: true
```

I also have word wrap set to off in vscode settings.

**Logs**
Please attach the clangd log from the "Output" window if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`): 14.0.6
clangd extension version: 0.1.24
Operating system: Windows 11

**Comment by i-ky** [comment]
Duplicates https://github.com/llvm/llvm-project/issues/44363.

**Comment by HighCommander4** [comment]
> Duplicates [llvm/llvm-project#44363](https://github.com/llvm/llvm-project/issues/44363).

Thanks!

Looks like this was fixed a few days ago so a fix should appear in clangd 18.

**Comment by lakshits11** [comment]
So do I need to update my clangd version? I thought maybe extension will fix the issue without need of updating clangd version.

**Comment by i-ky** [comment]
> So do I need to update my clangd version?

Yes, you will need to wait until clangd 18 is released, grab a weekly release from GitHub or build it yourself from source to get the latest fixes.
