### ISSUE TITLE
clangd does not respect fallback flags

### ISSUE THREAD

**Issue by lakshits11** [clangd/vscode-clangd#547]
I am a newbie so I am sorry if its a noob question 😅
Below is my configuration in settings. See that I have set std=c++14. I do not have a compile_commands.json file and neither do i need one. I just want that whatever file is opened, it provides correct errors,warnings and auto completion for that file.

<img width="583" alt="image" src="https://github.com/clangd/vscode-clangd/assets/54276661/bd8304ed-aba1-4cbc-9d18-dad7c70bad16">

It was doing it perfectly until i noticed one thing. In one file, I used `register` keyword.

<img width="629" alt="image" src="https://github.com/clangd/vscode-clangd/assets/54276661/7fd01bad-b735-45c1-b4e6-c8065ca24db6">

I don't understand why it is showing c++17 warnings if I am using c++14 version.

**System information**
Clangd version (from the log, or `clangd --version`): 14.0.6
clangd extension version: latest
Operating system: Win 11

**Comment by HighCommander4** [comment]
Please upload [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs) to help diagnose the problem.

**Comment by lakshits11** [comment]
I am sorry if its not what you wanted. I added `--log=verbose` in arguments and below is some output from extension. It was given when i created a new file and wrote below code.

```cpp
#include<bits/stdc++.h>
using namespace std;

int main(int argc, char const *argv[])
{
     int i = 0;
    register int j = 0;
    
      
    return 0;
}
```

Maybe you can try it on your machine?

**Comment by lakshits11** [comment]
Thank You Very much !!
