### ISSUE TITLE
macro symbol (by #define) not listed in current file's outline in clangd

### ISSUE THREAD

**Issue by Shaka0723** [clangd/vscode-clangd#548]
when I use clangd as my c project LSP, and define a macro (e.g., #define FOO 1234) in a source or header (.c or .h)
then show the outline of current file, symbol listed but except all macros - symbol FOO can not be found.
![image](https://github.com/clangd/vscode-clangd/assets/56809930/51eef58c-8a88-42aa-a3bc-409ca0e51e06)
I know macro symbol can be shown in  workspace's symbol list, but it's not as convinnent as curretn file's outline
![image](https://github.com/clangd/vscode-clangd/assets/56809930/3ecf244b-9106-42e2-9adf-fd7f9549f1a8)

Remark:

-  symbol defined by enum works fine
-  clangd version: 17
- OS: both win and linux
-  if using cpptools as LSP, not this issue.

**Comment by HighCommander4** [comment]
Duplicate of https://github.com/clangd/clangd/issues/1744
