### ISSUE TITLE
Struct function member tokens colorized as functions for C

### ISSUE THREAD

**Issue by cursedcrafts** [clangd/vscode-clangd#549]
Currently struct function pointers gets colored with `property` semantic token type. Having `function` colorization would help quite a lot spotting those from the code.

```c
struct {
  void (*func)(void);
  int var;
} test;

int main(void) {
  // func has same color as var currently
  test.func();
  test.var = 2;
}
```

**Comment by i-ky** [comment]
Wouldn't `function` coloring be confusing when `func` is assigned to? Also in C++ `struct` can have "true" function members and coloring data members as `function` may be confusing as well.

**Comment by cursedcrafts** [comment]
That I didn't even think of. Yes, that would be indeed confusing as well. In that case I think the better option is for me to instead find a method of overriding `semantic token type` with `textmate scopes` as that would recognize the member as `entity.name.function.member.c` when the parenthesis are used.
