### ISSUE TITLE
Syntax tree entry (char) is not resolved

### ISSUE THREAD

**Issue by Darkness2k19** [clangd/vscode-clangd#551]
`char` is not highlighted as if it was not parsed as a valid token
`const std::string sc(1, 'a'); `
`static_assert(!std::is_assignable_v<decltype(*sc.data()), char>);`
![Screenshot from 2023-11-20 02-09-25](https://github.com/clangd/vscode-clangd/assets/47902256/5827c001-8edd-4bdc-a82c-8aebc5fb096f)

**Logs**
**Initialization**
[clangd.log](https://github.com/clangd/vscode-clangd/files/13404880/clangd.log)

**On hower over `char`**
I[01:56:57.013] <-- textDocument/hover(19)
V[01:56:57.014] ASTWorker running Hover on version 1 of /home/darknessx/Projects/CPP/Programming/review/string/main.cpp
I[01:56:57.016] --> reply:textDocument/hover(19) 2 ms
V[01:56:57.016] >>> {"id":19,"jsonrpc":"2.0","result":null}

**System information**
Clangd version: 16.0.2
clangd extension version: 0.1.24
Operating system: Ubuntu 22.04.3 LTS

**Comment by HighCommander4** [comment]
Clangd does not apply semantic highlighting to keyword tokens in general, leaving that to client-side highlighting.

Is the apperance of `char` any different in this `static_assert` tha on the line:

```c++
char c;
```

?

**Comment by Darkness2k19** [comment]
Yes, it differs
![image](https://github.com/clangd/vscode-clangd/assets/47902256/b9d748c2-afc3-4c92-be61-8e06723d6aa9)

I supposed there was something with c++ version that is used to parse tokens and to highlight them because, if I change `is_assignable_v` to `is_assignable` or even just add a trailing `::`, the `char` becomes properly highlighted
![image](https://github.com/clangd/vscode-clangd/assets/47902256/a17011db-8f8a-4cd2-8518-525ea1df0d75)
![image](https://github.com/clangd/vscode-clangd/assets/47902256/09b0b2f7-fe67-49b8-87bd-14e157862c19)

**Comment by HighCommander4** [comment]
It's an issue of vscode's client-side highlighting, please file it at https://github.com/jeff-hykin/better-cpp-syntax.

You can also consider using [Minimal C++ Syntax](https://marketplace.visualstudio.com/items?itemName=daiyousei-qz.minimal-cpp-syntax) as an alternative client-side highlighting engine to VSCode's default, it does not have this problem.

**Comment by Darkness2k19** [comment]
Thank you very much for your help, this issue is then resolved!
