### ISSUE TITLE
Add possibility to hide auto return type and parameter names

### ISSUE THREAD

**Issue by stephanlachnit** [clangd/vscode-clangd#555]
Currently, source code lines can look significantly longer due to parameter names and the return being written out if it is auto type.

See for example here:
![Screenshot from 2023-11-26 21-48-46](https://github.com/clangd/vscode-clangd/assets/36662302/2ad56afa-a96a-4694-bf7f-6b83d8bb56ff)

I would be nice to add an option, that could hide these (I personally am fine with hovering over the symbol to get more info like resolved type and parameter name).

**Comment by HighCommander4** [comment]
We have such an option, please see https://clangd.llvm.org/config.html#inlayhints

**Comment by stephanlachnit** [comment]
> We have such an option, please see https://clangd.llvm.org/config.html#inlayhints

Ah, it's configured in clangd directly. Thanks and sorry for the noise.

**Comment by HighCommander4** [comment]
> Ah, it's configured in clangd directly

VSCode also has a setting to disable it on the client-side if you prefer that: `"editor.inlayHints.enabled"`.
