### ISSUE TITLE
pp_file_not_found sys/cdefs.h file not found 

### ISSUE THREAD

**Issue by keepitsimle** [clangd/vscode-clangd#556]
Please describe the problem.
I cross-compile the app at code-sever, it's simple ,  but  clangd keeps showing that it can't find the header file. 
run cmd "**clangd --check=/root/project/cloud-edge-collaboration-test/src/main.cpp**"   Is there anything I've lost ?
the clangd.arguments setting below:
![image](https://github.com/clangd/vscode-clangd/assets/15873225/3661ab3a-9c4d-45e8-b95a-c0586528e91d)

**Logs**
Please attach the clangd log from the "Output" window if you can.
I[15:47:35.573] argv[0]: clangd
I[15:47:35.573] argv[1]: --check=/root/project/cloud-edge-collaboration-test/src/main.cpp
I[15:47:35.573] Entering check mode (no LSP server)
I[15:47:35.573] Testing on source file /root/project/cloud-edge-collaboration-test/src/main.cpp
I[15:47:35.573] Loading compilation database...
I[15:47:35.573] Loaded compilation database from /root/project/cloud-edge-collaboration-test/build/compile_commands.json
I[15:47:35.574] Compile command from CDB is: /opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ --target=aarch64-linux-gnu --driver-mode=g++ -DIS_LITTLE_ENDIAN=1 -I/root/project/cloud-edge-collaboration-test/build/subprojects/stage/include -O3 -DNDEBUG -fPIE -std=gnu++11 -o CMakeFiles/cloud_edge.dir/main.cpp.o -c -resource-dir=/usr/lib/clang/15.0.0 -- /root/project/cloud-edge-collaboration-test/src/main.cpp
I[15:47:35.574] Parsing command...
I[15:47:35.575] internal (cc1) args are: -cc1 -triple aarch64-unknown-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=non-leaf -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu generic -target-feature +neon -target-feature +v8a -target-abi aapcs -fallow-half-arguments-and-returns -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/root/project/cloud-edge-collaboration-test/build/src -resource-dir /usr/lib/clang/15.0.0 -D IS_LITTLE_ENDIAN=1 -I /root/project/cloud-edge-collaboration-test/build/subprojects/stage/include -D NDEBUG -internal-isystem /opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/7.5.0/../../../../aarch64-linux-gnu/include/c++/7.5.0 -internal-isystem /opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/7.5.0/../../../../aarch64-linux-gnu/include/c++/7.5.0/aarch64-linux-gnu -internal-isystem /opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/7.5.0/../../../../aarch64-linux-gnu/include/c++/7.5.0/backward -internal-isystem /usr/lib/clang/15.0.0/include -internal-isystem /usr/local/include -internal-isystem /opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/7.5.0/../../../../aarch64-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=gnu++11 -fdeprecated-macro -fdebug-compilation-dir=/root/project/cloud-edge-collaboration-test/build/src -ferror-limit 19 -fno-signed-char -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -vectorize-loops -vectorize-slp -no-round-trip-args -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /root/project/cloud-edge-collaboration-test/src/main.cpp
I[15:47:35.575] Building preamble...
I[15:47:35.696] Indexing headers...
E[15:47:35.736] [pp_file_not_found] Line 3: in included file: 'sys/cdefs.h' file not found
I[15:47:35.736] Building AST...
E[15:47:35.740] [typecheck_invalid_operands] Line 8: invalid operands to binary expression ('std::ostream' (aka 'int') and 'const char[19]')
I[15:47:35.740] Indexing AST...
I[15:47:35.740] Building inlay hints
I[15:47:35.740] Testing features at each token (may be slow in large files)
I[15:47:35.742] All checks completed, 2 errors

**System information**
Clangd version (from the log, or `clangd --version`):
clangd extension version:
Operating system:

**Comment by keepitsimle** [comment]
I[16:34:54.675] clangd version 15.0.0 (https://github.com/llvm/llvm-project 4ba6a9c9f65bbc8bd06e3652cb20fd4dfc846137)
I[16:34:54.675] Features: linux+grpc
I[16:34:54.675] PID: 3918884
I[16:34:54.675] Working directory: /root/project/cloud-edge-collaboration-test
I[16:34:54.675] argv[0]: /usr/bin/clangd
I[16:34:54.675] argv[1]: --all-scopes-completion
I[16:34:54.675] argv[2]: --completion-style=detailed
I[16:34:54.675] argv[3]: --query-driver=/opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/*
I[16:34:54.675] argv[4]: --log=verbose
V[16:34:54.675] User config file is /root/.config/clangd/config.yaml
I[16:34:54.675] Starting LSP over stdin/stdout
V[16:34:54.679] <<< {"id":0,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"markdown":{"parser":"marked","version":"1.1.0"},"positionEncodings":["utf-16"],"regularExpressions":{"engine":"ECMAScript","version":"ES2020"},"staleRequestSupport":{"cancel":true,"retryOnContentModified":["textDocument/semanticTokens/full","textDocument/semanticTokens/range","textDocument/semanticTokens/full/delta"]}},"notebookDocument":{"synchronization":{"dynamicRegistration":true,"executionSummarySupport":true}},"textDocument":{"callHierarchy":{"dynamicRegistration":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"dynamicRegistration":true,"honorsChangeAnnotations":false,"isPreferredSupport":true,"resolveSupport":{"properties":["edit"]}},"codeLens":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"completion":{"completionItem":{"commitCharactersSupport":true,"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"insertReplaceSupport":true,"insertTextModeSupport":{"valueSet":[1,2]},"labelDetailsSupport":true,"preselectSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"completionList":{"itemDefaults":["commitCharacters","editRange","insertTextFormat","insertTextMode"]},"contextSupport":true,"dynamicRegistration":true,"editsNearCursor":true,"insertTextMode":2},"declaration":{"dynamicRegistration":true,"linkSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"diagnostic":{"dynamicRegistration":true,"relatedDocumentSupport":false},"documentHighlight":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"documentSymbol":{"dynamicRegistration":true,"hierarchicalDocumentSymbolSupport":true,"labelSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"foldingRange":{"dynamicRegistration":true,"foldingRange":{"collapsedText":false},"foldingRangeKind":{"valueSet":["comment","imports","region"]},"lineFoldingOnly":true,"rangeLimit":5000},"formatting":{"dynamicRegistration":true},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"inlayHint":{"dynamicRegistration":true,"resolveSupport":{"properties":["tooltip","textEdits","label.tooltip","label.location","label.command"]}},"inlineValue":{"dynamicRegistration":true},"linkedEditingRange":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"publishDiagnostics":{"codeDescriptionSupport":true,"dataSupport":true,"relatedInformation":true,"tagSupport":{"valueSet":[1,2]},"versionSupport":false},"rangeFormatting":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"honorsChangeAnnotations":true,"prepareSupport":true,"prepareSupportDefaultBehavior":1},"selectionRange":{"dynamicRegistration":true},"semanticTokens":{"augmentsSyntaxTokens":true,"dynamicRegistration":true,"formats":["relative"],"multilineTokenSupport":false,"overlappingTokenSupport":false,"requests":{"full":{"delta":true},"range":true},"serverCancelSupport":true,"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator","decorator"]},"signatureHelp":{"contextSupport":true,"dynamicRegistration":true,"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"typeHierarchy":{"dynamicRegistration":true}},"window":{"showDocument":{"support":true},"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"workDoneProgress":true},"workspace":{"applyEdit":true,"codeLens":{"refreshSupport":true},"configuration":true,"diagnostics":{"refreshSupport":true},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":true},"executeCommand":{"dynamicRegistration":true},"fileOperations":{"didCreate":true,"didDelete":true,"didRename":true,"dynamicRegistration":true,"willCreate":true,"willDelete":true,"willRename":true},"inlayHint":{"refreshSupport":true},"inlineValue":{"refreshSupport":true},"semanticTokens":{"refreshSupport":true},"symbol":{"dynamicRegistration":true,"resolveSupport":{"properties":["location.range"]},"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"workspaceEdit":{"changeAnnotationSupport":{"groupsOnLabel":true},"documentChanges":true,"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"code-server","version":"1.77.3"},"initializationOptions":{"clangdFileStatus":true,"fallbackFlags":[]},"locale":"en","processId":3917127,"rootPath":"/root/project/cloud-edge-collaboration-test","rootUri":"file:///root/project/cloud-edge-collaboration-test","trace":"off","workspaceFolders":[{"name":"cloud-edge-collaboration-test","uri":"file:///root/project/cloud-edge-collaboration-test"}]}}

I[16:34:54.679] <-- initialize(0)
I[16:34:54.679] --> reply:initialize(0) 0 ms
V[16:34:54.679] >>> {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"astProvider":true,"callHierarchyProvider":true,"clangdInlayHintsProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"compilationDatabase":{"automaticReload":true},"completionProvider":{"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/","*"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"implementationProvider":true,"inlayHintProvider":true,"memoryUsageProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":["declaration","deprecated","deduced","readonly","static","abstract","virtual","dependentName","defaultLibrary","usedAsMutableReference","functionScope","classScope","fileScope","globalScope"],"tokenTypes":["variable","variable","parameter","function","method","function","property","variable","class","interface","enum","enumMember","type","type","unknown","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",")","{","}","<",">",","]},"standardTypeHierarchyProvider":true,"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeDefinitionProvider":true,"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 15.0.0 (https://github.com/llvm/llvm-project 4ba6a9c9f65bbc8bd06e3652cb20fd4dfc846137) linux+grpc x86_64-unknown-linux-gnu"}}}

V[16:34:54.681] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}

I[16:34:54.681] <-- initialized
V[16:34:54.689] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"cpp","text":"\n\n#include <vector>\n#include <iostream>\nusing namespace std;\nint main()\n{\n    std::cout <<\" ================ \";\n}","uri":"file:///root/project/cloud-edge-collaboration-test/src/main.cpp","version":1}}}

I[16:34:54.689] <-- textDocument/didOpen
I[16:34:54.689] Loaded compilation database from /root/project/cloud-edge-collaboration-test/build/compile_commands.json
V[16:34:54.689] System include extraction: not allowed driver //opt/toolchains//gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++
V[16:34:54.689] Broadcasting compilation database from /root/project/cloud-edge-collaboration-test
I[16:34:54.689] ASTWorker building file /root/project/cloud-edge-collaboration-test/src/main.cpp version 1 with command 
[/root/project/cloud-edge-collaboration-test/build/src]
/opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ --target=aarch64-linux-gnu --driver-mode=g++ -DIS_LITTLE_ENDIAN=1 -I/root/project/cloud-edge-collaboration-test/build/subprojects/stage/include -O3 -DNDEBUG -fPIE -std=gnu++11 -o CMakeFiles/cloud_edge.dir/main.cpp.o -c -resource-dir=/usr/lib/clang/15.0.0 -- /root/project/cloud-edge-collaboration-test/src/main.cpp
I[16:34:54.689] --> window/workDoneProgress/create(0)
V[16:34:54.689] >>> {"id":0,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"backgroundIndexProgress"}}

I[16:34:54.689] Enqueueing 1 commands for indexing
V[16:34:54.690] Driver produced command: cc1 -cc1 -triple aarch64-unknown-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=non-leaf -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu generic -target-feature +neon -target-feature +v8a -target-abi aapcs -fallow-half-arguments-and-returns -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/root/project/cloud-edge-collaboration-test/build/src -resource-dir /usr/lib/clang/15.0.0 -D IS_LITTLE_ENDIAN=1 -I /root/project/cloud-edge-collaboration-test/build/subprojects/stage/include -D NDEBUG -internal-isystem /opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/7.5.0/../../../../aarch64-linux-gnu/include/c++/7.5.0 -internal-isystem /opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/7.5.0/../../../../aarch64-linux-gnu/include/c++/7.5.0/aarch64-linux-gnu -internal-isystem /opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/7.5.0/../../../../aarch64-linux-gnu/include/c++/7.5.0/backward -internal-isystem /usr/lib/clang/15.0.0/include -internal-isystem /usr/local/include -internal-isystem /opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/7.5.0/../../../../aarch64-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=gnu++11 -fdeprecated-macro -fdebug-compilation-dir=/root/project/cloud-edge-collaboration-test/build/src -ferror-limit 19 -fno-signed-char -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -vectorize-loops -vectorize-slp -no-round-trip-args -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /root/project/cloud-edge-collaboration-test/src/main.cpp
I[16:34:54.690] --> textDocument/clangd.fileStatus
V[16:34:54.690] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Update","uri":"file:///root/project/cloud-edge-collaboration-test/src/main.cpp"}}

V[16:34:54.690] Building first preamble for /root/project/cloud-edge-collaboration-test/src/main.cpp version 1
V[16:34:54.691] <<< {"id":0,"jsonrpc":"2.0","result":null}

I[16:34:54.691] <-- reply(0)
I[16:34:54.691] --> $/progress
V[16:34:54.691] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"begin","percentage":0,"title":"indexing"}}}

I[16:34:54.691] --> $/progress
V[16:34:54.691] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"report","message":"0/1","percentage":0}}}

V[16:34:54.704] BackgroundIndex: building version 1 after loading index from disk
V[16:34:54.721] BackgroundIndex: serving version 1 (4140149 bytes)
I[16:34:54.722] --> $/progress
V[16:34:54.723] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"report","message":"0/1","percentage":0}}}

I[16:34:54.723] --> $/progress
V[16:34:54.723] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"end"}}}

V[16:34:54.753] <<< {"id":1,"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///root/project/cloud-edge-collaboration-test/src/main.cpp"}}}

I[16:34:54.753] <-- textDocument/documentSymbol(1)
V[16:34:54.753] <<< {"id":2,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[],"triggerKind":2},"range":{"end":{"character":1,"line":8},"start":{"character":1,"line":8}},"textDocument":{"uri":"file:///root/project/cloud-edge-collaboration-test/src/main.cpp"}}}

I[16:34:54.753] <-- textDocument/codeAction(2)
V[16:34:54.755] <<< {"id":3,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///root/project/cloud-edge-collaboration-test/src/main.cpp"}}}

I[16:34:54.755] <-- textDocument/documentLink(3)
V[16:34:54.755] <<< {"id":4,"jsonrpc":"2.0","method":"textDocument/inlayHint","params":{"range":{"end":{"character":1,"line":8},"start":{"character":0,"line":0}},"textDocument":{"uri":"file:///root/project/cloud-edge-collaboration-test/src/main.cpp"}}}

I[16:34:54.755] <-- textDocument/inlayHint(4)
V[16:34:54.831] indexed preamble AST for /root/project/cloud-edge-collaboration-test/src/main.cpp version 1:
  symbol slab: 3048 symbols, 1006264 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 128 relations, 2200 bytes
V[16:34:54.846] Build dynamic index for header symbols with estimated memory usage of 2784568 bytes
V[16:34:54.847] Built preamble of size 1903820 for file /root/project/cloud-edge-collaboration-test/src/main.cpp version 1 in 0.16 seconds
I[16:34:54.847] --> workspace/semanticTokens/refresh(1)
V[16:34:54.847] >>> {"id":1,"jsonrpc":"2.0","method":"workspace/semanticTokens/refresh","params":null}

I[16:34:54.847] --> textDocument/clangd.fileStatus
V[16:34:54.847] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Build AST","uri":"file:///root/project/cloud-edge-collaboration-test/src/main.cpp"}}

I[16:34:54.847] --> textDocument/clangd.fileStatus
V[16:34:54.847] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, parsing main file","uri":"file:///root/project/cloud-edge-collaboration-test/src/main.cpp"}}

V[16:34:54.848] <<< {"id":1,"jsonrpc":"2.0","result":null}

I[16:34:54.848] <-- reply(1)
V[16:34:54.852] indexed file AST for /root/project/cloud-edge-collaboration-test/src/main.cpp version 1:
  symbol slab: 1 symbols, 4448 bytes

**Comment by HighCommander4** [comment]
The line which suggests the problem is:

> V[16:34:54.689] System include extraction: not allowed driver //opt/toolchains//gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++

I'm not quite sure how those double slashes got in there, but the message suggests that changing the `--query-driver` parameter to `--query-driver=//opt//toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/*` shiuld help.

(The behaviour will be improved in clangd 18, due to a recent change (https://github.com/llvm/llvm-project/pull/66757) to normalize the path in a way that will collapse double slashes.)
