### ISSUE TITLE
designate macro value in project config to control code highlighting

### ISSUE THREAD

**Issue by guxiao-tetras** [clangd/vscode-clangd#563]
MS intelligence has a feature, Defines, which coud set macro value in the code and control which parts of the code(in #ifdef #else #endif) is activated.
This can be useful when reading only part of the code.
Can you provide the same feature?
Thank you.

**Comment by HighCommander4** [comment]
We have a couple of mechanisms to do this already:

 1. Add a compiler flag for the define (e.g. `-DNAME=VALUE`) to the commands in your `compile_commands.json` file. See https://clangd.llvm.org/installation#project-setup for more details on different ways to create a `compile_commands.json` file.
 2. Add the compiler flag using a [clangd config file](https://clangd.llvm.org/config.html) (`.clangd` file in the project root directory), for example:
 
    ```yaml
    CompileFlags:
      Add: [-DNAME=VALUE]
    ```

**Comment by guxiao-tetras** [comment]
> 1. -DNAME=VALUE

Thanks, it works for me.
