### ISSUE TITLE
Where can I get the list of clangd.argument decriptions?

### ISSUE THREAD

**Issue by Cupcc** [clangd/vscode-clangd#570]
I don't know how to set it up?
Is there any tutorial for novice?

<img width="270" alt="image" src="https://github.com/clangd/vscode-clangd/assets/53716543/4deadcea-b527-4329-b32a-8d0886fb7c83">

**Comment by HighCommander4** [comment]
> I don't know how to set it up? Is there any tutorial for novice?

A good starting point is probably https://clangd.llvm.org/installation#project-setup

You often don't need anything in `"clangd.arguments"`, but to answer the question in the issue title, you can get a list of options and their descriptions by running `clangd --help` on the command line.

**Comment by Cupcc** [comment]
> > I don't know how to set it up? Is there any tutorial for novice?
> 
> A good starting point is probably https://clangd.llvm.org/installation#project-setup
> 
> You often don't need anything in `"clangd.arguments"`, but to answer the question in the issue title, you can get a list of options and their descriptions by running `clangd --help` on the command line.

Thank you for your help. I've tried both ways, but I could only find part of the clangd arguments descriptions in each resource. Is there a complete document available?

**Comment by Cupcc** [comment]
> > I don't know how to set it up? Is there any tutorial for novice?
> 
> A good starting point is probably https://clangd.llvm.org/installation#project-setup
> 
> You often don't need anything in `"clangd.arguments"`, but to answer the question in the issue title, you can get a list of options and their descriptions by running `clangd --help` on the command line.

Thank you for your help. I've tried both ways, but I could only find part of the clangd arguments descriptions in each resource. Is there a complete document available?

**Comment by Cupcc** [comment]
> > I don't know how to set it up? Is there any tutorial for novice?
> 
> A good starting point is probably https://clangd.llvm.org/installation#project-setup
> 
> You often don't need anything in `"clangd.arguments"`, but to answer the question in the issue title, you can get a list of options and their descriptions by running `clangd --help` on the command line.

Thank you Sooo much!
