### ISSUE TITLE
clangd crashing doesn't clear notifications

### ISSUE THREAD

**Issue by njames93** [clangd/vscode-clangd#58]
If clangd crashes while indexing, the indexing notification isn't cleared.
For this type of progress notification its not possible for a user to manually clear it either, leading to a notification tray looking like this:
![image](https://user-images.githubusercontent.com/5469473/88854823-d0ddbf80-d1e9-11ea-817c-d7874dc98196.png)
This issue also occurs if you manually restart the clangd server using the command palette

**Comment by hokein** [comment]
Looks like vscode only cleans up the notification after receiving a `WorkDoneProgressEnd` notification from clangd.

However, when clangd crashes, there is no way to send this notification to the client. I think vscode client should clean up the dangling notifications if the connect is not alive.

**Comment by njames93** [comment]
Any update on this. Issue still seems to persist.

**Comment by njames93** [comment]
This is working on my end now, thanks.
