### ISSUE TITLE
Release version 0.1.27

### ISSUE THREAD

**Issue by kotborealis** [clangd/vscode-clangd#590]
I just wanted to know how long would it take to publish a new version of this extension to the marketplace?
Specifically, I'm waiting for the #587 patch to go live.

Also let me know if I can help with this - should I submit a PR with a version bump?

**Comment by HighCommander4** [comment]
Thanks for filing. In addition to #587, #390 is another recent fix issue which I imagine some users are waiting to get released.

I'd like to fix one more thing, #588, and then release those three fixes together.

> Also let me know if I can help with this - should I submit a PR with a version bump?

Sure, please go ahead.

**Comment by HighCommander4** [comment]
I posted a PR at https://github.com/clangd/vscode-clangd/pull/596

**Comment by kotborealis** [comment]
Thank you so much for your work!
