### ISSUE TITLE
Regression issue on the new 0.1.27 release.

### ISSUE THREAD

**Issue by hokein** [clangd/vscode-clangd#599]
Steps:

1. work in a cpp source file, and introduce some code that make clangd crashes.
2. revert the change, and run `clangd: restart language server` command to restart clangd.

Now with 0.1.27, the restart command in 2) doesn't work -- I don't see a new instance of clangd starts. The https://github.com/clangd/vscode-clangd/pull/587 is a related change, @HighCommander4 .

**Comment by HighCommander4** [comment]
Thanks for filing, I'll investigate.

**Comment by HighCommander4** [comment]
Proposed fix: https://github.com/clangd/vscode-clangd/pull/601

Apologies for the regression.

**Comment by HighCommander4** [comment]
I also filed https://github.com/clangd/vscode-clangd/issues/602 as a follow-up for adding some tests for the clangd.restart command to avoid accidentally introducing regressions like this in the future.

**Comment by hokein** [comment]
Confirm that v0.1.28 release works now. Thanks!
