### ISSUE TITLE
Watch for compile_commands.json

### ISSUE THREAD

**Issue by navidR** [clangd/vscode-clangd#6]
Microsoft CMake extension has this handy ability to automatically copy the compile_commands.json to wherever you want. So it is possible to automatically configure the project and copy the compile_commands.json to workspace location, the only missing part of the puzzle is vscode-clangd should watch for compile_commands.json for change or creation. This feature could be extremely useful.

**Comment by pitaj** [comment]
Also `compile_flags.txt`, `.clang-tidy`, and `.clang-format`

**Comment by hammypants** [comment]
I just spent two days going batshit crazy because I had no idea I needed to restart the language server after every reconfigure...

**Comment by hokein** [comment]
Implemented in #33.
