### ISSUE TITLE
'-mabi' issues

### ISSUE THREAD

**Issue by ZZH-Finalize** [clangd/vscode-clangd#605]
clangd raise an error "Unsupported option '-mabi=' for target 'x86_64-unknown-linux-gnu'" after I rebuild my project, but it works well before.

I have already specified the '-mabi=lp64d', and this flag is generated to compile_commands.json by meson build system.
![image](https://github.com/clangd/vscode-clangd/assets/33342565/195a196a-a58c-4a6d-be70-04175cccf58d)
![image](https://github.com/clangd/vscode-clangd/assets/33342565/b47a8e4b-92e3-4a26-83af-3cb7837e0f32)

**System information**
Clangd version (from the log, or `clangd --version`):
![image](https://github.com/clangd/vscode-clangd/assets/33342565/7456913e-9bac-4b0d-8fed-cb6f6ea07bcc)
clangd extension version:
![image](https://github.com/clangd/vscode-clangd/assets/33342565/509330b6-818a-4a19-8b95-81a4adf549a4)
Operating system:
![image](https://github.com/clangd/vscode-clangd/assets/33342565/4a83b28e-825c-4c76-8fcc-b656ec43bfce)

**Comment by HighCommander4** [comment]
The flag can be removed using https://clangd.llvm.org/config.html#remove if clang does not recognize it.

**Comment by ZZH-Finalize** [comment]
> The flag can be removed using https://clangd.llvm.org/config.html#remove if clang does not recognize it.

I add this configuration to my .clangd file, the error is gone but I still can't get any tip or code completion at all.

But I noticed that if I generate the compile_commands.json by bear from the Makefile, the clangd will work as expected, the compile flags are the same. The only difference between these two "compile_commands.json" is the format, "meson" put flags into command section but "bear" put flags into arguments section like this:

![image](https://github.com/clangd/vscode-clangd/assets/33342565/d5b74a30-79ae-420e-8f8d-31178a40f931)
![image](https://github.com/clangd/vscode-clangd/assets/33342565/2d300185-b43a-4be6-a5f5-c37483a85172)

**Comment by HighCommander4** [comment]
Can you share a complete [clangd log](https://clangd.llvm.org/troubleshooting.html#gathering-logs) for the non-working (meson) case?

**Comment by ZZH-Finalize** [comment]
Yes, I setup a new demo project that doesn't contain any confidential information, this project has the same problem. I uploaded the"compile_commands.json" file and clangd log.
[compile_commands.json](https://github.com/clangd/vscode-clangd/files/14691697/compile_commands.json)
[clangd.json](https://github.com/clangd/vscode-clangd/files/14691700/clangd.json)
[clangd-log-from-vscode-output.txt](https://github.com/clangd/vscode-clangd/files/14691719/clangd-log-from-vscode-output.txt)
[dot_clangd.txt](https://github.com/clangd/vscode-clangd/files/14691730/dot_clangd.txt)

**Comment by ZZH-Finalize** [comment]
> (I don't have a log for the working (bear) version to compare, but maybe that one doesn't have this flag?)
I can provide that also, and I can upload another version clangd log which without -match flag (by add configuration to .clangd file, instead of remove flags from the build system).

Both of them will work as expected. But bear version have -mcpu -march -mabi flags, meson version doesn't have those flags.

bear version:
[compile_commands.json](https://github.com/clangd/vscode-clangd/files/14691861/compile_commands.json)
[clangd.json](https://github.com/clangd/vscode-clangd/files/14691904/clangd.json)
[clangd-log-from-vscode-output-bear.txt](https://github.com/clangd/vscode-clangd/files/14691906/clangd-log-from-vscode-output-bear.txt)

meson version without -march:
[compile_commands.json](https://github.com/clangd/vscode-clangd/files/14691942/compile_commands.json)
[clangd.json](https://github.com/clangd/vscode-clangd/files/14691944/clangd.json)
[clangd-log-from-vscode-output-without-march.txt](https://github.com/clangd/vscode-clangd/files/14691940/clangd-log-from-vscode-output-without-march.txt)

**Comment by HighCommander4** [comment]
A potentially relevant difference is that with `bear`, the command contains `--target=riscv64-unknown-elf`, so clangd doesn't need to look at the `-march` to try to determine the target.

Anyways, it sounds like you've got it working.

**Comment by ZZH-Finalize** [comment]
Yes, thanks for the help.

**Comment by ZZH-Finalize** [comment]
I have to say I made a mistake that I forgot the compiler is different between the meson case and the bear case.

And I noticed that all of these three configurations will work, so here is the question, does clangd parse the name of compiler to get target information? When I set the compiler to "riscv64-unknow-elf-gcc", It could work with the "-mabi -march" flags, but when I set it to "riscv-none-elf-gcc" it will not work because of clangd couldn't get the correct target information from compiler name, then it tries to parse the "-march -mabi" flags and met another error. Is that correct?

![image](https://github.com/clangd/vscode-clangd/assets/33342565/20880a34-fe2f-41d8-8d9b-380690dcf739)
![image](https://github.com/clangd/vscode-clangd/assets/33342565/9b8adf94-7754-419f-8341-812fa830e024)
![image](https://github.com/clangd/vscode-clangd/assets/33342565/068ca86a-e2bf-4010-88df-cbb3e0153eae)

**Comment by HighCommander4** [comment]
Yes, clangd tries to infer the target by parsing the compiler executable name (that happens [here](https://searchfox.org/llvm/rev/02cb89b36a7ae9be4ab657306b69dc9d2830d0d5/clang-tools-extra/clangd/CompileCommands.cpp#314) in the code).
