### ISSUE TITLE
A bug about the "Show Code Actions"

### ISSUE THREAD

**Issue by BrikeX** [clangd/vscode-clangd#614]
A blue lightbulb appears when clangd detects an issue and a preferred quick fix is available. But the blue bulb won't go away after the issue is fixed.

**System information**
Clangd version : 17.0.3
clangd extension version: 0.1.28
Operating system: Linux Mint 21.3
VS Code: March 2024 (version 1.88)

**Comment by BrikeX** [comment]
![Screenshot from 2024-04-07 01-32-20](https://github.com/clangd/vscode-clangd/assets/42525829/fe542382-5298-4114-8cf9-d1f59d47be91)
![Screenshot from 2024-04-07 01-32-33](https://github.com/clangd/vscode-clangd/assets/42525829/daa979ea-9882-4384-b624-2b1f448e09e7)

**Comment by HighCommander4** [comment]
I can't reproduce this, but based on the symptoms it seems more likely to be an issue with the editor (vscode) itself rather than the vscode-clangd plugin.

**Comment by emrekovanci** [comment]
I'm having the same problem too.

**System information:**
Clangd version : 18.1.2
clangd extension version: 0.1.28
Operating system: Windows 11
VS Code: 1.88.1

**Comment by BrikeX** [comment]
This bug is reported at here: https://github.com/microsoft/vscode/issues/209762

**Comment by emrekovanci** [comment]
Thanks for info, i added the minimal how to reproduce, maybe it will help.
