### ISSUE TITLE
 The issue revolves around the inability to locate header files correctly.

### ISSUE THREAD

**Issue by DYAAL** [clangd/vscode-clangd#617]
The problem I'm encountering is that I can't seem to locate header files correctly when using this plugin in vscode on Windows. Even though I've generated compile_commands.json using cmake or other tools, the plugin still fails to locate the header files properly. Is there any way to fix this bug?

**Comment by HighCommander4** [comment]
Please start by reviewing the Troubleshooting page starting from https://clangd.llvm.org/troubleshooting#cant-find-includes-within-your-project.

If the answers there do not resolve your problem, please provide details as requested in the issue template. Quoting the relevant parts:

 * If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).
 * Please attach the clangd log from the "Output" window if you can. If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
