### ISSUE TITLE
Does clangd support adding squiggles for unused variables and functions?

### ISSUE THREAD

**Issue by laplacedoge** [clangd/vscode-clangd#618]
Does clangd support adding squiggles for unused variables and functions?

**Comment by HighCommander4** [comment]
Clangd will show whatever diagnostics the clang compiler or clang-tidy can produce on a codebase.

For unused variables and functions, have a look at https://clang.llvm.org/docs/DiagnosticsReference.html for the relevant clang compiler flags that turn them on, and https://clangd.llvm.org/installation#project-setup about how to tell clangd about compiler flags (see also https://clangd.llvm.org/config.html).

**Comment by laplacedoge** [comment]
> Clangd can show whatever diagnostics the clang compiler or clang-tidy can produce on a codebase.
> 
> For unused variables and functions, have a look at https://clang.llvm.org/docs/DiagnosticsReference.html for the relevant clang compiler flags that turn them on, and https://clangd.llvm.org/installation#project-setup about how to tell clangd about compiler flags (see also https://clangd.llvm.org/config.html).

Really appreciate you providing this useful information. I will close this issue.

**Comment by laplacedoge** [comment]
> Clangd can show whatever diagnostics the clang compiler or clang-tidy can produce on a codebase.
> 
> For unused variables and functions, have a look at https://clang.llvm.org/docs/DiagnosticsReference.html for the relevant clang compiler flags that turn them on, and https://clangd.llvm.org/installation#project-setup about how to tell clangd about compiler flags (see also https://clangd.llvm.org/config.html).

@HighCommander4 Really appreciate you providing this useful information. I will close this issue.
