### ISSUE TITLE
Allow returning isIncomplete from clangd instead of forcing it to true

### ISSUE THREAD

**Issue by OlegOAndreev** [clangd/vscode-clangd#62]
Currently the vscode-clangd forces the isIncomplete flag to true, which makes autocompletion in large codebases (e.g. LLVM) fell sluggish. This is especially noticeable when developing on remote server.

Would you be interested in reviewing a PR adding a new setting "serverSideRanking" (set to true by default) which will disable the current isIncomplete override if set to false?

**Comment by hokein** [comment]
> Currently the vscode-clangd forces the isIncomplete flag to true, 

yeah, unfortunately, this is our workaround on making VSCode respect ranking from clangd

> which makes autocompletion in large codebases (e.g. LLVM) fell sluggish. This is especially noticeable when developing on remote server.

this is unexpected. We have made a lot of effort to make code-completion fast. Interestingly, I'm doing development in LLVM with VSCode on a remote machine, I haven't seen that code completion is slow.

It would be nice if you can share more details on the issue. In clangd [logs](http://clangd.llvm.org/troubleshooting.html#gathering-logs), you will find something like:

```
I[13:46:11.880] <-- textDocument/completion(75)
....
I[13:46:11.947] --> reply:textDocument/completion(75) 67 ms
```

**Comment by OlegOAndreev** [comment]
Thanks for reply! I see the following results on my SSH machine (ping ~20ms): average textDocument/completion is 120ms, which makes the completion lag behind the typing, e.g. when completing

`std::string s;
s.`
