### ISSUE TITLE
quick fix can't show add definition to .cpp files?

### ISSUE THREAD

**Issue by aiyolo** [clangd/vscode-clangd#620]
when I use other IDE, after I write function decraretion in .h file, I can use alt+enter to add an empty definition to .cpp files. It seems that clangd doesn't supprt this feature. 

I just wonder that people using clangd how to deal with this situation?

**Comment by HighCommander4** [comment]
If you type an empty definition (`{}` instead of `;` at the end of the function), then a "Move function body out of line" code action is available.

**Comment by HighCommander4** [comment]
For a code action that works on declarations, we have https://github.com/clangd/clangd/issues/445 on file.

**Comment by HighCommander4** [comment]
Duplicate of https://github.com/clangd/clangd/issues/445
