### ISSUE TITLE
Cannot override "clangd.path" per-workspace any more

### ISSUE THREAD

**Issue by HighCommander4** [clangd/vscode-clangd#64]
With vscode-clangd trunk, "clangd.path" cannot be overridden in Workspace settings any more, only User settings. This was regressed by #56, which made the pref `scope=machine`.

From the [vscode docs](https://code.visualstudio.com/api/references/contribution-points), the description of `scope=machine` is:

> `machine` - Machine specific settings that can be set in user or remote settings. For example, an installation path which shouldn't be shared across machines.

Note, it doesn't mention workspace settings.

I believe being able to override the clangd path per-workspace is useful. For example, I have two local clangd builds, a development build and a stable build, and it's useful to be able to run different ones in different workspaces.

There is a `machine-overridable` scope which does allow overriding in workspace settings perhaps we can use that instead:

> `machine-overridable` - Machine specific settings that can be overridden by workspace or folder settings.

**Comment by hokein** [comment]
Thanks for the report. I should have tested more about it locally (I test it with my personal workflow, which is fairly simple, just a single workspace with user setting).

> Note, it doesn't mention workspace settings.

> I believe being able to override the clangd path per-workspace is useful. For example, I have two local clangd builds, a development build and a stable build, and it's useful to be able to run different ones in different workspaces.

agree, that's unexpected. 

> There is a machine-overridable scope which does allow overriding in workspace settings perhaps we can use that instead:

this sounds reasonable to me, do you mind trying this and verifying it works on your case, and sending a PR to fix this? Thanks!

**Comment by HighCommander4** [comment]
> this sounds reasonable to me, do you mind trying this and verifying it works on your case, and sending a PR to fix this? 

Yup, works for me. PR at #65.
