### ISSUE TITLE
Highlighting broken in headers

### ISSUE THREAD

**Issue by MarkLagodych** [clangd/vscode-clangd#647]
The highlighting is wrong in headers, however it is correct in normal source files.

Test code snippet:

```c
struct A { struct A const */**/ a; };
extern struct A const */**/ a;
void f(struct A const */**/ a);
struct A const */**/ g(struct A const */**/ a);
```

Actual result (header):

![image](https://github.com/clangd/vscode-clangd/assets/70224579/362c4a26-41dc-4806-b68c-16553f9265d5)

Expected result (source file):

![image](https://github.com/clangd/vscode-clangd/assets/70224579/876aee69-acec-452b-bbd4-9ee2f356f2dd)

**Logs**
[clangd-log.txt](https://github.com/user-attachments/files/16060051/clangd-log.txt)

**System information**
clangd version: 18.1.3
clangd extension version: 0.1.28
vscode version: 1.90.2/flatpak
operating system: Fedora Linux 40 x86_64

**Comment by HighCommander4** [comment]
The tokens that are colored differently between the two screenshots are `struct`, `const`, and `/**/`.

These tokens are not colored by clangd (clangd only colors semantic tokens, mostly identifiers), they are colored on the client-side by vscode.

Therefore, please report the issue to the client-side coloring engine at https://github.com/jeff-hykin/better-cpp-syntax (this is what vscode uses).

Alternatively, I would recommend using this alterantive client-side coloring engine which works better in my experience: https://marketplace.visualstudio.com/items?itemName=daiyousei-qz.minimal-cpp-syntax

**Comment by MarkLagodych** [comment]
minimal-cpp-syntax worked well enough for me, though `struct` is still highlighted differently between headers and source files.
Thank you!

**Comment by HighCommander4** [comment]
> though `struct` is still highlighted differently between headers and source files

If you're interested in finding out more about this remaining discrepancy, a helpful VSCode command to know about is "Developer: Inspect Editor Tokens and Scopes". This will tell you information about where the color of the token at the editor caret location is coming from.
