### ISSUE TITLE
How to use the exposed API that other extensions can consume?

### ISSUE THREAD

**Issue by ccsyt1205** [clangd/vscode-clangd#656]
I read the README file in vscode-clangd-master/api/README.md, and I want to consume the exposed provideHover function to obtain the ast.kind. However, I encountered problem. It did't work, could you please help me?
I use the exposed function like this:
![image](https://github.com/user-attachments/assets/e1eba148-f395-4dfa-a486-573d0110d1b9)
and the result:
![image](https://github.com/user-attachments/assets/39c59ddc-c790-4e99-ba21-a6f19bac5826)
'clangdExtension' just doesn't have the property 'activate', so it's undefined. Could you please show me a more detailed demo using the exposed API? Thanks a lot!

**Comment by HighCommander4** [comment]
> Could you please show me a more detailed demo using the exposed API? Thanks a lot!

I have the example written up in a complete repository at https://github.com/HighCommander4/vscode-clangd-api-example; let me know if that helps.

**Comment by ccsyt1205** [comment]
> > Could you please show me a more detailed demo using the exposed API? Thanks a lot!
> 
> I have the example written up in a complete repository at https://github.com/HighCommander4/vscode-clangd-api-example; let me know if that helps.

It works, thank you very much. This problem has been solved, thanks a lot
