### ISSUE TITLE
How to get the "Type" property using the exposed API

### ISSUE THREAD

**Issue by ccsyt1205** [clangd/vscode-clangd#658]
Dear author, Sorry to disturb you again, I want to get the "type" property of a ASTNode. Just like this:
![image](https://github.com/user-attachments/assets/6154088f-51cc-4c3b-b0aa-0b2f3abfa06b)
I tried the API that clangd extension exposes, and successfully got the ASTNode. However, after I console.log the ASTNode, I could't find the "type" property, just like this:
![image](https://github.com/user-attachments/assets/8b1ed1e8-6e89-43fb-93f4-175bfc8f7ab5)
and I saw the interface of ASTNode is like this:
![image](https://github.com/user-attachments/assets/f8af7944-3cd4-4e79-982e-ce055b406fb3)
It surely doesn't have the "type" property. But, how does the extension get the "type" property? Could you please expose it? It's very useful. 
Longing for your reply, thanks a lot ^.^

**Comment by HighCommander4** [comment]
> how does the extension get the "type" property?

The place where you are seeing the `Type: ` is the hover popup.

The extension gets the contents of this popup from the server using the `textDocument/hover` request as documented [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_hover).

So you would have to make that request via `api.languageClient` and look in the response for the `Type: `.

**Comment by ccsyt1205** [comment]
> > how does the extension get the "type" property?
> 
> The place where you are seeing the `Type: ` is the hover popup.
> 
> The extension gets the contents of this popup from the server using the `textDocument/hover` request as documented [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_hover).
> 
> So you would have to make that request via `api.languageClient` (rather than `textDocument/ast`) and look in the response for the `Type: `.

I tried as follow:
1. I Register a command like this
![image](https://github.com/user-attachments/assets/5fcb49b7-192d-4be6-9ef8-e16fb6e516db)
2. And the function 'getHoverforPostion' I write it like this
![image](https://github.com/user-attachments/assets/75b71a5b-fc82-4941-b824-2d5772ab88c7)
3. However, after I run the command registered in step1, I saw the response is "null".
![image](https://github.com/user-attachments/assets/8556a5d4-3ae5-4405-87cd-20bcd32c7e9e)
4. Surely I did't request correctly, but I'm not able to figure out where the mistake is. I searched the source code of clangd and I can't see usage related to 'textDocument/hover'. 
![image](https://github.com/user-attachments/assets/4745d19d-7a67-47a6-84bc-2eaa248d584a)

Could you please help me figure out where my mistake is in my code? thanks a lot! Or, do you have a demo just like the AST demo you have given me a few day ago [demo](https://github.com/HighCommander4/vscode-clangd-api-example)? Badly thanks

**Comment by HighCommander4** [comment]
Can you get [logs](https://clangd.llvm.org/troubleshooting.html#gathering-logs) from clangd in a session where you perform this operation with the client?

**Comment by ccsyt1205** [comment]
> Can you get [logs](https://clangd.llvm.org/troubleshooting.html#gathering-logs) from clangd in a session where you perform this operation with the client?

Sorry, my code works correctly. The mistake is, if the line VSCODE editor we see is t, then the line property in Position object is (t-1)
