### ISSUE TITLE
Option to disable showing clangd status in vscode's status bar.

### ISSUE THREAD

**Issue by rekaerst** [clangd/vscode-clangd#66]
Can we have an option to disable showing clangd's status? There are already too many items in vscode's status bar.
![image](https://user-images.githubusercontent.com/52642831/92148155-ba60fe80-ee4e-11ea-8cfa-6a936b241400.png)

**Comment by ell1e** [comment]
I would really like this as well, since the constant flashing while typing can be distracting and it doesn't really provide any info that is interesting to me at all as a user.

**Comment by njames93** [comment]
You know you can disable that in vscode. Just right click the status bar and unselect clangd.

**Comment by rekaerst** [comment]
TIL

**Comment by rekaerst** [comment]
TIL
