### ISSUE TITLE
How does clangd extension be able to  offer the ability “jump to defination”? Is that implemented through ASTNode?

### ISSUE THREAD

**Issue by ccsyt1205** [clangd/vscode-clangd#660]
Dear author, 
  I find that the “jump to defination” offered by clangd extension in VSCode is the most accurate one I've tried, better than the C/C++ extension. I'm developping an automatic tool which analyzes user's c language code and do some optimization. And, I wonder how clangd implements the ability “jump to defination”, could you please expose it just like the ASTNode api?
  The key challenge is to find where the defination of a variable is. Is that implemented through ASTNode? I want to learn the clangd's implementation, thanks a lot!

**Comment by HighCommander4** [comment]
"Go to definition" is implemented using the standard `"textDocument/definition"` request documented [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_definition).

Generally speaking, you can use the [`languageClient`](https://github.com/clangd/vscode-clangd/blob/f44f030866aa07114d0bb9b64b5e6b39b6208b62/api/vscode-clangd.d.ts#L11) object exposed by the API to send any of the standard requests documented on that page (and the corresponding parameter and response types are provided by the `vscode-languageclient` package).

**Comment by ccsyt1205** [comment]
> textDocument/definition

Cool! I successfully get the definitionInfo by using "textDocument/definition" request. The response contains the "range" property where the definition lies. And then I can use the editor.revealRange and editor.selection api to jump to the location provided by "definitionResponse[0].range.start". You're really nice. Thank you very much!
