### ISSUE TITLE
Publish extension API package to npm

### ISSUE THREAD

**Issue by wss29** [clangd/vscode-clangd#670]
Note: we mostly implement features in the clangd language server, and rely on Microsoft's LSP client framework to expose these in VSCode. Features requiring a lot of VSCode-specific work are unlikely to be implemented.
It is necessary to publish the extension API to npm and yarn for third-party extension use, this can avoid  Error: command 'clangd.applyFix' already exists
details discussed is [here](https://github.com/clangd/vscode-clangd/issues/668)

**Comment by HighCommander4** [comment]
Thanks for filing. To provide some context, in https://github.com/clangd/vscode-clangd/pull/575 we added code for a [new npm package](https://github.com/clangd/vscode-clangd/blob/master/api/package.json) in this repository called `@clangd/vscode-clangd`, to host the type definition files for the extension API added in that PR.

This package should be published to the npm registry, but I don't think I have the permissions to do that. I think the people who do have such permissions might be @sam-mccall and @kadircet.

As for yarn, I'm not quite sure how that works. I do see that `@clangd/install` shows up at https://yarnpkg.com/package?q=clangd&name=%40clangd%2Finstall; I suspect this may happen automatically (it's mirrored from npm)? If that's not the case and it requires a separate account and publishing process, then that's best discussed in a separate issue after this one is resolved.

**Comment by parisa-mchp** [comment]
Any word on this? It's not a need-to-have, but it would make the API easier to use.

**Comment by HighCommander4** [comment]
@kadircet or @hokein, could you help with publishing this npm package please, or alternatively add me to the npmjs account so that I can do it?

**Comment by kadircet** [comment]
hi @HighCommander4, i am happy to add you to npmjs/clangd org. can you provide your username?

apart from that i tried cutting a new release, but registry is set to github ATM:
```
    "publishConfig": {
        "registry": "https://npm.pkg.github.com"
    },
```

moreover, looks like someone tried .. something for https://www.npmjs.com/package/vscode-clangd. Hence we might need to do some work to reclaim it. I don't think i'll have the capacity to drive that myself, but I am happy to provide any information you might need along the way (feel free to reach out via kadircet@google.com).

**Comment by HighCommander4** [comment]
> hi @HighCommander4, i am happy to add you to npmjs/clangd org. can you provide your username?

Thanks. Username is "nridge".

> apart from that i tried cutting a new release, but registry is set to github ATM:
> 
> ```
>     "publishConfig": {
>         "registry": "https://npm.pkg.github.com"
>     },
> ```

@thegecko, this `"registry"` key comes from your original patch at https://github.com/clangd/vscode-clangd/pull/575.

Could you clarify what the implications are of using this URL vs. https://registry.npmjs.org/ ?

> moreover, looks like someone tried .. something for https://www.npmjs.com/package/vscode-clangd. Hence we might need to do some work to reclaim it. [...]

Note that this may not be relevant to the API package we're trying to publish, whose package name is `@clangd/vscode-clangd`.

**Comment by thegecko** [comment]
> Could you clarify what the implications are of using this URL vs. https://registry.npmjs.org/ ?

This URL points at the GitHub npm registry in the case that we want to publish the example there rather than on the npm registry.

If the example is for npm, it should be fine to remove this entry from package.json.

**Comment by HighCommander4** [comment]
> > Could you clarify what the implications are of using this URL vs. https://registry.npmjs.org/ ?
> 
> This URL points at the GitHub npm registry in the case that we want to publish the example there rather than on the npm registry.
> 
> If the example is for npm, it should be fine to remove this entry from package.json.

What does it mean for a user of the API? Would they have to run something different from `npm install @clangd/vscode-clangd`, or perform some additional configuration, if the GitHub npm registry is used?

**Comment by thegecko** [comment]
Apologies, I copied the wrong line above..

> "registry": "https://npm.pkg.github.com"

Is the GitHub one. Users would have to set up their `.npmrc` to have a API key because I think GH now insist on it. I feel this adds complication and we should just use npm. This is the default registry if none is set, so propose we simply delete:

```json
    "publishConfig": {
        "registry": "https://npm.pkg.github.com"
    },
```

**Comment by HighCommander4** [comment]
> Apologies, I copied the wrong line above..
> 
> > "registry": "https://npm.pkg.github.com"
> 
> Is the GitHub one. Users would have to set up their `.npmrc` to have a API key because I think GH now insist on it. I feel this adds complication and we should just use npm. This is the default registry if none is set, so propose we simply delete:
> 
> ```json
>     "publishConfig": {
>         "registry": "https://npm.pkg.github.com"
>     },
> ```

Thanks. I sent out https://github.com/clangd/vscode-clangd/pull/746 with this change.

**Comment by HighCommander4** [comment]
> Thanks. I sent out #746 with this change.

Merged.

@kadircet this should now be ready for publishing (or giving me permissions to do so).

**Comment by kadircet** [comment]
> or giving me permissions to do so

i've sent an invite to https://www.npmjs.com/~nridge couple days ago. LMK if it didn't arrive

**Comment by HighCommander4** [comment]
> i've sent an invite to https://www.npmjs.com/~nridge couple days ago. LMK if it didn't arrive

I'm not seeing one. (Maybe I'm not looking in the right place?)

**Comment by HighCommander4** [comment]
Thanks!

Package published at https://www.npmjs.com/package/@clangd/vscode-clangd.

**Comment by HighCommander4** [comment]
> As for yarn, I'm not quite sure how that works. I do see that `@clangd/install` shows up at https://yarnpkg.com/package?q=clangd&name=%40clangd%2Finstall; I suspect this may happen automatically (it's mirrored from npm)?

The `@clangd/vscode-clangd` package did show up automatically at https://yarnpkg.com/package?q=clangd&name=%40clangd%2Fvscode-clangd as well, so I guess it's mirrored from npm.

Anyways, I think we can close this.
