### ISSUE TITLE
I set clang-tidy-checks, but it still reports errors.

### ISSUE THREAD

**Issue by Qizhi697** [clangd/vscode-clangd#674]
I set  "--clang-tidy-checks=-cppcoreguidelines-init-variables" in setting.json，but it still reports errors
<img width="799" alt="image" src="https://github.com/user-attachments/assets/db0de0fe-b171-4857-91ba-61fbfd19174b">

**Comment by HighCommander4** [comment]
`--clang-tidy-checks` is not an option listed in `clangd --help`.

The way to disable clang-tidy checks for clangd is via the config file, see https://clangd.llvm.org/config.html#clangtidy.

**Comment by Qizhi697** [comment]
thanks
