### ISSUE TITLE
[Question]: What do I need to do to be able to use `clangd` for non-CMake repositories?

### ISSUE THREAD

**Issue by just-ero** [clangd/vscode-clangd#682]
Hello! Sorry if this is a bad place to ask this.

I would like to use `vscode-clangd` with the [Unitry-Technologies/mono](https://github.com/Unity-Technologies/mono) repository. It does not contain `CMakeLists.txt` files, but instead `Makefile.am` files. As I'm not primarily a C/C++ developer, I'm not sure what tools are needed to generate the required `compile_commands.json` file to allow `clangd` to function.  

Does anyone have an idea what I need to do to make this work for me?

**Comment by HighCommander4** [comment]
Please have a look at https://clangd.llvm.org/installation#project-setup, in particular the section titled "Other build systems, using Bear".

Note also that on Windows, the following tool can be used in place of Bear: https://github.com/nickdiego/compiledb.

**Comment by just-ero** [comment]
It appears those tools work only after (or in conjuction with) building the project.

This goes beyond the responsibility of this repo, but how do I build these `Makefile.am` files on Windows? I've tried to do some research, but everything I'm reading and trying leads me to believe that `make` is not easily available on Windows.

**Comment by HighCommander4** [comment]
> This goes beyond the responsibility of this repo, but how do I build these `Makefile.am` files on Windows? I've tried to do some research, but everything I'm reading and trying leads me to believe that `make` is not easily available on Windows.

I'm not familiar with this project, but I see that the documentation has a section on [building on Windows](https://github.com/Unity-Technologies/mono/blob/unity-main/Unity-build.md#build-on-windows), so at least the project supports being built on Windows.

I think the idea behind tools like `bear` and `compiledb` is that they can be put before any build command, it doesn't have to be `make` -- so I would suggest trying to run the build script mentioned in the project's Windows build instructions with `compiledb` in front of it.

**Comment by just-ero** [comment]
The branch I'm trying to build (`unity-2017.1-mbe`) doesn't appear to have those build scripts, unfortunately, and seems to require some incredibly out-of-date software. I'm not sure whether any of the more recent branches will work, but I appreciate the help. I'll figure it out. Thank you.
