### ISSUE TITLE
delete[] and new not colored

### ISSUE THREAD

**Issue by ChenCuiPlasma** [clangd/vscode-clangd#685]
Please describe the problem.
I recently found that after starting the clangd in the vscode, the "new" and "delete" in words "new double []" and "delete []" will be changed to white rather than the purple highlight it originally had. I have attached two screenshots here information. 
Before start any add-on of the vs code:
<img width="771" alt="image" src="https://github.com/user-attachments/assets/44790325-94ee-472d-b02d-735e5051d962">

After only starting the clangd:
<img width="771" alt="image" src="https://github.com/user-attachments/assets/d385920c-4e0d-4a1e-a8f3-7643889014fb">

**System information**
Clangd version (from the log, or `clangd --version`): Homebrew 18.1.8
clangd extension version: v0.1.29
VS Code Information: Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

**Comment by HighCommander4** [comment]
clangd assigns the `new` and `delete` tokens a semantic token of kind `operator` (https://clangd.llvm.org/features#kinds).

If you prefer it to be colored differently, two options are:
 * customize the color of `operator` tokens using vscode's `editor.semanticTokenColorCustomizations` settings (see [this article](https://medium.com/@danromans/how-to-customize-semantic-token-colorization-with-visual-studio-code-ac3eab96141b) for a guide)
 * disable clangd's coloring of `operator` tokens using https://clangd.llvm.org/config.html#semantic-tokens (then the editor will fall back to the TextMate color that you see before starting clangd)

**Comment by HighCommander4** [comment]
> I noticed that, if I write something like "new variable_name" or "delete variable_name", the clangd gives the "new" or "delete" a correct highlight. However, if I try to use the "new" or "delete" to dynamically allocate an array or release the allocated array, like doing "new double [somenumber]" or "delete [] array_name", the clangd will make the new and delete highlighted as white, which seems to have something wrong.

I can't reproduce this, for me it looks the same (white) in all four cases.

Can you try with extensions other than clangd disabled, and your vscode user / workspace settings (temporarily) blank?

**Comment by HighCommander4** [comment]
> Can I inquire if all of the "operator" category are highlighted into white by the clangd?

Clangd doesn't specify any colors, it just specifies a token type from [the list in the Language Server Protocol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/). The decision to assign a color like white for a token type like `operator` is made by the client (vscode), based on the theme and any customizations in user settings.

**Comment by HighCommander4** [comment]
> So based on my understanding, if no extensions is activated, the VS code, by using its default dark scheme, will assign all of the operators with "white" color. And VS code does not put "new" and "delete" into the category of operator, so it highlights these two into "purple" by TextMate.

To be a bit more precise, I believe what happens is that the "white" color is associated with the `"keyword.operator"` TextMate scope [here](https://github.com/microsoft/vscode/blob/b1d98891931b942ce26ce9ec66327e372e461e1c/extensions/theme-defaults/themes/dark_vs.json#L335-L340), but the `new` and `delete` keywords have more specific scopes, `"keyword.operator.new"` and `"keyword.operator.delete"`, which are associated with the "purple" color [here](https://github.com/microsoft/vscode/blob/b1d98891931b942ce26ce9ec66327e372e461e1c/extensions/theme-defaults/themes/dark_plus.json#L73-L87).

Whereas, with the semantic tokens sent by the server, it's all one token kind, `operator`, which gets mapped to the TextMate scope `"keyword.operator"` (and therefore the "white" color) [here](https://github.com/microsoft/vscode/blob/b1d98891931b942ce26ce9ec66327e372e461e1c/src/vs/platform/theme/common/tokenClassificationRegistry.ts#L548).

> Can I further inquire what is identified by the clangd as an operator?

It includes the punctuation tokens of unary operators (e.g. `!`), binary operators (`+`), and the ternary operator (`?` and `:`), as new as `new` and `delete`.

---

For what it's worth, when the `operator` semantic highlighting was added to clangd in https://reviews.llvm.org/D136594, I did bring up the concern that this is mostly useful for highlighting **overloaded** operators, and that the highlighting of built-in operators may be better left to the client; but ultimately, the patch did add the highlighting for built-in operators as well.

**Comment by Scorg** [comment]
Hello. So what is the resolution here? Having symbolic and keyword operators be the same color is kind of unsatisfying. Is there a chance to separate them into different categories?

**Comment by HighCommander4** [comment]
> Hello. So what is the resolution here? Having symbolic and keyword operators be the same color is kind of unsatisfying. Is there a chance to separate them into different categories?

I think the simplest way is the second bullet point from [this comment](https://github.com/clangd/vscode-clangd/issues/685#issuecomment-2351126125):

>  * disable clangd's coloring of `operator` tokens using https://clangd.llvm.org/config.html#semantic-tokens (then the editor will fall back to the TextMate color that you see before starting clangd)

This can be done by adding the following to `.clangd`:

```yaml
SemanticTokens:
  DisabledKinds: [Operator]
```
