### ISSUE TITLE
Add option to disable clangd extension hover tooltips

### ISSUE THREAD

**Issue by FilipNur** [clangd/vscode-clangd#692]
As in the title. Asking for this feature, because clangd can be used for intellisense and IWYU warnings, but used hover tooltips might be from c++ vscode extension. In c++ extension hovers can be disabled so only clangd tooltips are visible, but not the other way: using c++ extension hovers and disabling clangd extension tooltips.

**Comment by HighCommander4** [comment]
This can be implemented using middleware similar to https://github.com/clangd/vscode-clangd/pull/591.

**Comment by HighCommander4** [comment]
Proposed patch: https://github.com/clangd/vscode-clangd/pull/703

**Comment by HighCommander4** [comment]
Released in 0.1.30.
