### ISSUE TITLE
Incorrect brackets match due to macro judgment

### ISSUE THREAD

**Issue by Shapeno** [clangd/vscode-clangd#706]
The macro definition judgment results in an incorrect brackets match :   
![image](https://github.com/user-attachments/assets/b27ea7ab-4224-43c5-b534-8d2123792995)
A simple example is given above to illustrate this bug, where the brackets in the **inactive area** match with the brackets in the **active area**, resulting in inconsistent results that are not as expected.    
This doesn't cause the code to fold incorrectly, but it does affect the coding experience to some extent.

**Comment by HighCommander4** [comment]
Bracket matching is not done by the vscode-clangd plugin, it's done by vscode itself; kindly report the issue at https://github.com/microsoft/vscode/.
