### ISSUE TITLE
Go to definition for auto keyword

### ISSUE THREAD

**Issue by stianval** [clangd/vscode-clangd#71]
Go to definition for `auto` types does not seem to work, even though the type seems to be deducted correctly when hovering the auto keyword, and for suggestions when using `.` or `->` with the type.

```c++
struct Foo {
    int a;
};

int main() {
    Foo foo;
    auto &bar = foo;
}
```
Not possible to go to definition when selecting the `auto` before `bar`. Popup label says `No definition found for 'auto'`.

Expected behavior: Navigational jump to the definition of `struct Foo`

Attaching simple setup demonstrating issue.
[no-go-to-definition-for-auto.zip](https://github.com/clangd/vscode-clangd/files/5232178/no-go-to-definition-for-auto.zip)

**System information**
Clangd version (from the log, or `clangd --version`): clangd version 10.0.0
clangd extension version: 0.1.7
Operating system: Ubuntu 19.10

**Comment by kadircet** [comment]
see https://github.com/clangd/clangd/issues/532
