### ISSUE TITLE
Enable and Disable vscode-clangd via settings.json

### ISSUE THREAD

**Issue by akhodeir** [clangd/vscode-clangd#718]
I use vscode-clangd for work and microsoft extensions for my open source projects.

to disable the microsoft extension for my work projects, I use following configuration in settings.jon

```
"C_Cpp.intelliSenseEngine": "disabled",
```
I can't find similar configuration for clangd extensions.

it is really handy if I can hardcode this configuration in settings.json for each project I have instead of disable the whole extension and enable the other via extensions toolbar.

**Comment by HighCommander4** [comment]
Fixed in #636
