### ISSUE TITLE
Semantic highlight does not work 

### ISSUE THREAD

**Issue by yuanchen-zhu** [clangd/vscode-clangd#72]
My current project uses Windows/cmake/clang-cl/ninja as the main setup. I turned off the official C/C++ extension to isolate the issue.  clangd works and does return the correct type and documentation for symbols in the source files. However, semantic highlighting does not seem to work. Below is a screen snippet that shows the correct on-hover doc but no semantic token type

<img width="842" alt="Code_043" src="https://user-images.githubusercontent.com/23563836/93661927-91c13300-fa10-11ea-82a9-86cf272b46eb.png">

**Logs**

Here's some log for opening a simple file (not the one shown in the screenshot)

[vscode-clangd.log](https://github.com/clangd/vscode-clangd/files/5249306/vscode-clangd.log)

**System information**
Clangd version: 10.0.0
clangd extension version: 0.1.7
Operating system: Windows 10
VS Code version:  1.49.1

**Comment by Trass3r** [comment]
You need clangd 11 for the new highlighting.

**Comment by yuanchen-zhu** [comment]
Thank you! That indeed solved the problem!

Maybe a note can be added to either the changelog or the Details page so others can find about this tip more easily.

**Comment by Trass3r** [comment]
It is in the changelog fwiw.

**Comment by yuanchen-zhu** [comment]
Indeed it is! Somehow my eyes just missed what's in the parentheses. Sorry :)
