### ISSUE TITLE
Unknown command line arguments triggers an error for each file

### ISSUE THREAD

**Issue by theScrabi** [clangd/vscode-clangd#738]
Each file shows an error at the beginning. Also when opening a file in the explorer sidebar is marked red.
![Screenshot from 2024-11-29 08-13-32](https://github.com/user-attachments/assets/73f36387-d7f5-4bfb-abb4-92bc0c07d562)

**Logs**
Hoverging over the marked code reveals the following error:
```
Unknown argument: '-fno-reorder-functions'clang(drv_unknown_argument)
Unknown argument '-mlongcalls'; did you mean '-mlong-calls'?clang(drv_unknown_argument_with_suggestion)
```

**System information**
- The **clangd** version is the one recommended and installed by the extension:
clangd version 18.1.3 (https://github.com/llvm/llvm-project c13b7485b87909fcf739f62cfa382b55407433c0)
- The dev environment is a **dev container** based on the Zephyr's **docker image**: ghcr.io/zephyrproject-rtos/zephyr-build:v0.27.4, which intern is based on Ubuntu 22.04.5.
- The **VSCode** version is **1.95.3**
- Ths host is ubuntu 22.04.
- The **clangd extension** version is v0.1.33

**Comment by HighCommander4** [comment]
Compile commands given to clangd need to contain flags which are supported by clang.

If you're not using clang to compile your code, one solution is to use a [clangd config file](https://clangd.llvm.org/config.html#remove) to remove unsupported flags.

**Comment by theScrabi** [comment]
Aaah, I understand. These flags are coming from my `compile_commands.json` produced by CMake. Removing them using a clangd config file worked.
Thank you very much :).
