### ISSUE TITLE
go to definition does not work from header to implementation in c++

### ISSUE THREAD

**Issue by lijh8** [clangd/vscode-clangd#757]
1. firstly, do not navigate from definition `foo` in foo.cpp to declaration `foo` in foo.h, this kinda hides the issue;
2. close all opened tabs and reopen the editor;
3. from function call site `foo()` in main.cpp, can only go to declaration in foo.h; 
4. from function declaration `foo` in header foo.h, can not go to definition in foo.cpp; 

Tested with: VSCode 1.96.0.

By the way, both nvim-lsp and vim-lsp have the same issue, is this related to LSP server clangd?

```
// main.cpp
foo();
```

```
// foo.cpp
void foo(){}
```

```
// foo.h
#ifndef foo_h
#define foo_h

void foo();

#endif
```

**Logs**
Please attach the clangd log from the "Output" window if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`): Apple clangd version 14.0.0 (clang-1400.0.29.202) ;
clangd extension version: llvm-vs-code-extensions.vscode-clangd 0.1.33 ;
Operating system: macOS 12.7.6 (21H1320) ;
VSCode 1.96.0 ;

**Comment by HighCommander4** [comment]
Have you followed the steps at https://clangd.llvm.org/installation#project-setup including having a `compile_commands.json` file?

**Comment by lijh8** [comment]
After the entry of implementation file is added in compile_commands.json, it can navigate from the call location to the definition. But i remember this is not needed before.

Thanks

```
  {
    "directory": "/Users/user1/src/main/",
    "arguments": [
      "/usr/bin/clang++",
      "-std=c++2a",
      "-DSOMEDEF=With spaces, quotes and \\-es.",
      "-I/Users/ljh/Documents/hello_cpp/src/main/",
      "-c",
      "-o",
      "foo.o",
      "foo.cpp"
    ],
    "file": "foo.cpp"
  },
```
