### ISSUE TITLE
env var in clangd.path

### ISSUE THREAD

**Issue by gkarlos** [clangd/vscode-clangd#76]
Is it possible to use an environment variable in the `clangd.path` setting?
In other vscode settings it is possible to do `${env.VAR}/...` but that doesn't seem to work in `clangd.path`. Is there any alternative? If not, such a feature would be good to have.

**Comment by hokein** [comment]
It should be supported, the syntax is like `${env:Name}`.

**Comment by gkarlos** [comment]
Oh silly me. I only tried `${env.Name}` that i use in other plugin. Indeed in works. Thanks! (Closing)
