### ISSUE TITLE
New print function from c++23 causing spurious error

### ISSUE THREAD

**Issue by AWH1122** [clangd/vscode-clangd#761]
When typing the following code:

```c++
#include <print>

int main() {
 std::print("Hello world\n");
 return 0;
}
```

print on line 4 has a red underline with the following message: 'No member named 'print' in namespace 'std'clang(no_member)'

The code runs without errors.

**Logs**
Please attach the clangd log from the "Output" window if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`):

18.1.3

clangd extension version:

0.1.33

Operating system:

Ubuntu 24.04.1 LTS

**Comment by HighCommander4** [comment]
Have you followed the project setup steps at https://clangd.llvm.org/installation#project-setup?

**Comment by AWH1122** [comment]
Just had a look and this has fixed the issue. Thanks!
