### ISSUE TITLE
Support multiple compile_commands.json files

### ISSUE THREAD

**Issue by Volker-Weissmann** [clangd/vscode-clangd#82]
Currently, you can specify the path to your compile_commands.json file by setting the "compileCommands" in c_cpp_properties.json
It would be nice if you could specify a list of paths, each pointing to a compile_commands.json file. vscode should then read all specified compile_commands.json files and merge them (in memory).

**Comment by i-ky** [comment]
`c_cpp_properties.json` belongs to a [different extension](https://github.com/microsoft/vscode-cpptools).

**Comment by Volker-Weissmann** [comment]
You're right, I'm an idiot.
