### ISSUE TITLE
Disable function/method arugment insertion.!?

### ISSUE THREAD

**Issue by MK-Alias** [clangd/vscode-clangd#92]
Hi There,

As the title says I want to disable the insertion of method/function arguments as soon as I press **TAB** to complete the function/method name. I Basically just want the functionality that pressing the **"("** gives me (a hover with the signature help) when I press **TAB**. This might be a VScode feature somewhere butt I cannot seem to find it. 

Many thanks for any help on this. It's the only irritation I have with this plugin and other than this is works incredible!

**Comment by Kztpia** [comment]
clangd provid this completion result along with placeholder, 
use --function-arg-placeholders=0  to stop this.

**Comment by MK-Alias** [comment]
Thanks for your reply! I've just added the argument to clangd by adding it to my settings.json

```json
{
    "clangd.arguments": [
        "--function-arg-placeholders=0"
    ],
}
```

And the annoying placeholders are gone now. So thanks a lot. However, it is still not 100% perfect. Because the first argument of a function being auto-completed does not show the hover, it will now only popup after typing the first comma. Is there anyway to trigger it on the first argument?

**Comment by Kztpia** [comment]
It guess this is because of how signature help is triggered, like, by typing a "(" or a "," . But the completion result already includes the "(".  Then... you know the story.

And this option have a bug on funciont-like macro, refer to this issues for more detail. 
https://github.com/clangd/clangd/issues/922
