### ISSUE TITLE
Limit Memory Usage

### ISSUE THREAD

**Issue by Curve** [clangd/vscode-clangd#93]
Would it be possible to allow specifying something like a `maxMemoryUsage` setting?
The memory consumption on large files get so bad that it eats up all of my ram when editing really large files, it would be nice to have a setting to limit its memory usage similar to how CLion does it

**Comment by Trass3r** [comment]
First step: run clangd with LeakSanitizer and fix presumed leaks.

**Comment by hokein** [comment]
I think this is fixed in clangd side.
