### ISSUE TITLE
Error restarting server when using onConfigChanged

### ISSUE THREAD

**Issue by njames93** [clangd/vscode-clangd#98]
When using onConfigChanged and the compile_commands.json file gets updated I get an error when the extension tries to restart the server

![image](https://user-images.githubusercontent.com/5469473/98959857-9fb89f00-24fb-11eb-8a0a-6d07a422035e.png)

**System information**
Clangd version: trunk
clangd extension version: 0.18
Operating system: Ubuntu 20.04

**Comment by Trass3r** [comment]
Same here after choosing "yes, always".

**Comment by HighCommander4** [comment]
I tried this locally, but haven't been able to reproduce (clangd restarts successfully for me).

**Comment by HighCommander4** [comment]
Summarizing some discussion from the clangd Discord channel:

 * Shortly after the server starts up (more specifically, after the client receives the response to the `initialize` request from the server), the client registers the `clangd.applyFix` command (among others) using `vscode.commands.registerCommand()`.
 * When clangd is restarted, we call `ClangdContext.dispose()` followed by `ClangdContext.activate()`. `ClangdContext.dispose()` results in the `clangd.applyFix` command being un-registered (by calling the `Disposable` returned by `vscode.commands.registerCommand()`; there are several layers in between that I'm glossing over as I don't think it's super relevant). `ClangdContext.activate()` then starts the server again which will soon result in the command being registered again.
 * The observed error occurs if `vscode.commands.registerCommand("clangd.applyFix")` is called at a time when the command has not yet been un-registered. Normally, this shouldn't happen, and e.g. it doesn't when `clangd.restart` is invoked explicitly.
 * @njames93 has observed that `clangd.restart` is being invoked multiple times in quick succession due to `ConfigFileWatcher.handleConfigFilesChanged()` being called multiple times. This results in multiple clangd instances running in parallel for a brief time, which suggests the calls to `dispose()` and `activate()` are not being sequenced, leading to this error.

@rapgenic would you like to have a look at this, as it is a regression from #33?

**Comment by HighCommander4** [comment]
>     * @njames93 has observed that `clangd.restart` is being invoked multiple times in quick succession due to `ConfigFileWatcher.handleConfigFilesChanged()` being called multiple times.

@njames93 Perhaps the method you're using to update `compile_commands.json` is relevant here, e.g. if it's a process that modifies the file multiple times in quick succession, vs. making all the changes at once. Could you share some details on how you're updating `compile_commands.json`?

**Comment by njames93** [comment]
> @njames93 Perhaps the method you're using to update `compile_commands.json` is relevant here, e.g. if it's a process that modifies the file multiple times in quick succession, vs. making all the changes at once. Could you share some details on how you're updating `compile_commands.json`?
I'm just using the CMake Tools (https://github.com/microsoft/vscode-cmake-tools) extension with 
`"cmake.copyCompileCommands": "${workspaceFolder}/compile_commands.json"`
AFAIK this just passes `-DCMAKE_EXPORT_COMPILE_COMMANDS` then after cmake has done its thing, it copies it the compile_commands.json from the build directory to specified location.
In any case while this information should help for debugging, there should still be something in place to prevent this issue if the cause is rapid file modifications.

**Comment by Trass3r** [comment]
Same here. This might happen when you modify a cmake file and hit F7. The automatic file saving will trigger configuration and the build will start, also invoking cmake. A bug in the cmake tools I think.

**Comment by njames93** [comment]
> Same here. This might happen when you modify a cmake file and hit F7. The automatic file saving will trigger configuration and the build will start, also invoking cmake. A bug in the cmake tools I think.

I'm inclined to disagree, cmake tools making sure the database is up to date sounds like a feature. If it is the case tho that it is causing multiple rapid modifications to the database while running, that's definitely a bug on their part but even still it's not relevant here as even that shouldn't cause a crash here.

**Comment by rapgenic** [comment]
I have been experimenting a little right now, and according to what you reported, it would seem to be related to the command "clangd.restart" being called in small subsequent bursts.

However i tried @njames93 setup first, with a CMake project and the automatic copy in the same folder, without any problem.

What @Trass3r reported doesn't seem to cause any problem to vscode-clangd, even though the cmake extension complains that I'm trying to run two tasks in parallel (I'd agree that this is a cmake tools bug)

I even tried brute-forcing the clangd restart with the following (ugly) bash script:

```sh
#!/bin/bash

SLEEP=0.1
N=20

for ((i=1;i<=N;i++))
do
	echo "Restart $i"
	echo "1" >> compile_commands.json
	sleep $SLEEP
done
```
But still no error.

Also while looking at the source code I cannot find the place where the "clangd.applyFix" command is being registered... I am sure I am missing something, so forgive me if this is a dumb question

**Comment by njames93** [comment]
So its definitely something with how cmake-tools copies the compile_commands it seems. I added a log above here https://github.com/clangd/vscode-clangd/blob/1aa04ac919ecf93231f23c4e5b02935faff92703/src/config-file-watcher.ts#L40
```
[CMakeTools] 2020-11-13T16:56:32.167Z [info] [cmake] -- Configuring done
main.js:1337
[CMakeTools] 2020-11-13T16:56:37.052Z [info] [cmake] -- Generating done
main.js:1337
[CMakeTools] 2020-11-13T16:56:38.919Z [info] [cmake] -- Build files have been written to: /home/nathan/src/llvm-project/build/Release
main.js:1337
[CMakeTools] 2020-11-13T16:56:39.525Z [debug] [cmakefileapi-parser] Read reply folder: /home/nathan/src/llvm-project/build/Release/.cmake/api/v1/reply
main.js:1337
Unable to log remote console arguments Output omitted for a large object that exceeds the limits
C/C++ extension is not installed
main.js:17568
Command version test return code 1
main.js:14924
Command version test return code 0
main.js:14924
File Change: 'file:///home/nathan/src/llvm-project/compile_commands.json', newSize = 1114112, time = 16:56:43.279
config-file-watcher.js:47
File Change: 'file:///home/nathan/src/llvm-project/compile_commands.json', newSize = 2232320, time = 16:56:43.331
config-file-watcher.js:47
File Change: 'file:///home/nathan/src/llvm-project/compile_commands.json', newSize = 3473408, time = 16:56:43.383
config-file-watcher.js:47
File Change: 'file:///home/nathan/src/llvm-project/compile_commands.json', newSize = 4915200, time = 16:56:43.443
config-file-watcher.js:47
File Change: 'file:///home/nathan/src/llvm-project/compile_commands.json', newSize = 5898240, time = 16:56:43.487
config-file-watcher.js:47
C/C++ extension is not installed
main.js:17568
File Change: 'file:///home/nathan/src/llvm-project/compile_commands.json', newSize = 6769083, time = 16:56:43.527
```
Anyway this confirms that the cmake-tools extension is modifying the file multiple times, which in turn causes the handler to get executed multiple times. Maybe this needs fixing in cmake-tools, however the bug would be fixed here by introducing a small delay(maybe a couple seconds) and debouncing behaviour.

**Comment by HighCommander4** [comment]
> Also while looking at the source code I cannot find the place where the "clangd.applyFix" command is being registered... I am sure I am missing something, so forgive me if this is a dumb question

It happens in the LSP client libraries [here](https://github.com/microsoft/vscode-languageserver-node/blob/73ef9a6e19bda2e29e0d19a88f37f111f85e316b/client/src/common/client.ts#L2542). Clangd returns it as one of the commands in `ServerCapabilities.executeCommandProvider` in response to the [initialize request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize).

**Comment by rapgenic** [comment]
@HighCommander4 thank you, I thought it was something like that, just wanted to be sure.

@njames93 I will try to implement a debouncing mechanism, even though it is still not clear to me on which conditions this happens, because even brute-forcing the restart by writing multiple times the commands file i could not replicate the bug...

**Comment by njames93** [comment]
I added a basic debounced call to restart to the config watcher and it fixed the bug. Though I feel that the implementation could be adjusted to put this debouncing behaviour on the handler for the restart command. I've attached a simple diff of what I did, but this is the first ts code I've ever written so likely has some bug in there.
```
diff --git a/src/config-file-watcher.ts b/src/config-file-watcher.ts
index 8f3da76..fbe05f6 100644
--- a/src/config-file-watcher.ts
+++ b/src/config-file-watcher.ts
@@ -9,8 +9,18 @@ export function activate(context: ClangdContext) {
   }
 }
 
+function debounce<T extends Function>(Callback: T, WaitMilliSeconds: number) {
+  let Timer: NodeJS.Timer;
+  let callable = (...args: any) => {
+    clearTimeout(Timer);
+    Timer = setTimeout(() => Callback(...args), WaitMilliSeconds);
+  };
+  return <T>(<any>callable);
+}
+
 class ConfigFileWatcher {
   private databaseWatcher: vscode.FileSystemWatcher = undefined;
+  private debouncedClangdRestart = debounce(() => { vscode.commands.executeCommand('clangd.restart') }, 1000);
 
   constructor(private context: ClangdContext) {
     this.createFileSystemWatcher();
@@ -42,7 +52,7 @@ class ConfigFileWatcher {
 
     switch (config.get<string>('onConfigChanged')) {
     case 'restart':
-      vscode.commands.executeCommand('clangd.restart');
+      this.debouncedClangdRestart();
       break;
     case 'ignore':
       break;
@@ -53,10 +63,10 @@ class ConfigFileWatcher {
               uri.fsPath}' has been changed. Do you want to restart it?`,
           'Yes', 'Yes, always', 'No, never')) {
       case 'Yes':
-        vscode.commands.executeCommand('clangd.restart');
+        this.debouncedClangdRestart();
         break;
       case 'Yes, always':
-        vscode.commands.executeCommand('clangd.restart');
+        this.debouncedClangdRestart();
         config.update<string>('onConfigChanged', 'restart',
                               vscode.ConfigurationTarget.Global);
         break;
```

**Comment by rapgenic** [comment]
Was about to open a pull request.. :)

Anyway my implementation is quite similar to yours, if you want to compare it it's here: https://github.com/rapgenic/vscode-clangd/commit/97b2f08a8832dcdb72aebff9684b9d3161089c79

**Comment by njames93** [comment]
Gotta say yours seems much nicer than mine as you debounce the whole files changed handler, and it wasn't lazily copied then pieced together by a monkey :)

**Comment by njames93** [comment]
@rapgenic Just tried your version, working perfectly when config is empty, prompt or restart. Never get the bug about it failed to register command

**Comment by rapgenic** [comment]
@njames93 Thank you very much for trying it and giving me feedback!
